### ISSUE TITLE
Journal Import stalls

### ISSUE THREAD

**Issue by wbradney** [EDSM-NET/FrontEnd#101]
I drag a 170K file into the browser and it stalls out at 8% "sending journal events".
Tried Edge and Firefox.

**Comment by AnthorNet** [comment]
Does the browser console says anything?

**Comment by wbradney** [comment]
In Firefox:

Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”.
journal:542
[bugsnag] Loaded!
client.js:60:4
File.lastModifiedDate is deprecated. Use File.lastModified instead.
fileDrop.js:1871:4

**Comment by wbradney** [comment]
The first few files I tried uploaded fine - the largest was 27K.

**Comment by wbradney** [comment]
Edge console doesn't show any errors or warnings.

**Comment by wbradney** [comment]
I just tried again with AdBlock disabled and no change.

**Comment by wbradney** [comment]
Firing up Fiddler to see if I can see anything there...

**Comment by wbradney** [comment]
Fiddler shows about 15 POSTs to api-journal-v1, all 200 OK.
I see a variety of "Message already stored" and "Message older than the stored one" but no failures.

**Comment by AnthorNet** [comment]
May be too much journal at once and your browser takes time to proceed?
I cannot see any error reported by BugSnag right now.

**Comment by wbradney** [comment]
I left it alone for about 10 minutes and it was still showing 8%.
It only took about 10 seconds to get to 8% initially.
Not sure what could be causing it. Is there another way to bulk-load journal history?

**Comment by AnthorNet** [comment]
Can you send me the journal file in cause to contact@edsm.net

**Comment by wbradney** [comment]
Done

**Comment by AnthorNet** [comment]
Not seeing any issues, so closing for now.
