### ISSUE TITLE
Badges - unearned/earned wrongly appearing/not appearing

### ISSUE THREAD

**Issue by AndyHunt66** [EDSM-NET/FrontEnd#102]
Hi,

Various badges that I've earned are not appearing, and now I've been granted a badge which I haven't earned.
https://www.edsm.net/en/user/badges/id/17100/cmdr/CMDR+Boot
1 - Earned badges not appearing:
All of the "Be the first to discover a ..." badges.
After months around Colonia, I've first-discovered multiples of all of these, whilst submitting data via the E:D market connector.
For instance, https://www.edsm.net/en/system/bodies/id/18666231/name/Kyloall+YZ-P+d5-673
First discovered for you by me, and also in-game, my name is on both stars.

2 - Unearned badges appearing.
A couple of days ago I got awarded the "... Gone" badge. No way have I done a >200LY jump. Max is 50, and looking over my flight logs, there doesn't seem to be any anomaly in the last few days that would correspond 

These are obviously *not* urgent issues, as the value in your site is way more than the badges :-)

And thank you for the christmas card with a plot of my journeys - nice touch !

thanks,

Andy

**Comment by NecroBones** [comment]
Interesting. I hadn't noticed any being awarded that I didn't earn, but I can say I've also had some that were not awarded at all, or were awarded after a significant delay. It seemed like a few of them wouldn't award, until something else was being awarded.

I can't remember which ones behaved that way, except that Wolf Hunter was delayed quite a bit, and I still haven't received Thargoid Encounter, despite taking samples from Cyclops variants probably half a dozen times. The latter might have something to do with the fact that I was doing that around the time that the badge was created. I don't know what EDDiscovery reports and how this one is triggered. Kilo Run is also a few days late so far, but I know many of these are not awarded in real time.

**Comment by NecroBones** [comment]
As an update-- I was never awarded with Thargoid Encounter, despite taking cyclops samples several times during the week that the badge was added, both before and after. How is this one tracked?

**Comment by AnthorNet** [comment]
@AndyHunt66 Looks like the is a "BooT" account on EDSM, while yours is "Cmdr Boot", then if you submit with only "BooT" to EDDN there is no way for us to track your bodies!
The other account was never used so if you in game name is BooT, I can delete the old account and rename.

**Comment by AnthorNet** [comment]
@NecroBones I suspect you need to create a separate issue please :)

**Comment by NecroBones** [comment]
@AnthorNet Will do.

**Comment by AndyHunt66** [comment]
Hi - Thanks for looking at this.
I'm submitting as CMDR Boot, as I couldn't create an account for Boot.
Just so you know - all money, scans, travel etc.etc. are showing up absolutely fine - just the badges are a bit skewed. (So I don't think the underlying problem is due to the account name.....)

Cheers,

**Comment by AnthorNet** [comment]
The old BooT account is deleted, so you can rename your account to your in game commander name.
You can reimport your journal directly on EDSM, which will unlock the proper scan and badges.
