### ISSUE TITLE
Suggestion: Habitable zone info.

### ISSUE THREAD

**Issue by ghost** [EDSM-NET/FrontEnd#107]
If possible please add the habitable zone info of a star on to the Celestial Objects main tab. There seams to be a formula in EDMC plugin.

Thanks,

Fly/land safe.

CMDR Steyla

**Comment by AnthorNet** [comment]
Testing this, right now strangely I don't get the same results as the @marginal plugin.

**Comment by AnthorNet** [comment]
If I check Jackie's thread, it work pretty much!
