### ISSUE TITLE
Pimp my Ride and Kilo Run badges not lighting up for me

### ISSUE THREAD

**Issue by wbradney** [EDSM-NET/FrontEnd#109]
I do seem to have achieved these, and I have uploaded all of my journals. Any way to diagnose?

**Comment by NecroBones** [comment]
Yeah, Kilo Run, and 1,000,000 ly club aren't awarding for me either. I'm not sure if these are just updated on a more monthly cycle, or if they're bugged?

**Comment by AnthorNet** [comment]
Should work better on 3.0 with the new statistics.
