### ISSUE TITLE
Add a nightly dump for recent bodies, 7 days?

### ISSUE THREAD

**Issue by NecroBones** [EDSM-NET/FrontEnd#111]
There's a nightly dump of recent systems for the last 7 days, but not an accompanying one for bodies. This necessitates downloading the bodies.json dump repeatedly if you wish to maintain current data. Any chance of adding a 7 days recent dump nightly, like we have now for systems?

**Comment by AnthorNet** [comment]
Should be up tomorrow, if no errors were made ;)

**Comment by NecroBones** [comment]
This is wonderful. Thanks!
