### ISSUE TITLE
Feature Request - List/Sort/Filter all objects with first discovery by Commander

### ISSUE THREAD

**Issue by zebarmy** [EDSM-NET/FrontEnd#112]
Would it be possible to add functionality to allow a commander to look up all objects they have first discovery on? For instance, I quite often scratch my head and wonder where the Earth-like world I first discovered is located.

Having the option to search by first discovered by (current commander), and then filter down by body type into Ammonia World, or Earth-like, Rocky, etc would be super useful :)

Thanks in advance!

Zebarmy

**Comment by AnthorNet** [comment]
Filters added to both system and celestial body search.
