### ISSUE TITLE
CMDR Credits total picking up alt account

### ISSUE THREAD

**Issue by yobortom** [EDSM-NET/FrontEnd#113]
The "Credits" graph on the CMDR Profile has dips showing my alt account total credits. I can only assume this is picking up my alt account under the wrong CMDR Name.

**Comment by AnthorNet** [comment]
Checked and working fine on our side, which software are you using?

**Comment by yobortom** [comment]
@AnthorNet I'm using EDMC. This is what I'm seeing. [https://imgur.com/qZcZQ5u](https://imgur.com/qZcZQ5u)

**Comment by AnthorNet** [comment]
Which commander name?

**Comment by yobortom** [comment]
CMDR Tom D

**Comment by AnthorNet** [comment]
Added a delete button in the account book, and fixed your account, as much as I can, not sure what happens, it's not a known issue, but if it happens again on the last version of EDMC, try submit an issue there.

**Comment by yobortom** [comment]
Thank you!
