### ISSUE TITLE
Allow Galactic Map to scale with screen resolution

### ISSUE THREAD

**Issue by ElanSolo** [EDSM-NET/FrontEnd#115]
As described in the linked tweet.  I'd love the window for the Galactic Map to scale to fill some more of my 4k screen.  :)

https://twitter.com/elanstreaming/status/955086513783672832/photo/1

**Comment by millstonebarn** [comment]
And my 16:9 ultra-wide :-)   (3440x1440)

I make the point only for consideration of different aspect ratios.

**Comment by AnthorNet** [comment]
As a first start is it better when looking at a route?

**Comment by AnthorNet** [comment]
Ha no doesn't change a thing!

**Comment by AnthorNet** [comment]
Added fullscreen support ;)
