### ISSUE TITLE
black hole Badge not registering 

### ISSUE THREAD

**Issue by MissPolgara** [EDSM-NET/FrontEnd#122]
I discovered two black holes today but didn't get the badge and have the screenshots below?

https://1drv.ms/f/s!AtCokBvlcMJrmmcwSCbOoPAOGJJR

https://www.edsm.net/en/user/badges/id/41660/cmdr/Miss+Polgara

**Comment by AnthorNet** [comment]
You need to use EDMC, or import your journal files directly on EDSM.
Or wait for EDD 9.1 which will use our new API.

In the meantime you still need to upload your journal files and it should trigger the first scan and the badge.
