### ISSUE TITLE
Thargoid Encounter and Kilo Run badges not awarding.

### ISSUE THREAD

**Issue by NecroBones** [EDSM-NET/FrontEnd#123]
Account is "Orvidius". Took thargoid (cyclops) tissue samples both before and after the Thargoid Encounter  badge was added, during those first couple of weeks of 2.4, but was not awarded the badge. Also passed 1000 hours of play at the start of January, but not awarded Kilo Run.

**Comment by AnthorNet** [comment]
Kilo Run must be the amount shown in the dashboard, right now you're only at 500h calculated by EDSM.
With 3.0 the badges will be consistent with the game.

For Thargoids, I need to check further

**Comment by AnthorNet** [comment]
Thargoids encounter is given when a cargo is saved on the database, for any of the 3 tissue sample.
It will only trigger on new cargo.

**Comment by NecroBones** [comment]
OK, but I had picked up the samples on several occasions without it awarding, so I have no idea where the disconnect is. Last time was probably October, after the badge was created.

**Comment by AnthorNet** [comment]
I added the badge into the CollectCargo event, so please try uploading the journal files on EDSM, it should trigger the badge ;)

**Comment by NecroBones** [comment]
Awesome, that worked. Thanks! :)
