### ISSUE TITLE
Weird rendering bug when displaying credits graph at /dashboard/account

### ISSUE THREAD

**Issue by WaldemarLehner** [EDSM-NET/FrontEnd#128]
Using Google Chrome Version 64.0.3282.167 
https://drive.google.com/file/d/1WIQxkbpgYlyJlQMC46cmqpJuQwFAbRlK/view?usp=sharing

**Comment by WaldemarLehner** [comment]
This issue doesnt seem to appear in Mozilla (for me, at least) (v 57.0.4)

**Comment by AnthorNet** [comment]
Odd, I can't reproduce.

**Comment by WaldemarLehner** [comment]
Weird. Also happens when running in incognito for me.
As for hardware...
GPU: GTX 1060 6GB
CPU: Intel Xeon E3-1231 v3 3.4GHz

**Comment by WaldemarLehner** [comment]
ok. Now that's interesting. The rendering error disappeared when I turned off Hardware Acceleration.

**Comment by AnthorNet** [comment]
Possibly some weird things over rendering engine, and external library, not sure we can do anything about it on our end.
Might update/change the library at some point.
