### ISSUE TITLE
Imported Fleet Incorrect (Initial Journal Population)

### ISSUE THREAD

**Issue by DaddaTheButt** [EDSM-NET/FrontEnd#131]
About 3Weeks playing ED. Signed up for EDSM couple of days ago - some good stuff here.

Cat'd the journals and dragged over to import page - all seems OK but only ship in resultant 'Fleet' is  the original Sidewinder (marked as 'Sold') and profile shows current ship as Sidewinder (DB-01). Should be Asp Explorer (DB-03) having passed through a Diamondback Scout (DB-02).

Looking at the journal import progress the parsing does 'progress' through all three ships but they don;t seem to make it to 'Fleet' or 'Profile'/CurrentShip.

Happy to share the journal for analysis (2MB) but privately as opposed to 'public' attachment.

**Comment by AnthorNet** [comment]
You can send us the journal to contact@edsm.net

**Comment by AnthorNet** [comment]
New event should fix it
