### ISSUE TITLE
Chieftan Paint Jobs

### ISSUE THREAD

**Issue by kylie3605** [EDSM-NET/FrontEnd#135]
Attached are all currently available Alliance Chieftan paint jobs for EDSM Fleet tab

[c6.zip](https://github.com/EDSM-NET/FrontEnd/files/1773642/c6.zip)
[c5.zip](https://github.com/EDSM-NET/FrontEnd/files/1773643/c5.zip)
[c4.zip](https://github.com/EDSM-NET/FrontEnd/files/1773644/c4.zip)
[c3.zip](https://github.com/EDSM-NET/FrontEnd/files/1773645/c3.zip)
[c2.zip](https://github.com/EDSM-NET/FrontEnd/files/1773646/c2.zip)
[C1.zip](https://github.com/EDSM-NET/FrontEnd/files/1773647/C1.zip)
![stock](https://user-images.githubusercontent.com/27835708/36882694-3ea15ba6-1d8a-11e8-9ff3-2584c239edb9.png)

**Comment by AnthorNet** [comment]
It's uploading, thx!
