### ISSUE TITLE
Unexpected "first scanned by" entry in celestial bodies records view

### ISSUE THREAD

**Issue by meiergeorg** [EDSM-NET/FrontEnd#144]
In Records > Gas giant with ammonia-based life
it says "Zekonnd" and an identical timestamp for the "This body was first scanned by/on" information for:
Coldest planet: | Dryooe Flyou DE-H b53-26 A 2 | 100 K | Zekonnd
as well as for: 
Most represented in: | Sifeae WZ-K c10-1 | 5 | Zekonnd

But Zekonnd has never been in the latter system (see flight log of cmdr Zekonnd), and the edsm entry for Sifeae WZ-K c10-1 has no discoverer/no traffic report at all ("There is no traffic report for Sifeae WZ-K c10-1").

I would expect, that no name is displayed in such cases, like for example in Records > Class V gas giant > Smallest planet.

Similar cases are visible in 
- Records > Class V gas giant > Most represented in 
- Records > Helium-rich gas giant > Most represented in 
where the shown systems have a traffic report, but the discoverer of the system is someone else. Again,  the discoverer of the coldest planet is shown unexpectedly.

I would expect that the system's first dicoverer is then shown, even if the planets may have been scanned by different cmdrs.

Thank you for your great work with that website. It's evolving fast and I use and like it very much!

**Comment by AnthorNet** [comment]
Fixed with https://github.com/AnthorNet/www.edsm.net/commit/f0972930466f9a84d3a341de7afd4cf94f887c95
