### ISSUE TITLE
Bug by Mission board

### ISSUE THREAD

**Issue by Warlkar** [EDSM-NET/FrontEnd#149]
Mission board dont display accepted missions.
its marked that 2 missions active but this will not displayed.

(synced with EDDiscovery 9.1.8.0)

**Comment by AnthorNet** [comment]
Are they still marked after refresh? Should only happen if the script spotted expired mission

**Comment by Warlkar** [comment]
http://prntscr.com/iwjolm <--- screenshot

**Comment by AnthorNet** [comment]
Fixed
