### ISSUE TITLE
Data Tab shows more Datas then allowed

### ISSUE THREAD

**Issue by Deamawa** [EDSM-NET/FrontEnd#151]
Hello! Please see by yourself:

![inkededsm_li](https://user-images.githubusercontent.com/27950801/38303205-9e287ce0-3805-11e8-87b1-d0c7c10ac7ee.jpg)

**Comment by AnthorNet** [comment]
Please send a capture from in game.
Some data have changed their grades, and some limit don't follow the grade.

**Comment by Deamawa** [comment]
Checked again. its in total max. 150. But 100 max is not correct. btw. Guardian Power Conduit  shows max 300. it is 250.

**Comment by AnthorNet** [comment]
Please send me the ingame screen so I can check the current icon and make the needed changes ;)

**Comment by Deamawa** [comment]
![elite - dangerous client 08 04 2018 14_36_10 2](https://user-images.githubusercontent.com/27950801/38467575-e9f01efc-3b3a-11e8-90d8-26258f0d7f8a.png)

**Comment by Deamawa** [comment]
above requested
