### ISSUE TITLE
Api won't pull up.

### ISSUE THREAD

**Issue by demyroku** [EDSM-NET/FrontEnd#154]
Every time I try and grab my API it returns a message saying "PC users only" what should I do?
![capture 1](https://user-images.githubusercontent.com/13934763/38477339-1764e2ce-3b80-11e8-8665-c9edb0162db8.PNG)
![capture 2](https://user-images.githubusercontent.com/13934763/38477344-1a32ab12-3b80-11e8-9b8f-3992afa848a5.PNG)
![capture 3](https://user-images.githubusercontent.com/13934763/38477345-1c901304-3b80-11e8-8391-4d291030a43a.PNG)
![capture 4](https://user-images.githubusercontent.com/13934763/38477348-1edff822-3b80-11e8-864e-c59cad008b74.PNG)

**Comment by klightspeed** [comment]
This suggests you have registered as a console user.

Consoles don't have a journal, and it's not possible to query Frontier's Companion API for ship status, so an EDSM API key is useless for console users.

**Comment by AnthorNet** [comment]
No news, closing.

If you're a console player, there is no API available. If you created a wrong account, contact us to convert your account to a PC one.
