### ISSUE TITLE
Suggestion: Estimated Value for a system, visible on the flight log

### ISSUE THREAD

**Issue by Caintain** [EDSM-NET/FrontEnd#156]
I'd suggest, for the explorers who're tracking their progress using the EDSM flight log, adding the estimated value of a system (currently visible on the system's page) to the flight log.
![image](https://user-images.githubusercontent.com/30013820/38786647-dfcbd81c-40ee-11e8-9bea-c1fb9699b59f.png)

**Comment by AnthorNet** [comment]
Done ;)
