### ISSUE TITLE
Guardian Power Conduit max incorrect

### ISSUE THREAD

**Issue by D3JA5U** [EDSM-NET/FrontEnd#160]
Hi,

in-game the cap for Guardian Power Conduit is 250. EDSM setting is 300.

Thanks.
Regards.

**Comment by AnthorNet** [comment]
Hi, thx, can you send a screenshot of the game, to check which rarity level it holds.

**Comment by D3JA5U** [comment]
Hi, screenshot now attached - rarity level 2 in-game.

![guardian power conduit screenshot](https://user-images.githubusercontent.com/38751941/39404637-37c21470-4b97-11e8-8f2d-ea6aaf1fcf61.jpg)

**Comment by b166er** [comment]
here from me:
![screenshot](https://user-images.githubusercontent.com/679114/39404926-3d2cec00-4b9c-11e8-9ba8-b63fa2b2e959.png)

i found here another screenshot: https://canonn.science/codex/guardian-structure/ 
![sentinel-loot](https://user-images.githubusercontent.com/679114/39404846-2d8d24e6-4b9b-11e8-9de1-131fd129356f.png)
direct link to screenshot: https://canonn.science/wp-content/uploads/2018/03/Sentinel-loot.png
