### ISSUE TITLE
Paintjob show the last selected not the current one

### ISSUE THREAD

**Issue by b166er** [EDSM-NET/FrontEnd#163]
how to reproduce: 
1. buy a sidewinder
2. send data with EDMC, edsm show the ship
3. select a new paintjob (e.g. Tactical Graphite), send data with EDMC, -> edsm show "Default"-Paintjob
4. logout
5. login
6. select another paintjob (e.g. tactical ice), send data to edsm -> edsm show "Tactical Graphite" as current paintjob

**Comment by AnthorNet** [comment]
Does it work if you import the journal on EDSM directly?
Can you join the associated journal?

**Comment by b166er** [comment]
thats weird, i sold some ships (e.g. eagle) then buy a sidewinder, edmc was running on background and send data every minute. edsm show first my asp explorer as current active ship, i upload my journals, now is my solded eagle active, even though I'm in the sidewinder. 
![image](https://user-images.githubusercontent.com/679114/39569526-c10836a2-4ec5-11e8-9196-e5a759ceaec9.png)

edit: after changing the ship to another, and then back, edsm show now the correct ship (with active edmc)

edit2: ok, i found the problem, it's seems a "bug" in game, i dont found any entry's for changing paintjob for current ship. i think this issue can be closed here.

**Comment by AnthorNet** [comment]
It should be fixed for the next uploads
