### ISSUE TITLE
Suggestion: reputation search-filter for minor-factions

### ISSUE THREAD

**Issue by b166er** [EDSM-NET/FrontEnd#164]
I don't know if it is possible, but it would be nice to search in minor factions and filter & sort by reputation to my profile. 
e.g. 

Name | Allegiance | Government | Home System | Reputation
------ | ------------ | ------------- | ---------------- | ------------
Sol Nationalists | Federation | Democracy | Sol | 56%
Sol Workers' Party | Federation | Democracy | Sol | 0%

so I can choose the faction where the reputation low and work for them to ranking up.

**Comment by AnthorNet** [comment]
There is sadly no reputation known for the player, appart for the main allegiances.

**Comment by b166er** [comment]
what about this journal entries: 

```
{ "timestamp":"2018-05-03T14:18:37Z", "event":"MissionAccepted", "Faction":"Aegis Research", "Name":"Mission_AltruismCredits", "LocalisedName":"Donate 1,000,000 Cr to the cause", "Donation":"1000000", "Expiry":"2018-05-03T17:58:08Z", "Wing":false, "Influence":"Med", "Reputation":"Med", "MissionID":374741250 }


{ "timestamp":"2018-05-03T14:18:46Z", "event":"MissionCompleted", "Faction":"Aegis Research", "Name":"Mission_AltruismCredits_name", "MissionID":374741250, "Donation":"1000000", "Donation":1000000, "FactionEffects":[ { "Faction":"Aegis Research", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_boom_up;", "Effect_Localised":"$#MinorFaction; are experiencing increased growth that could lead to an economic boom", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":224644818084, "Trend":"UpGood" } ], "Reputation":"UpGood" } ] }
```

if a user will upload he's logs, the reputation can maybe "reconstructed" from "Reputation: UpGood", e.g. if you do 10x times (i dont know how many you need, its just an example) mission for the same minor faction, and the mission has "Reputation":"High", then you have theoretically 100%.

**Comment by AnthorNet** [comment]
Not possible right now.
