### ISSUE TITLE
Can not send data to EDSM

### ISSUE THREAD

**Issue by JoBaccaroo** [EDSM-NET/FrontEnd#166]
Hi,
i just encountered an new bug.
since today EDMC always returns the Message Could not send data to EDSM while i am exploring. Yesterday there was no such bug and all data was sended correctly to EDSM.
I have also tried to renew the API key with no effect.

**Comment by AnthorNet** [comment]
Hi,

Where are you from?
Does it work if you import your journal files directly from EDSM?

**Comment by JoBaccaroo** [comment]
I am from Austria
Yes it works but slowly
Now i found out, that it does work sometimes, sometimes not. (with EDMC)
I am already flying to beagle point via SagA, with the next jump i take another look

**Comment by JoBaccaroo** [comment]
![image](https://user-images.githubusercontent.com/17493882/40104217-069c5a70-58f0-11e8-9682-7287f5b5db40.png)
the lower Error Message came without any action from me hitting the button or so
as i entered this system my location in edsm was renewed correctly
After the next Jump it took 3 tries to actualize EDMC to make it send the location to edsm

**Comment by klightspeed** [comment]
What version of EDMC are you using?

**Comment by JoBaccaroo** [comment]
3.0.5.0

**Comment by AnthorNet** [comment]
Should be fixed now.
