### ISSUE TITLE
EDSM  Persistent 502: Bad Gateway error

### ISSUE THREAD

**Issue by darth-crunchus** [EDSM-NET/FrontEnd#167]
I've been using the site for about twenty minutes, but every link I click on, I have to reload the page due to a 502 error on the first try.  EDSM is the only site that has been giving me this issue today, so I thought I'd bring it to your attention, in case it's a sign of a larger problem.  I'm using Mozilla Firefox to view the site.

**Comment by AnthorNet** [comment]
Hi,
Thanks for your report, we are aware of some load issue today, which should been resolved now.

**Comment by darth-crunchus** [comment]
You're welcome.  Love the site, by the way.  It's a fantastic resource for the community!
