### ISSUE TITLE
Removal of locked distances

### ISSUE THREAD

**Issue by gregmcdougall** [EDSM-NET/FrontEnd#168]
You remove distance references between two green/locked systems automatically, but this removal doesn't seem to include hidden distances. Could you amend the removal routine to include hidden distances too?

**Comment by AnthorNet** [comment]
From what I remember they are only hidden and removed 6 month after, but only if they match, non matching distances aren't touched.

**Comment by gregmcdougall** [comment]
So 'red' (invalid) distances between two 'green' (locked) systems aren't removed after being hidden? Sol is a good example - loads of distances from it (green/locked) to amber systems, but also a whole bunch of stored hidden distances between it and other green/locked systems - surely these could be removed once both of the end systems 'go green/locked'?
