### ISSUE TITLE
How do i submit distances?

### ISSUE THREAD

**Issue by Stompmaster** [EDSM-NET/FrontEnd#169]
Hi guys, as above how do i submit distances?  through logs?

**Comment by klightspeed** [comment]
On a system that doesn't have known coordinates (e.g. a system from https://www.edsm.net/en/systems/front or https://www.edsm.net/en/systems/unresolved), click the Distances tab, and submit your current system and its current distance to that system as shown in the Elite Dangerous galaxy map.

Systems can be submitted by submitting your journals through the journals page in your EDSM profile (https://www.edsm.net/en/settings/import/journal).  Using the API key (https://www.edsm.net/en/settings/api), you can also use a program such as EDMC (which submits systems as you jump into them when it's running), EDDiscovery (which can submit your travel history to EDSM) or EDDI to submit systems to EDSM.
