### ISSUE TITLE
Bodies missing in LHS 1573

### ISSUE THREAD

**Issue by ghost** [EDSM-NET/FrontEnd#17]
Added bodies to the LHS 1573 system manually via ROSS, need to be added to EDSM manually per Anthor.

https://www.edsm.net/en/system/id/4705/name/LHS+1573
https://eddb.io/system/bodies/11843

**Comment by AnthorNet** [comment]
Will need to add a proper way to add the bodies along with some missing fields.

**Comment by AnthorNet** [comment]
Waiting for 2.4
