### ISSUE TITLE
Trailblazer badge not awarding

### ISSUE THREAD

**Issue by ArkanaCode** [EDSM-NET/FrontEnd#171]
Hello, 

just wanted some assistance with the badge.
I have been out in the black for a while, still am, so I collected a lot of data.
I swung by a station and sold it, resulting in my Exploration rank to rise.

I am a Pathfinder now, but since the large amount of data promoted me to Trailblazer, and then immediately Pathfinder, the badge apparently didn't register.

Could there be a way to trigger it?

CMDR Capt. Ragnarok

**Comment by ArkanaCode** [comment]
It has just triggered, thanks for the help!

**Comment by AnthorNet** [comment]
Good to know :)
Enjoy!

**Comment by ArkanaCode** [comment]
Will do :)
