### ISSUE TITLE
CL PISMIS 15 Erroneous Celestial Bodies

### ISSUE THREAD

**Issue by SeeJayEmm** [EDSM-NET/FrontEnd#174]
CL PISMIS 15 has 3 planets listed that do not exist.  The only objects that exist are CL PISMIS A and CL PISMIS B

https://www.edsm.net/en/system/bodies/id/45101/name/Cl+Pismis+15

https://steamuserimages-a.akamaihd.net/ugc/952957448629635823/4C1A617E90353BE297CF566B949ADF7D6D8637DA/

**Comment by klightspeed** [comment]
They were discovered on 21 Mar 2018, and last updated on 23 Mar 2018, which makes me suspect they were an artifact of 3.0.3's alteration of some system masses (3.0.3 came out 19 Mar 2018, and 3.0.4 came out 27 Mar 2018)

**Comment by RapidfireCRH** [comment]
Removed the 3 gas giants.

**Comment by AnthorNet** [comment]
Thx
