### ISSUE TITLE
Pattern Obelisk Data has wrong limit in inventory-data

### ISSUE THREAD

**Issue by b166er** [EDSM-NET/FrontEnd#175]
please fix the cargo limit for Guardian Patter * Obelisk Data.

Name | EDSM | Game Cargo
------- | ------ | -------
Pattern Alpha Obelisk Data | 200 | 150
Pattern Beta Obelisk Data | 250 | 150
Pattern Delta Obelisk Data | 150 | 150
Pattern Epsilon Obelisk Data | 150 | 150
Pattern Gamma Obelisk Data | 300 | 150

![image](https://user-images.githubusercontent.com/679114/42051922-a3fe3aa6-7b0d-11e8-9db3-4653de1d13f8.png)

**Comment by AnthorNet** [comment]
New to 3.1 I guess?

**Comment by b166er** [comment]
> New to 3.1 I guess?

i dont know if it was like this before in 3.0, but yes, it's fresh screenshot from 3.1. maybe bug in 3.1?
