### ISSUE TITLE
"View as list" option no longer present on Flight Log page

### ISSUE THREAD

**Issue by amloessb** [EDSM-NET/FrontEnd#177]
The Flight Log page used to have a button next to the _Export_ button that let you view the flight log as a list, but it seems to no longer be present.  I found this option extremely useful for calculating my total number of jumps and distance jumped in a session, so I'd love it if you brought this option back.

Thanks!

**Comment by AnthorNet** [comment]
Ok, while I do not intent to maintain both page as it is too much work, it is still available and I will add it back on popular request.

When I have time I might rebrand the timeline one so it's easily switchable.

I'll try to add the link back tomorrow.
