### ISSUE TITLE
Sectors with known coords are appearing in systemsWithoutCoordinates.json

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#18]
systems that are in the json with coords (so far):
Assairshch AK-I d9-209
Bloomoa YU-Y f190
Byaa Ail FZ-S d3-1

this is with a fresh download this morning:
![image](https://user-images.githubusercontent.com/30603500/29052555-2cb5d7d4-7ba8-11e7-88e4-7070a6eb101d.png)

**Comment by RapidfireCRH** [comment]
Byeethao FV-G d10-22

**Comment by klightspeed** [comment]
All of those systems have duplicates in EDSM.

**Comment by RapidfireCRH** [comment]
This might be related to Issue #19, if they are showing two entries

**Comment by AnthorNet** [comment]
Possible duplicate of issue#19

**Comment by RapidfireCRH** [comment]
https://www.edsm.net/en/system/id/14897402/name/Wrupeae+QT-Q+e5-4126
System has known coords but was pulled from the above unknown data

**Comment by AnthorNet** [comment]
@RapidfireCRH Can you state the line in the file with the according id?
If i's all duplicates, I think the problem lies in #19 and we will continue there.

**Comment by RapidfireCRH** [comment]
The last one didnt have a duplicate. Ive given you line numbers and ID's in the other issue

**Comment by AnthorNet** [comment]
Wrupeae QT-Q e5-4126 was submitted with EDSM after the dump, so it's fine.

**Comment by AnthorNet** [comment]
Closing as duplicate from #19
