### ISSUE TITLE
Badges Not Being Awarded Correctly With Uploaded Journal Data

### ISSUE THREAD

**Issue by LivewareCascade** [EDSM-NET/FrontEnd#181]
EDSM is not correctly awarding me the following badges:
- Centre of the Galaxy (Visit Sag A*)
- Is there anybody out there? (Visit Colonia)

This is despite me uploading my journals to EDSM, both manually and also using EDDiscovery.
I know that EDSM recognizes that I have visited those systems, since both systems appear in my flight log:

Callsign is CMDR LivewareCascade:

Sag A* [Apr 15, 2017, 9:13:55 PM]
Colonia [Apr 16, 2017, 9:10:52 PM]

**Comment by AnthorNet** [comment]
If it was before we implemented badge, delete the log, then reimport your log.
Checking the code, all should work fine.

**Comment by LivewareCascade** [comment]
Thank you, that worked perfectly.
