### ISSUE TITLE
Galactic Map certificates expired?

### ISSUE THREAD

**Issue by waterlubber** [EDSM-NET/FrontEnd#182]
I noticed that the Galactic Map wasn't working for me, and was rendering as entirely black. 
![image](https://user-images.githubusercontent.com/7517025/42536571-7382b3fa-8460-11e8-9664-ff73c85f16ea.png)

I poked around in Chromium's debugger, and it was throwing a bunch of certificate errors. 
I managed to get it working by launching Chromium with the `--ignore-certificate-errors` and `--disable-web-security` flags:
![image](https://user-images.githubusercontent.com/7517025/42536596-8433129e-8460-11e8-804d-6a53312c6fcb.png)
It should be mentioned that this is only the backdrop, the little PoI things work.

I believe the domain with the expired cert is static.edsm.net

**Comment by AnthorNet** [comment]
Fixed
