### ISSUE TITLE
Feature Request Distance to Sol in Station Search

### ISSUE THREAD

**Issue by austeregrim** [EDSM-NET/FrontEnd#185]
Add distance to Sol and Colonia in search results of Station Search. Similar to Distance to Commander Position column, but keeping the sort by distance to Commander.

This function would enable the ability to see if one station is closer to Sol or Colonia than another to keep on a course towards the bubble or Colonia area. Another option is to provide the Z Axis, or all Axis' of the System in the search results.

**Comment by RapidfireCRH** [comment]
To add on to this request, It would be nice to combine these stations in a "Bubble, Colonia, and Outlier." Bonus if they could have their own symbols :D

**Comment by AnthorNet** [comment]
Added distances in tooltips in stations search
