### ISSUE TITLE
Station data not updated with "Docked" event

### ISSUE THREAD

**Issue by bgol** [EDSM-NET/FrontEnd#186]
Looks like EDSM does generate a new stations with commodities/shipyard/outfitting messages from EDDN but not with journal/Docked?

"Bunnell Port"
https://www.edsm.net/en/system/stations/id/5933/name/HIP+56145/details/idS/63741/nameS/Bunnell+Port
https://ross.eddb.io/eddn/log/75706077

"Shalatula Terminal"
https://www.edsm.net/en/system/stations/id/184470/name/Pegasi+Sector+EL-Y+d96/details/idS/63738/nameS/Shalatula+Terminal
https://ross.eddb.io/eddn/log/74170014

"Sheffield's Folly"
https://www.edsm.net/en/system/stations/id/1846582/name/Col+285+Sector+ZB-R+b19-2/details/idS/63737/nameS/Sheffield%27s+Folly
https://ross.eddb.io/eddn/log/74165521

**Comment by AnthorNet** [comment]
The four events should lead to the creation but only the docked one contains the distance and the type.
I will run a full check see why it haven't put it.

**Comment by AnthorNet** [comment]
It should be fixed on next docking.
