### ISSUE TITLE
missing "Ship Flight Data"

### ISSUE THREAD

**Issue by b166er** [EDSM-NET/FrontEnd#188]
i was able to scan and collect some http://elite-dangerous.wikia.com/wiki/Ship_Flight_Data from Thargoid Vessel, but i cannot see the data on my edsm-page: https://www.edsm.net/en/dashboard/inventory/data can you please add the missing data. thank you!

**Comment by AnthorNet** [comment]
Which software are you using?

**Comment by b166er** [comment]
I'm sorry, it's my mistake, thank you for the hint with the software. I thought the program was on, all the time. i'm, using EDDiscovery. 
btw, maybe it's better to see all the data/materials, even if it is empty?
