### ISSUE TITLE
Spliech UE-Y c14-0 duplicated

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#19]
https://www.edsm.net/en/system/id/14285265/name/Spliech+UE-Y+c14-0
Frontpage search for Spliech UE-Y c14-0 turns up two results, one which was added as a poi by Corbin Moran and one that is unknown.
https://imgur.com/xh3S2b8

**Comment by RapidfireCRH** [comment]
this also happens with 
Crookie KG-N c20-16, 
Chau Euq IA-A d0, 
Cyoangeia QL-N c23-1 
Dryafao MK-R c7-0
Dryi Fraae UZ-S c3-0
Dryu Auf NT-H d10-50

**Comment by AnthorNet** [comment]
I will rum a complete check for duplicate.
Might be something wrong changed somewhere in the duplicate handling.

**Comment by RapidfireCRH** [comment]
Assairshch AK-I d9-209 - Line 5254247: {"id":7809757,"name":"Assairshch AK-I d9-209","date":"2016-12-12 00:00:04"},
Bloomoa YU-Y f190 - Line 5309763: {"id":8969580,"name":"Bloomoa YU-Y f190","date":"2017-01-21 00:00:19"},
Byaa Ail FZ-S d3-1 - Line 5989487: {"id":13115804,"name":"Byaa Ail FZ-S d3-1","date":"2017-06-06 21:46:13"},
Byeethao FV-G d10-22 - Line 5421987: {"id":9994481,"name":"Byeethao FV-G d10-22","date":"2017-02-21 00:00:44"},
Wrupeae QT-Q e5-4126 - Line 6030521: {"id":14897402,"name":"Wrupeae QT-Q e5-4126","date":"2017-08-04 20:25:17"},
Be careful with this one ^. I saw only one entry in EDSM
Spliech UE-Y c14-0 - Line 6025253: {"id":14285276,"name":"Spliech UE-Y c14-0","date":"2017-07-16 00:02:18"},(edited)
Crookie KG-N c20-16 - Line 5309339: {"id":8791315,"name":"Crookie KG-N c20-16","date":"2017-01-15 00:00:19"},
Chau Euq IA-A d0 - Line 5998519: {"id":13389952,"name":"Chau Euq IA-A d0","date":"2017-06-16 00:02:37"},
Cyoangeia QL-N c23-1 - Line 6030459: {"id":14844373,"name":"Cyoangeia QL-N c23-1","date":"2017-08-02 20:04:17"},
Dryafao MK-R c7-0 - Line 6016243: {"id":13826508,"name":"Dryafao MK-R c7-0","date":"2017-06-30 00:02:31"},
Dryi Fraae UZ-S c3-0 - Line 5252393: {"id":7540634,"name":"Dryi Fraae UZ-S c3-0","date":"2016-12-04 00:00:04"},
Dryu Auf NT-H d10-50 - Line 6026027: {"id":14483707,"name":"Dryu Auf NT-H d10-50","date":"2017-07-23 00:03:17"},

**Comment by AnthorNet** [comment]
OK, I found 852 of them, while it looks there is much, it's not, compared to the new systems entered each days! Now to fix them.

**Comment by AnthorNet** [comment]
All systems should have been fixed, will monitor in case happens, but no real fix yet.

**Comment by AnthorNet** [comment]
This should be fixed now :)
