### ISSUE TITLE
[API] Empty array is returned when no faction's history data, but should be dict.

### ISSUE THREAD

**Issue by IgaguriMK** [EDSM-NET/FrontEnd#191]
At `api-system-v1/factions` endpoint, result contains faction's influence / status / pending status / recovering status history.

The history data format is dictionary. unix epoch key and values.
```json
"influenceHistory":{"1507898805":0.44012,"1507900097":0.38745,"1507900421":0.44012, ... },
"stateHistory":{"1507992717":"Boom","1507993351":"Civil war", ...},
"recoveringStatesHistory":{"1501549816":[{"state":"Boom","trend":0}],"1501551115":[{"state":"Boom","trend":0}], ... },
```

So, that should be empty dict when no history.
```json
"influenceHistory":{}
```

But that are empty array.
```json
"influenceHistory":[],
"stateHistory":[],
"recoveringStatesHistory":[],
"pendingStatesHistory":[],
``

**Comment by klightspeed** [comment]
If the code currently uses `Array()`, and always treats it as an associative array, then using `ArrayObject()` instead of `Array()` should have it encode as objects instead of arrays when there are no entries.

**Comment by IgaguriMK** [comment]
Fix "recoveringStatesHistory" and "pendingStatesHistory", neither "recoveringStates" nor "pendingStates".

**Comment by AnthorNet** [comment]
Odd, do you have a precise example?

**Comment by IgaguriMK** [comment]
## Infuluence

"influence" should be single value, and is
```
"influence": 0.55
```

"influenceHistory" should be a dict. The key is unix epoch as string. and value is float.
```
"influenceHistory": {"1507898805":0.44012,"1507900097":0.38745}
```
when no history, the dict should be empty.
```
"influenceHistory": {}
```

## (Current) State

"state" and "stateHistory" like "influence", but value is string.

```
"state": "Boom"
```
```
"stateHistory": {"1507898805": "Boom", "1507900097": "War"}
```
```
"stateHistory": {}
```

## Pending States

"pendingStates" is array of dict, that include "state" and "trend".
```
"pendingStates": [{"state":"Boom","trend":0}, {"state":"War","trend":0}]
```
If no pending states exist, it should be empty array.
```
"pendingStates": []
```

"pendingStatesHistory" should be dict of array of dict.
```
"pendingStatesHistory": {
    "1501549816":[{"state":"Boom","trend":0}],
    "1501551115":[{"state":"Boom","trend":0}, {"state":"War","trend":0}]
}
```
If no histories exist, it should be empty dict.
```
"pendingStatesHistory": {}
```

## Recovering States

"recoveringStates" and "recoveringStatesHistory" is like "pendingStates" and "pendingStatesHistory".
```
"recoveringStates": [{"state":"Boom","trend":0}, {"state":"War","trend":0}]
```
```
"recoveringStates": []
```
```
"recoveringStatesHistory": {
    "1501549816":[{"state":"Boom","trend":0}],
    "1501551115":[{"state":"Boom","trend":0}, {"state":"War","trend":0}]
}
```
```
"recoveringStatesHistory": {}
```

**Comment by AnthorNet** [comment]
OK is it better now?

**Comment by IgaguriMK** [comment]
It seems to better. thanks for fix.
