### ISSUE TITLE
Station search uses stale data

### ISSUE THREAD

**Issue by ghost** [EDSM-NET/FrontEnd#192]
I am currently looking for stations selling CMM Composites with a good supply, which is only present in stations that are in boom state.  However, the advanced search is returning stale data.  As a case in point, the search currently returns:

![image](https://user-images.githubusercontent.com/25147462/44054213-4be6c262-9f42-11e8-937d-c88ed4f50db7.png)

If I use the link to go to the station in question, I get this:

![image](https://user-images.githubusercontent.com/25147462/44054276-74aefdcc-9f42-11e8-9652-4fab47b83fc1.png)

However, if I then use the link to check the faction state, I get this:
![image](https://user-images.githubusercontent.com/25147462/44054346-a0bb556e-9f42-11e8-86a3-01f19898db38.png)

I had several of these this evening, and as soon as I dock, the status of the port is updated, but then I have already done the SC approach and descent.

What should happen is that the status of the station should be updated whenever its owning faction is updated.  In its current form, the search results are very misleading

**Comment by AnthorNet** [comment]
If I understand clearly, once docked station state is None ? Right?

**Comment by ghost** [comment]
Correct, once I dock, the status is updated.

**Comment by AnthorNet** [comment]
It should potentially be fixed ;)
