### ISSUE TITLE
If the EDTS calc is less then 250 ly, its probably ok to put an approximate red dot on the galmap

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#199]
https://www.edsm.net/en_GB/system/id/36372/name/Bleia+Eohn+ER-M+a34-2
as an example, this is +-9ly, it would be nice to see an approx dot

**Comment by AnthorNet** [comment]
I suspect the dot is under your commander position ;)
For example check that one: https://www.edsm.net/en_GB/system/id/2753232/name/Syrivoe+BY-F+c25-5
