### ISSUE TITLE
Text error on System summary page

### ISSUE THREAD

**Issue by cmdrmarx** [EDSM-NET/FrontEnd#206]
As noted on the forums earlier, on system pages, the text "It was named by the Elite: Dangerous community with the name of:" is slightly incorrect. It should be "It was named by the Galactic Mapping Project with the name of:". I'd also recommend making it a link to the GMP, as that would make it easier for anyone who might want to contribute to find it.

Also, the "Galactic Map description" would be better as "Galactic Mapping Project entry". It might be mistaken for the in-game Galaxy Map description. (I wish we could access those as well, but FD's unlikely to provide those.)

**Comment by AnthorNet** [comment]
Done
