### ISSUE TITLE
Request: add number of bodies from journal to system

### ISSUE THREAD

**Issue by cmdrmarx** [EDSM-NET/FrontEnd#207]
The journal records the number of bodies found in a system when the ADS is fired. Specifically, DiscoveryScan's second parameter. When this info is available, could you log this and add it to system summaries as well? It would be useful even now to be able to tell if a system was fully scanned, and with the upcoming Q4 changes, it will be even more useful.

**Comment by AnthorNet** [comment]
That event is not reliable sadly...
It can trigger multiple times in a row without giving the total number of bodies.
It only shows the number shown in your cockpit.
It also captured belts in the number!

From what I've seen Q4 should give is the opportunity to know if a system is fully scanned or not.

**Comment by cmdrmarx** [comment]
Oh, I see. I was aware that it also triggers when the passive scanners find something, which could be solved by using the largest number of bodies provided for the system... but I didn't know about the belts. Guess we'll see if anything changes in the beta then.

**Comment by AnthorNet** [comment]
Done
