### ISSUE TITLE
"First discovered for EDSM by" and "First scanned for EDSM by"

### ISSUE THREAD

**Issue by cmdrmarx** [EDSM-NET/FrontEnd#208]
On the system summary pages, the first uploader's text reads "That system was first discovered for EDSM by", but on body summaries, it's "First scanned for EDSM by". Having two different phrases is somewhat inconsistent, and the first one has at times led to confusion, when the actual first discoverer (with the in-game tag) wasn't the one who submitted it to EDSM. So, to make the two more consistent and precise, I'd suggest changing both texts to "First uploaded to EDSM by" or "First recorded for EDSM by". It's also how EGO does it.

**Comment by AnthorNet** [comment]
Was looking at it, need to think on it because it's not the first uploaders at all, but the first to visit or scan, using the journal file provided.

**Comment by mwerle** [comment]
It would be pretty neat if we could also register the in-game first-discovered-by/first-mapped-by tags.  Would need to petition FDev to extend the Journal I'm guessing.

**Comment by AnthorNet** [comment]
@mwerle It was during Q4 beta but was then removed for privacy purpose by Frontier.

**Comment by mwerle** [comment]
?!? What privacy concerns? The information is right there on the "System Map" screen in-game; the only difference is whether we have to type it in manually or not.

**Comment by AnthorNet** [comment]
I remember it has something to do with console commander name.

**Comment by mwerle** [comment]
Sure, out of our hands and FDev's decision is final and all that; but the reason given is absolute bollocks.
I could "easily" write a screen-scraper to capture the information automatically.

Anyway, getting a bit OT now, sorry! :-D
