### ISSUE TITLE
Faction labeled incorrectly

### ISSUE THREAD

**Issue by ghost** [EDSM-NET/FrontEnd#209]
When doing an advanced search for minor factions, my faction, the Horizon Defense Agency, only shows up when I input "no" on the "is player faction?" question. Why?

**Comment by klightspeed** [comment]
Likely due to nobody telling anybody that it was a player faction.

What is their home system?

Edit: since they're only present in Songala, I'm guessing that's their home system?

**Comment by ghost** [comment]
Yes

**Comment by klightspeed** [comment]
OK - the faction has been marked as a player faction, and Songala has been set as their home system.

**Comment by ghost** [comment]
Cool
