### ISSUE TITLE
Star Halo Animation in System Preview bugged

### ISSUE THREAD

**Issue by WaldemarLehner** [EDSM-NET/FrontEnd#222]
The "glow" animation from the stars seems to be bugged and shows differently depending on how far you are zoomed in / out.
Tested on [LHS 3006 Page](https://www.edsm.net/en/system/bodies/id/17375/name/LHS+3006)
Here's a [video](https://youtu.be/fPe0FMuYxmI) showing the issue.

**Comment by AnthorNet** [comment]
Wil try to replicate but doesn't do it at first glance on my laptop.

**Comment by WaldemarLehner** [comment]
Interesting..

Firefox and Edge seem to be working as intended, while Chrome is not.



![image](https://user-images.githubusercontent.com/27686785/49591569-11325f00-f96f-11e8-8d97-65f230d2f68f.png)
in case it could help with anything.
