### ISSUE TITLE
EDDN Market Sync is not per account

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#224]
I was able to login to my account, but the login stayed when i logged into my other account. this would allow incorrect data to come through.

**Comment by AnthorNet** [comment]
That is odd, I just test switch between my two accounts, and one was connected and not the other/

**Comment by RapidfireCRH** [comment]
Can you give me a way to reauth then. i may have mixed the accounts. My account in colonia was pulling data from the bubble
