### ISSUE TITLE
EDMS having trouble to work on Chrome 

### ISSUE THREAD

**Issue by HavocRS** [EDSM-NET/FrontEnd#225]
I can't access some options in the site like my profile menu, anyone having the same problem?

**Comment by AnthorNet** [comment]
Have you tried to force refresh by empty your cache?

CTRL+F5 or CTRL+R ?

**Comment by HavocRS** [comment]
Yes, doesn't work

**Comment by AnthorNet** [comment]
Hit F12, any error in the console?

**Comment by HavocRS** [comment]
Yes, 9   :o

**Comment by AnthorNet** [comment]
Care to share them? Otherwise it will be hard to help you :)

**Comment by HavocRS** [comment]
![1111111111111a](https://user-images.githubusercontent.com/45856093/50023080-e8d4e100-ffbc-11e8-9b5c-1c1d92b16196.PNG)

**Comment by HavocRS** [comment]
Any thoughts?

**Comment by AnthorNet** [comment]
Looks like an extension is trying to load jquery instead of our file, any extension loaded?

**Comment by HavocRS** [comment]
It's not Ad Block neither Ad Block Plus (They are already disable), I gonna disable the others to see.

**Comment by HavocRS** [comment]
I found the trouble maker, https://chrome.google.com/webstore/detail/web-boost-wait-less-brows/ahbkhnpmoamidjgbneafjipbmdfpefad

**Comment by AnthorNet** [comment]
Glad you found it :) Not sure why it can't load jQuery ... :S

**Comment by HavocRS** [comment]
I giving you the link in case you want to know how the extension works :)

**Comment by HavocRS** [comment]
Btw thanks for the help!
