### ISSUE TITLE
unable to auth

### ISSUE THREAD

**Issue by Zimbinator** [EDSM-NET/FrontEnd#229]
Frontier auth keeps spitting a "user not found" error despite using my correct xbox info, cant use the console updater due to this

**Comment by RapidfireCRH** [comment]
We have been seeing alot of these come through. 

Anthor (EDSM/EDDN)Today at 6:16 AM
All poke support :p
I can't do anything about this one :frowning:
From hat they told me either you don't own Elite or using the wrong xBox account, which doesn't help much :smile:

**Comment by Zimbinator** [comment]
> We have been seeing alot of these come through.
> 
> Anthor (EDSM/EDDN)Today at 6:16 AM
> All poke support :p
> I can't do anything about this one 😦
> From hat they told me either you don't own Elite or using the wrong xBox account, which doesn't help much 😄

oh well, I guess, I couldnt find anything on FDev's forums.
thank you for pointing that out though

**Comment by dtmderrick** [comment]
Having the same issue, like many it seems. I contacted FDev support to which they said:  "Thanks for contacting Frontier Customer Support, sorry to hear that but I am happy to assist you today. Sorry for the delay in our response, we're extremely busy currently but working tirelessly to get back to our regular response time!

We do not support this third party application, for assistance you will need to contact their support team.

If there is anything else that we can do to help, please let us know! :)"

**Comment by RapidfireCRH** [comment]
The support is for your username not being found when using the Auth service. Is that the same issue you are having?

**Comment by RapidfireCRH** [comment]
While it is correct that Frontier does not support the 3rd party apps, the one thing they do support is the Auth service. If you are getting the user not found error when trying to use the auth service here: https://www.edsm.net/en/auth/frontier/go/state/link then i would reach out to support

**Comment by dtmderrick** [comment]
Yes, that's the issue I am having. And I did explain that to them in the ticket about the Auth service, and still responded with the above.
