### ISSUE TITLE
Badge for "Merchant" skipped

### ISSUE THREAD

**Issue by ArkanaCode** [EDSM-NET/FrontEnd#231]
The "Playing the Markets" "Merchant" rank one did not unlock since I made enough credits to skip through the rank after it.

ID: CMDR Capt. Ragnarok

Could you help me with the unlock? :)

**Comment by Capt-Ragnarok** [comment]
I can see now that EDSM still has me marked as dealer, this might be a problem with the Market Connector, will see soon I guess.

**Comment by ArkanaCode** [comment]
Nevermind, might have been a Market Connector issue.
Unless you helped in the meantime.

Ok to close this.
Thank you!
