### ISSUE TITLE
odd commander name

### ISSUE THREAD

**Issue by kn-yami** [EDSM-NET/FrontEnd#232]
When I navigate to my EDSM profile I see `PROFILE\CMDR %1$s profile` in the top part of the web-page. Is it supposed to be like this?

**Comment by AnthorNet** [comment]
Link please

**Comment by kn-yami** [comment]
Here: https://www.edsm.net/en/user/profile/id/69674/cmdr/kn-yami.

**Comment by kn-yami** [comment]
Thanks for fixing this.
