### ISSUE TITLE
Searching for pirate attack state is broken

### ISSUE THREAD

**Issue by 9Husky** [EDSM-NET/FrontEnd#238]
Searching for pirate attack state is broken. Go to Advanced search > Stations, there's a dropdown for faction state, with an option called 'ALIAS\STATE\Pirate Attack' on the bottom of the list. It doesn't seem to produce any results.

**Comment by AnthorNet** [comment]
Fixed the missing translation.
For system state as noted on the galaxy map popup, I believe it is currently broken.

Will bypass it by fixing search to look into active factions states.

**Comment by AnthorNet** [comment]
Tried to find some pirate attack in the database, but couldn't find any, any example?

**Comment by AnthorNet** [comment]
Fixed :)
