### ISSUE TITLE
Import Journal > FSSSignalDiscovered - Error 500: Message needs to be checked

### ISSUE THREAD

**Issue by Diamundo** [EDSM-NET/FrontEnd#239]
Hi all,

Whenever I upload my journals once in a while, I get a few of the errors as described in the title.
I've always thought it to be odd, as I had a few of them. Lately though I've seen more and more pop up in a journal.

The uploaded journal (see below) is from about four hours of playtime, and another additional hour of sitting in the main menu (while having dinner). It consists of 1734 log lines.

Importing this journal resulted in 223 errors, all from the title.
The first one error is from game-time 13/01/2019 14:53:28, that timestamp is present 15 times. The next one is 11 times, then 15x, then 4x, then 8x, then 13x, then 13x, then 11x, ... You get the point. It occurs between 4 and 15 times, somewhere between 3 and 10 minutes apart.

My hypothesis, based on the amounts, differences in time, and a quick peek at the log itself, that the parser is having trouble with multiple FSS Signal discoveries inside a system. It happily parses the first one, then thinks all others in the same second are doubles - where they in fact are separate FSS signals.

[Full logfile present here.](https://gist.github.com/Diamundo/fc6144c9f9f55ee71a5fcb1cd15f35a9)

**Comment by AnthorNet** [comment]
Yes, I'm still looking at them, seeing if I can do something with them.

**Comment by francescocmazza1** [comment]
Hi, I'm getting the same error

**Comment by Diamundo** [comment]
So I've been pondering about this, and I've come up with the following:

_Main Source:_ [E:D Fandom.com](https://elite-dangerous.fandom.com/wiki/Category:Signal_Sources)


 - Check if the log line has an `"IsStation"` boolean:
    - As far as I can see, it's always true if present. This means it's a persistent signal (because you can dock here)
 - Check if the log line otherwise  has a `"SignalName_Localised"`
    - If so, it's a RES, (Compromised) NAV Beacon, or Conflict zone.
      - If it's a Conflict zone, then the `"SignalName"` is `$Warzone_PointRace_` followed by either `Low`, `Med`, or `High`. These are temporary signals, although I can't find exactly how long they last (I think it ends when one side 'wins', [source](https://elite-dangerous.fandom.com/wiki/Conflict_Zone)) ...
      - If it's a RES or (Compromised) NAV Beacon, these signals are persistent.
  - It doesn't fit the above: these *could* be temporary signals, though I've also seen names with _"dock"_ or _"station"_ in them. 


Furthermore, for the temporary signals (once we figure out when a signal is temporary):

 - Check the timestamp of the log line
   - If it's longer than (_insert lifetime of Signal Sources, currently 10 minutes_) ago since its discovery, then the signal is already gone again. In this case you can just ignore or delete the signal source.
   - If it's not longer than (_same lifetime as above_) ago since its discovery, perhaps list it inside the System page, and set a timer to delete it after 10 minutes (or periodically run a cleanup-job to remove any Signal Sources who've since perished due to their lifespan).

**Comment by AnthorNet** [comment]
Yep I know pretty much that, I've reduced the number of message stored, which set the 500 error, it's nothing to worry.
Most of them are already discarded as they are not useful at all.

**Comment by AnthorNet** [comment]
See https://github.com/EDSM-NET/Journal-Events/blob/master/Event/FSSSignalDiscovered.php

**Comment by Diamundo** [comment]
Looking good, to be honest. I think you've gotten most, if not all, different types of FSS signals.

**Comment by rhadkins2002** [comment]
I'm uploading my journals for the first time, and every single line is giving that error (so far). Should I worry, or let it continue since it is taking HOURS for it all to upload and process? My assumption is it's because my logbooks are so very old. They begin on 16/04/2019 19:49:31.

**Comment by AnthorNet** [comment]
Nothing to worry about that one, you can continue.

**Comment by alexzk1** [comment]
Still getting very often in bubble logs:

ApproachSettlement | -- | 07/03/2020 06:25:21 | Error 500: Message needs to be checked
-- | -- | -- | --


System info:


Timestamp | 07/03/2020 08:30:01
-- | --
Ship | krait_mkii (#8)Athena (pallas)
System | Jinoharis
System Coordinates | 74.09375 / 7.09375 / 29.625
Station | Korzun Platform

**Comment by VAKazakov** [comment]
Nothing to worry here, EDSM ignoring this events, because they are useless
