### ISSUE TITLE
redirected to 404 when logging in from /dashboard

### ISSUE THREAD

**Issue by aaronmallen** [EDSM-NET/FrontEnd#240]
I am consistently being routed to 404 when attempting to login via Frontier... I don't believe its them either, I never even make it to the OAuth page... I click the login button and am immediately redircted to EDSM's 404 page

reproducible like this:
1. goto https://www.edsm.net/en/dashboard without being logged in
1. click login in the "Login via Frontier Auth" section

I also notice the `href` for the links differ, from the dashboard where the error is producible the link is: `/en/dashboard/frontier/go/state/in` where as from `/` it's `/en/frontier/go/state/in`

_attempting to login from the `/` path does not produce the same error_

**Comment by AnthorNet** [comment]
Fixed :)
Thanks
