### ISSUE TITLE
Grammar Error on EDSM first discovered for

### ISSUE THREAD

**Issue by Krynh** [EDSM-NET/FrontEnd#244]
EDSM currently says on each page "That system was first discovered for EDSM by <name> on <date>.

This is grammatically incorrect as we are not talking about something other than the star system, it should in fact say "This system was first discovered for EDSM " The correct language is seen in the red banner telling you the number of ships destroyed. 

E.G "4 ships were destroyed in this system in the last 24 hours."

**Comment by AnthorNet** [comment]
I'll check that, possibly need more correction as I spotted a lot of "that system"!

**Comment by AnthorNet** [comment]
While at it, also do #208

**Comment by Krynh** [comment]
I should have added to this, "That system is located at: <co-ords>" should say "This system located at: <Co-ords>". However that might have been what you were talking about.

**Comment by AnthorNet** [comment]
Yes that's it, I did a search on the whole source code for 'That system' and will move them :)
