### ISSUE TITLE
Codex - Star confirmations not showing?

### ISSUE THREAD

**Issue by mwerle** [EDSM-NET/FrontEnd#245]
My Codex page is missing my "Star" confirmations.  

In the "Inner Orion Spur" my Commander (Myshka) is listed as only having 1 Star confirmed.
In the "Inner Scutum-Centaurus Arm" I have 0 stars confirmed!

Haven't compared the other data with the in-game Codex to see if there's anything else missing.

**Comment by AnthorNet** [comment]
Do you have the journal file from when you got them?

**Comment by mwerle** [comment]
Sure; I'll upload when I get home.

But you can see in my travel history that I've certainly visited systems with dozens of different stellar types... and other Codex entries do appear to be getting flagged correctly (like I said, will need to double-check whether they have anything missing too, but they appear to be correct)

**Comment by AnthorNet** [comment]
When EDSM spot new codex entry that aren't in the code yet, they are sent to our sentry process.
I haven't received any stars, so may be a bug in the game.

Try finding your journal, upload it again to EDSM, if it doesn't fix, send me the codex line and I will try to replicate and fix :)

**Comment by AnthorNet** [comment]
It might be a game bug, Checked all my journal files since December and only got 3 confirmed stars, Y, T, and M.

**Comment by mwerle** [comment]
Ok, so it does appear to be mostly a game bug - my Journal only has a dozen or so Codex entries for Stars, none in the current region. The in-game Codex itself seems to be ok, it's the Journal that's missing the entries.

Most entries are from Dec, but I do have a couple from the last couple of weeks so it's sporadic at best.

And no entries at all from my new Commander.

**Comment by mwerle** [comment]
So I guess we can close this; not sure if you have an "official" channel for reporting Journal-related bugs, or whether I should create a report on the forum.
