### ISSUE TITLE
Duplicate moon names in system Ceos

### ISSUE THREAD

**Issue by Dem0no** [EDSM-NET/FrontEnd#247]
System: https://www.edsm.net/en/system/bodies/id/29543/name/Ceos

It looks like many of the moons in this system are duplicated, with both lowercase and uppercase denominations for each one in the database. The following are the moons with duplicate entries on the EDSM page for this system.

Ceos 1 a
Ceos 4 a
Ceos 7 a
Ceos 7 b
Ceos 7 c
Ceos 7 d
Ceos 7 e
Ceos 7 f

**Comment by RapidfireCRH** [comment]
Ok, ive cleaned it up

**Comment by Dem0no** [comment]
> 
> 
> Can you give me a screenshot of the system?

Sure! Here's one I just took. Let me know if you need one showing different info!

![screenshot 2019-02-13 17 56 38](https://user-images.githubusercontent.com/47614237/52749989-e68d0400-2fb8-11e9-9641-12644ce5df4a.png)

**Comment by Dem0no** [comment]
Thanks! Fastest response time ever!

**Comment by Dem0no** [comment]
Thanks! Fastest response time ever!
