### ISSUE TITLE
Main star scan sometimes not registering on EDSM

### ISSUE THREAD

**Issue by lauri0** [EDSM-NET/FrontEnd#249]
Just today I noticed that in some cases (seems to be the case when the system is previously discovered on EDSM) the main star scan isn't saved EDSM. 

I just visited a Wolf-Rayet C star, but that star type did not appear on my exploration dashboard. EDSM shows that I have visited the system (that Type-10 Defender in the screenshot is me), but claims I have not scanned the star itself. I even went back to the system after noticing that, made sure to honk, synchronized the logs from EDDiscovery, but still nothing.
![z1](https://user-images.githubusercontent.com/4471358/52901485-d66d6280-320c-11e9-806d-6042374ec6dc.PNG)
![z2](https://user-images.githubusercontent.com/4471358/52901487-e1c08e00-320c-11e9-8391-862fa810efe8.PNG)
![z3](https://user-images.githubusercontent.com/4471358/52901489-e5541500-320c-11e9-8a5c-deb4d281e8ec.PNG)

**Comment by AnthorNet** [comment]
Have you tried to reimport your journal file directly on EDSM?

**Comment by lauri0** [comment]
I hadn't before, but now I did. The Wolf-Rayet still has the "You have not scanned this celestial body yet." text and my EDSM Exploration Dashboard also doesn't have any WR stars listed.

**Comment by AnthorNet** [comment]
Please send your journal so I can take a look

**Comment by lauri0** [comment]
[Journal.190216131439.01.log](https://github.com/EDSM-NET/FrontEnd/files/2872225/Journal.190216131439.01.log)
Thanks!

**Comment by AnthorNet** [comment]
It should be resolved, tell me if importing again works or wait for our background task to link it again :)

**Comment by lauri0** [comment]
Seems good, now it worked. Awesome, thanks!
