### ISSUE TITLE
System API: The information parameter should act more like the primaryStar parameter

### ISSUE THREAD

**Issue by Stargator** [EDSM-NET/FrontEnd#250]
## Description of Issue
There is an issue with how the `information` parameter is returned when it is empty that is inconsistent with how a similar parameter, `primaryStar` is returned when empty.

First note how when either `information` or `primaryStar` has data, it is in the form of a JSON.

```json
{
"name":"Eranin",
"information":{
    "allegiance":"Independent",
    "government":"Communism",
    "faction":"Eranin Peoples Party",
    "factionState":"Boom",
    "population":450000,
    "security":"Medium",
    "economy":"Agriculture",
    "secondEconomy":"Refinery",
    "reserve":null
    },
"primaryStar":{
    "type":"K (Yellow-Orange) Star",
    "name":"Eranin",
    "isScoopable":true
    }
}
```

Now note when either return empty results, they appear much different. `primaryStar` correctly returns null, but `information` consists of an empty list. This is consistent and should be correct.

````json
{
"name":"Nyeajaae JY-L a75-1",
"information":[],
"primaryStar":null
}
````

Links to compare the results by:
[Get Known System (Eranin)](https://www.edsm.net/api-v1/systems?systemName=Eranin&showInformation=1&showPrimaryStar=1)

[Get Unknown System (Nyeajaae JY-L a75-1)](https://www.edsm.net/api-v1/systems?systemName=Nyeajaae%20JY-L%20a75-1&showInformation=1&showPrimaryStar=1)

## Problem it is causing
I am writing up an application using a strong typed language, Dart, to make REST calls to EDSM.

Unfortunately, this issue is causing problems with how I define my class types. `information` should be a Map<String, dynamic>` since it returns data in a JSON format. But I have to workaround this issue in order to continue developing my app.

## Proposed Solution
Thanks to feedback from @Tkael, any field that returns a JSON, like `information` and `primaryStar` should return an empty JSON, `{}`, instead of `null` or an empty list (`[]`).

**Comment by Tkael** [comment]
https://stackoverflow.com/questions/9619852/what-is-the-convention-in-json-for-empty-vs-null
http://jtechies.blogspot.com/2012/07/item-43-return-empty-arrays-or.html
https://stackoverflow.com/questions/22997327/should-i-return-null-an-empty-object-or-an-empty-array-for-json-with-no-data
https://stackoverflow.com/questions/1969993/is-it-better-to-return-null-or-empty-collection

The consensus that I'm seeing is that it is better to return an empty collection than a null value in this circumstance. Returning null can also have the consequence of breaking apps that are used to the current format.

**Comment by klightspeed** [comment]
Another case of being bitten by PHP's associative arrays being serialized as an array when empty.

**Comment by Stargator** [comment]
@Tkael Then I would suggest changing both `information` and `primaryStar` so they return an empty JSON, `{}`, instead of `null` or an empty list `[]`. Also apply that to other similar data in the other APIs.

As noted in your [first reference](https://stackoverflow.com/questions/9619852/what-is-the-convention-in-json-for-empty-vs-null) (emphasis mine).

> It is good programming practice to **return an empty array if the expected return type is an array**. This makes sure that the receiver of the json can treat the value as an array immediately and does not first has to check if it is null. **It's the same way with empty objects ({})**. Strings, Booleans and integers do not have an 'empty' form, so there it is okay to use null values.

And your [third reference](https://stackoverflow.com/questions/22997327/should-i-return-null-an-empty-object-or-an-empty-array-for-json-with-no-data) (emphasis mine):

> If your client expects an array (e.g. it will loop through the results), then use [].
> **If your client expects a map of key-value pairs (e.g. it will loop through keys or will use result[someKey]), then use {}**.
> If your client expects a single object (i.e. it expects the result to have well-known properties and will do something like result.someProperty), then null is better than returning an empty object.

**Comment by AnthorNet** [comment]
Both now return an empty object ;)

**Comment by Stargator** [comment]
@AnthorNet Thanks!
