### ISSUE TITLE
Console Updater Failing To Pull Anything w/Error Code

### ISSUE THREAD

**Issue by beamansw** [EDSM-NET/FrontEnd#256]
I have gotten the message "The Frontier Auth Service is currently not available, please try again later." each and everytime I have tried to use the updater from the page https://www.edsm.net/en/settings/import/capi

 My log-in is SMEAC
Thank you in advance, Shannon

**Comment by AnthorNet** [comment]
Hi,

I checked your account, and you didn't linked the right one.
You need to click the console icon on the frontier service.

You can unlink from the security tab under settings, then sign in again on the console updater.

**Comment by beamansw** [comment]
Thanks a million.  I had put my Frontier ID in when registering, and that was causing all the problems I guess.  I'll be on later playing and we'll be capturing the flight data going forward now I guess.  Too bad the data prior is lost...  I'll come back and close this tonight after confirming date transmitting correctly. 
 Thank you again for such a quick response!
Semper Fidelis, Shannon
