### ISSUE TITLE
PS4 Console Updater no longer picks up system correctly

### ISSUE THREAD

**Issue by keelerad** [EDSM-NET/FrontEnd#258]
There appears to have been an update that does  great job of pulling in cargo/inventory but unfortunately since about 08:24 in game time it no longer is updating the system correctly.

Currently travelling for DW2 and flight log no longer getting updated but great work on the inventory, cross checked vs game and values being imported are correct

**Comment by AnthorNet** [comment]
Hi,

Did you get enough time to make it update your last 30ndays history?
What is your commander name so I can check your account?

**Comment by keelerad** [comment]
Commander name is BuzzLiteYear63, also tried an experiment and synthed some heat sinks and basic conductors still shows 243 while in game it's now 239, so looks like it did a good initial import of materials but is no longer updating

**Comment by keelerad** [comment]
What did you mean by 

> Did you get enough time to make it update your last 30ndays history?

Is there some action I should take ?

Thanks, Alec

**Comment by AnthorNet** [comment]
Materials were here from your last play, just weren't show on the old updater ^^
From what I see in the database, your history is around the end of February.

When it will be on the current day, it should be mostly instant.

**Comment by AnthorNet** [comment]
If you check the date when it's importing Journal event,s you'll see that it's not quite yet in the present time.
On first loads, and until it get to the current day, the updater will try to update your last 30 days history in the game.

**Comment by keelerad** [comment]
Sorry don't understand how history is from end of Feb, have been playing every day since then, game is running at the moment

**Comment by keelerad** [comment]
Is there a way of speeding up the import ie logging in and out of EDSM or restarting the game or is it just a case of waiting is best? Patience is a virtue ;-)

**Comment by AnthorNet** [comment]
Patience, once history is done, it will never go beyond the last imported time :)

**Comment by keelerad** [comment]
![edsm](https://user-images.githubusercontent.com/13383443/54611270-86bdc900-4a4e-11e9-95e7-ceb1532ed8f1.PNG)

Just for the record those were my last position updates this morning

Current position being reported as Hypio Pra RE-A c29-1 the 2nd one in the list

Thanks for the response and appreciate all your good work
