### ISSUE TITLE
Console Updater is pulling nothing...

### ISSUE THREAD

**Issue by beamansw** [EDSM-NET/FrontEnd#259]
The Console Updater is clearly running, and on the screen last night it would show me in a different system after jumping there on the updater screen, but there is zero data being added to my profile.  Short for showing that I docked last night, there is zero flight data, distances, number of jumps, fuel used, game time, materials, systems visited/discovered, stars scanned/value, alliance reputation, engineers, fleet, etc...  [XBOX; User ID: SMEAC]

**Comment by beamansw** [comment]
Would wiping my account from the server possibly fix this?

**Comment by AnthorNet** [comment]
Hi, 

There was an issue that should be fixed, you also need it to fetch all your history from the last 25 days until it get to real-time.

**Comment by beamansw** [comment]
Thanks a bunch!!!  I saw the Paetreon on twitter by the way and I just posted it in The Fatherhood Wing's Discord stream.  I'm happy to support your hard work and I'm grateful to have some of the same tools that PC players do.

**Comment by AnthorNet** [comment]
I'll try to write some new FAQ tomorrow :)
