### ISSUE TITLE
Estimated Scan Value Endpoint Documented Incorrectly

### ISSUE THREAD

**Issue by magico13** [EDSM-NET/FrontEnd#261]
When looking at the documentation for the estimated scan values in api-system-v1 it lists the endpoint as `https://www.edsm.net/api-system-v1/estimated-values` but in actuality the endpoint is `https://www.edsm.net/api-system-v1/estimated-value` (note, doesn't end with an "s"). Had to figure that one out with trial and error.

**Comment by AnthorNet** [comment]
Ooops!
