### ISSUE TITLE
Just to make you aware (Console Updater)

### ISSUE THREAD

**Issue by beamansw** [EDSM-NET/FrontEnd#264]
I know you all are working hard on the console updater and also working to make it more 'durable' (I guess is a word, IDK).  After working fine in the session I played on Wednesday evening (CDT),  I went on to Thursday thinking this was great and things were going to be flawless going forward.  You all patched an update the same day I guess..?  So I really hope you take my tickets as feedback and not as nagging; I really want this to work as bad as you guys do.  And so, I hope my feedback is helpful.  
  So, like I said things worked fine on Wednesday, to include my selling data to cartographer and EDSM reflecting accurately the remaining data I couldn't sell because it was within the required radius to sell.  I was docked and then logged off ED for the night; also closed my EDSM browser as well.  So when I played last night, the EDSM was not updating my location at all, or any otherr data.  I logged out of EDSM and logged back in, I also went to setting -> security and refreshed my token... still nothing.  I left it alone thinking maybe there was a temporary disconnect with the frontier servers or something.  So today I log into my EDSM and there is still nothing.  It has my ship still sitting where I logged off on Wednesday night.  So this time, I went to settings -> security and this time I unlinked my customer ID and then relinked it in console updater.  That worked! :)  I tell you all of this so you are aware how things are working on the user end and I hope it's helpful.  My only concern (which may be unfounded because I don't know how cumulative data works in EDSM) is that, once I hit 25 days of data; if I'm still having to unlink my customer ID to get EDSM to work, do I/will I stand the chance of losing previous data?

  Again, I sincerely hope this feedback is helpful.

V/R, Shannon Beaman (SMEAC)

**Comment by keelerad** [comment]
Also suffering this issue, updating stopped with last flight log entry being 19:09:07 on 25/03/19, had been working perfectly but now on each attempt it puts up a message that dissapears to quick to read properly but seems to be about not being able to connect to frontier as busy ? Same PSN account works with updater for inara but not for EDSM. Tried refreshing token as mentioned above still no joy (Cmdr BuzzLiteYear63)
Note my main account Cmdr Keelerad is working perfectly (it has a separate EDSM and PSN account but they were linked in EDSM in the past, not sure if this might be causing an issue?)

**Comment by AnthorNet** [comment]
Just tested with your account, and Frontier just says it has no content for today (yet?)

**Comment by keelerad** [comment]
OK logged in to the Buzz account and did a jump and  updating is happening again but flight log is missing all the jumps between yesterday at 19:09:07 and today at 09:32:22 (i'm on DW2 and did about 5 hours last night 2.2 k ly) which suggest some problem with working out where it should start reading from ? Like the OP I'm extremely appreciative of the work you have put in and am providing this info to try and help you debug the issue, not that worried about what was lost from that 2.2k ly session.
![edsm2](https://user-images.githubusercontent.com/13383443/54986884-5d9bbc00-4fab-11e9-8904-ae0229b3b81b.PNG)
 suggests

**Comment by keelerad** [comment]
I did notice that in settings/security it showed a number (about 4 or 5) of other connected sessions, I use one of 3 laptops to connect and there seemed to be leftover sessions from previous connections still in existence as well as the current session, wondering if this might have caused the issue? Will try in future to ensure there is only one connected session at any time

**Comment by beamansw** [comment]
I went to settings -> security and this time I unlinked my customer ID and then refreshed the screen and relinked it in console updater. That works for me.  Updating the token does not seem to do a thing with regard to this issue.

**Comment by beamansw** [comment]
BTW: I haven't played all weekend and only got on last night to apply a paint job to an Asp Exp while the dogs were outside.  Maybe I'll play tonight, but after playing 8 straight days after getting the game, my family needed me to 'be present' and do something else ;)  I love the game and also that there are those that will build tools like this for us all to enjoy.  If I didn't care, I wouldn't have already become and monthly contributor via Patreon and I'd just be happy disconnecting and reconnecting my frontier ID.  At the end of the day, I think voting with my dollar and with my feedback is entirely the appropriate thing to do and I hope it is a genuine help -vs- a nag.

**Comment by AnthorNet** [comment]
Thanks for you support 
So what you're saying here is that unlink/relink solve the unavailable problem?

That would be some king of bug on frontier side!

**Comment by beamansw** [comment]
Yes, the problem occurs after being AFK/G for say, overnight.  When you begin back playing the following day the console updater will be running every minute, but it's not receiving data; there was NO unavailable notice or indication that that was the problem.  It was successfully handshaking because as you know it will hit that no-go and issue the unavailable notice when there's a failure to any part of the handshake.  The unlink did resolve it and I can't say that renewing token did anything that we as the user would notice.  Or at least I didn't.

**Comment by AnthorNet** [comment]
Please note that there is a bug on Frontier side preventing the download of large journals.
Hopefully it will be resolve soon and things will work better.

**Comment by beamansw** [comment]
Yep, It's not updating tonight (currently 2242 CDT).  I tried detaching and reconnecting as I described above, but didn't work this time.
