### ISSUE TITLE
Console Updater not working (Xbox)

### ISSUE THREAD

**Issue by harryofbath** [EDSM-NET/FrontEnd#265]
Just signed up and have been running updater for 30+ mins. It gets to the end of the refresh cycle and then says there are no more logs, which isn't true, it's only updated to approx. 3 days ago. Please help,
-Cmdr warfieldgb

**Comment by CoNemesis** [comment]
Not updating for me either. Been wonky for over a week.

**Comment by harryofbath** [comment]
seems to work now though, oh well

**Comment by AnthorNet** [comment]
Just finished a new release, that will try to reparse older unavailable.
