### ISSUE TITLE
Console Updater PS4. My two CMDR accounts have combined

### ISSUE THREAD

**Issue by XonE32** [EDSM-NET/FrontEnd#268]
Hi Anthor,

Allcrowsareblack (My ED boss :)) sent me to ask you to see if you could help.

Not sure if you can help. I have two CMDR accounts for the PS4. My main, XonE_32 (https://www.edsm.net/en/user/profile/id/57623/cmdr/XonE_32) is on DW2 and currently 40k ly from the bubble. My alt, Ariel_Soleil is Bubble bound and located in Dianguandri as I've just started her a cpl weeks ago. They were both linked to EDSM, but now something has gone terribly wrong, they have combined up. 

Somehow when I log into XonE_32 I get the correct holo-me for XonE_32 and name and even the correct ship XonE is flying in the fleet tab (IPX Trespasser), but that is all. Everything else is from Ariel_Soliel's account including her ship (The Valkris) materials, money, location etc etc. I deleted Ariel's account from EDSM the other day in the hopes of linking it later and hoping it might help to clear the way to get uncorrupted info for XonE_32, but the Frontier Auth service is still grabbing her data and putting it into XonE_32 when I unlink and try to re-authorize.

I believe the problem is not here, but somehow the Frontier Auth service has chosen Ariel as my preferred account. Maybe I did something? I have un-linked and reauthorized several times, but when it gets to the reauth screen I only have the xbox or PS4 logo to choose from as 'preferred account', there's no option to select WHICH account on the PS4.

I have sent in a ticket to Frontier to see if they can set XonE_32 as my preferred account as I can not see anywhere on fedv's or ED's web page under my account to do this.

Can you hlp at least elucidate what went wrong? Should I delete XonE_32's account on EDSM? and try to re-register. Sorry for the bother and long post, but there is a silver lining.. One of my squad mates suggested becoming a patron. thought it was great idea so that's done. Keep up the great work, I'd be lost in space without EDSM and the other sites that use this amazing resource.

fly Safe
CMDR XonE_32

**Comment by AnthorNet** [comment]
Good question, let me know what frontier says.
I'll try to check with them too :)

**Comment by XonE32** [comment]
Will do, 

So far they've just told me they don't have much control over the Frontier Auth Service at support.

Thanks Anthor

**Comment by XonE32** [comment]
I just logged into Playstation on my Ariel account and just did a quick jump to Smith Orbital in Ga Gigah. EDSM tracked that flight and now says XonE_32 is in Ga Gigah. Do you think I should delete XonE's account on EDSM and just re-register? If I do delete the account and re-register and then it still pulls up Ariel's should we assume it's just on Fdev sony's end?

Thanks Anthor

**Comment by XonE32** [comment]
Hi Anthor.

Frontier seems to think the problem might be on this end. I'm of two minds. I think I shall delete XonE's account and attempt to re-register on EDSM. do u think that would hlp?

**Comment by XonE32** [comment]
Heya. 

Frontier wants to close the ticket but I asked them to keep it open until I hear from you. Know you’re busy. I attempted to del XonE_32 edsm acct, but it didnt work, its still giving the correct name but with ariel’s stars. I went online to playstation and noticed I was logged in as Ariel. Thought That might have something to do with it. So I logged out and log back in as xone. Then deleted my xone account again  in order to try and re-register but I still haven’t got a confirmation email from EDSM  saying the account has been deleted. Still waiting on that. 

 I also logged into Inara As I have two accounts with them they seem to pull the correct data using their API. Which leads me to believe that it is something on edsms end but not sure. waiting to hear back from you. 

Thanx again

**Comment by AnthorNet** [comment]
Hi,
No idea, I haven't got any answer from them. You can try to delete your account, but there's nothing wrong on EDSM.
Frontier just gives us a token from the account you sign-in.

**Comment by XonE32** [comment]
Thanks Anthor,

Have tried deleting xone_32. But haven’t rec’d a confirmation that its been deleted. Last time I tried to re register it said email not available so I assume its in the process, but its been over 24 hours. So weird

**Comment by XonE32** [comment]
Dbl post


Edsm Also says CMDR Name not available. Probably just taking its time

**Comment by XonE32** [comment]
Hi Anthor,

Got the email saying xone_32 acct has gone. Was able to re register. Things are looking better. Using EDSM from phone at the moment. System I’m being reported in was on the DW2 route a while back https://www.edsm.net/en/system/id/12569699/name/Phipoea+WK-E+d12-1374 i’m 20k ly past that and the console updater is counting up.. it says refreshing in -20:0:42 and going up. The yellow progression bar has stopped showing. But on the bright side edsm is showing my correct currency and materials. Do I need to dock for edsm to catch up or something?

https://drive.google.com/file/d/19ovIT5k8_uv1Tg-L-svgLBPZ6cQfony-/view?usp=drivesdk

Hope you can see the image. Basically says the frontier auth service is not available. That mormal?

**Comment by XonE32** [comment]
Hi Anthor

SUCCESS! I guess it just took a bit to update, but now my main account is 90% accurate. Position, Rep, assets, cash all look good. thanks for your help. I can't imagine what caused this, but if I had to guess I think it had something to do with two accounts on 1 PS4 and garbled communications between that EDSM and Frontier. Seems sorted.

Last question: I said 90% as the only thing not showing up is an incomplete listing of ships under the fleet tab. It just lists my current ship. Is it because I have to actually get into another ship and have EDSM update at that point? I assume yes, but just checking.

Cheers o7
CMDR XonE_32

**Comment by klightspeed** [comment]
I don't think EDSM currently processes the ships from the `/profile` cAPI endpoint.

**Comment by AnthorNet** [comment]
Wonderful to know it works! My guess, as I can only guess, I don't have specific entries on their side, is that the Auth Service might return the last logged account on your console?

As for the ships, we only use the journal for now, it should update when you board them. I recall there is a list on game load? But not sure without checking against the code again!

**Comment by klightspeed** [comment]
The journal does not have a ship list.

**Comment by AnthorNet** [comment]
I was thinking of the "StoredShips" event, but it's when you visit a shipyard, not on load.

**Comment by XonE32** [comment]
Ok cool. So all is well. Hazaa. Thanks again and have great weekend. I think I’ll leave Ariel off EDSM for now lol

o7
