### ISSUE TITLE
Scanned Stars not recognized on Site

### ISSUE THREAD

**Issue by zeromic** [EDSM-NET/FrontEnd#270]
Hello,

the website does not recognize a star scan.

https://www.edsm.net/en/system/bodies/id/13729129/name/Asura

Even after visiting the system honking and scanning every other object via FSS the star counts as not scanned the Progress bar is not at 100% and on the body page:

https://www.edsm.net/en/system/bodies/id/13729129/name/Asura/details/idB/5649520/nameB/Asura

are the following informations:

You have not scanned this celestial body yet.
You have not mapped this celestial body yet.

How to i get the website to recognize a scanned star. Ingame i already sold the data incl. the "detailed surface scan bonus" for the star.

this is just an example, its has happend on many systems.

just found this after entering the title:
https://github.com/EDSM-NET/FrontEnd/issues/249

**Comment by klightspeed** [comment]
What program are you using to submit the data to EDSM?  Do you have your commander name and API key set up?

**Comment by zeromic** [comment]
thanks for your questions. After looking up the scan date in EDDiscovery anduploading the right journal file i got the problem fixed! Maybe EDSM was closed/crashed while I was scanning.
