### ISSUE TITLE
Duplicate Planet (wrong name)

### ISSUE THREAD

**Issue by zeromic** [EDSM-NET/FrontEnd#272]
Hi,
just found that in this system:
https://www.edsm.net/en/system/bodies/id/3399957/name/Eol+Prou+LW-L+c8-127
the Planet B 3 has a broken duplicate (no space between B and 3):

https://www.edsm.net/en/system/bodies/id/3399957/name/Eol+Prou+LW-L+c8-127/details/idB/1043/nameB/Eol+Prou+LW-L+c8-127+B3

**Comment by klightspeed** [comment]
Deleted.  Given its low ID, I think it was imported from EDDB in 2017.

**Comment by AnthorNet** [comment]
Apparently someone was faster than me and it's already been deleted!

**Comment by zeromic** [comment]
Are you guys bots or just ridiculus fast ;-) THX
