### ISSUE TITLE
Expedition not tracking locations

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#274]
Probably a bit more complex that the title suggests.

The expediction appears to get marked complete if you arrive at the final destination even if you haven't arrived at any of the preceeding waypoints. 

After reaching the final destination, if you subsequently go back to prior waypoints then your waypoints arent recorded as met. 

The expected behaviour is that no waypoint should be marked complete until the previous waypoint has been reached. 

Example is the [Miskatonic Expedition](https://www.edsm.net/en/expeditions/summary/id/49/name/Miskatonic+University+Galactic+Expedition+3304+-+3305) for LCU No Fool Like One

**Comment by AnthorNet** [comment]
Waypoint are not mandatory.
It is planned that half of it should trigger the completion.
