### ISSUE TITLE
EDSM Codex Wrong Star Reported System

### ISSUE THREAD

**Issue by zeromic** [EDSM-NET/FrontEnd#276]
The online Codex on EDSM shows for DQ Type Star:
https://www.edsm.net/en/codex/discoveries/idR/9/region/Inner+Scutum-Centaurus+Arm/details/idD/11190/nameD/White+Dwarf+Star/idC/10000/nameC/Astronomical+Bodies/idS/11000/nameS/Stars

the System:
https://www.edsm.net/en/system/bodies/id/29021990/name/Flyiedgue+QX-U+e2-3

There is no such star in the System.

**Comment by zeromic** [comment]
Maybe its a Ingame Problem/ Bug.

The Ingame Codex shows this System https://www.edsm.net/en/system/bodies/id/32761683/name/Blua+Hypue+IB-F+d11-5

Which also only have a DCV Star

**Comment by zeromic** [comment]
Confirmed Ingame Problem.
I made a ticket on the frontier tracker.

https://issues.frontierstore.net/issue-detail/1037

EDIT again: Just found this by chance while searching for something else:

https://forums.frontier.co.uk/threads/issue-with-certain-codex-discoveries.509473/
Quote:
"...issue...Codex...
    White Dwarfs classes:
        DO, DOV, DQ, DC and DCV
    Both terraformable and non-terraformable Ammonia worlds
... disabled the ability to discover these body types"

**Comment by AnthorNet** [comment]
Thank you for checking :)
