### ISSUE TITLE
Add Pending State Information to system/factions API

### ISSUE THREAD

**Issue by markjfisher** [EDSM-NET/FrontEnd#28]
An example message to EDDN shows journal entries contain pending state data.
e.g. https://ross.eddb.io/eddn/log/36033017

Can the faction information in system api be extended to contain the pending state also?

**Comment by AnthorNet** [comment]
They are already stored in the database, but I have no clue how to present them!
Do you have some screenshot where they appear in-game for me to look?

**Comment by markjfisher** [comment]
I'll find one for you.

**Comment by markjfisher** [comment]
Example data: https://ross.eddb.io/eddn/log/40505900

         "Factions": [
            {
                "Name": "HIP 5623 Empire Group",
                 "Government": "Patronage",
                 "Influence": 0.433,
                 "Allegiance": "Empire",
                 "PendingStates": [
                    {
                        "Trend": 1,
                         "State": "Boom"
                    },
                     {
                        "Trend": -1,
                         "State": "Bust"
                    },
                     {
                        "Trend": 1,
                         "State": "Lockdown"
                    }
                ],
                 "FactionState": "None"


Normally, you only see the pending state names in the missions board like this:
![image](https://user-images.githubusercontent.com/1616940/29240975-0415a9d0-7f68-11e7-8fe2-cc3ac5ceeef5.png)

But if you go into your own panel (button 4), and show additional details for a particular faction, you see the arrows indicating the trend, so for HIP 5623 Empire Group, Boom with trend 1 = up arrow, -1 is down arrow, and there is no arrow when the trend is 0.

![image](https://user-images.githubusercontent.com/1616940/29240972-eef2d44c-7f67-11e7-8d9b-08463d172980.png)

**Comment by markjfisher** [comment]
Although, I'm not sure if the trend values are that important, just the pending state values.

**Comment by AnthorNet** [comment]
Perfect all I needed, everything is already in our database, so no trouble to show them ^^

Will do the API and the front-end.

**Comment by markjfisher** [comment]
sweet. thanks @AnthorNet
