### ISSUE TITLE
PS4 Console updater issue (authentication servers unavailable).

### ISSUE THREAD

**Issue by rhyobit** [EDSM-NET/FrontEnd#280]
Not sure if this is an issue with FDEV or my account or EDSM, but my console updater has now not logged any new information since April 25th.  Currently, y last recorded system is 2.5k LY away.  I've tried logging out of EDSM, back in, refreshing my auth token, which it advises was done correctly, all to no effect.

I'd rather not unlink my account and re-create, but I'm not sure what else to do.  I assume this may be tied to the similar issues with xbox?

Any help, gratefully received and anticipated :)

**Comment by AnthorNet** [comment]
That should be an error on Frontier side, it's generally temporary :)
