### ISSUE TITLE
Failure to load entire journal

### ISSUE THREAD

**Issue by ivankautter** [EDSM-NET/FrontEnd#283]
Just signed up on the site. Account is on PS4. Journal of my time in the game only imported back to April 19, 2019, whereas I picked ED back up after the exploration system update. An odd example of the incomplete import is I have over 122,000 LY of travel but only showing 160 jumps total.

**Comment by AnthorNet** [comment]
Console updater can only go as far as 28 days of history. Frontier didn't provide more.
