### ISSUE TITLE
[PS4] Hole in logs

### ISSUE THREAD

**Issue by scannerGT** [EDSM-NET/FrontEnd#284]
Hi,
few days ago, I noticed a hole between two entries in my flight log, between Apr 24, 2019, 5:23:51 AM and Apr 28, 2019, 8:56:52 AM - the log does not show my Cobra, and in addition suggests a jump of about 95 Ly - some far as my possibilities :)
Is it possible to complete the missing data?
My platform is PS4, profile: https://www.edsm.net/en/user/profile/id/79814/cmdr/scanner_pl

**Comment by AnthorNet** [comment]
Hi,
I put your dashboard around the 20th of April, try to run it again, if it doesn't work, then Frontier is not sending it to us ;)
