### ISSUE TITLE
Incorrect Earth-like value

### ISSUE THREAD

**Issue by Qumfur** [EDSM-NET/FrontEnd#287]
The calculation of the value of earth-like seems very far of.

The majority of the values and formulas are found [here](https://forums.frontier.co.uk/threads/exploration-value-formulae.232000/)
The formula for the calculation is k + k * q * mass^0.2 and this is used correctly for every other planet type. 
The calculation for earth-likes seems to have the wrong k value.

To elaborate this a bit more: 
I'm currently at Rohini. This system has one earth-like: Rohini AB 1
The estimated value on EDSM has actually two different entries:
 [System overview:](https://www.edsm.net/en/system/bodies/id/16355685/name/Rohini) 95,854
[Planet information:](https://www.edsm.net/en/system/bodies/id/16355685/name/Rohini/details/idB/8158333/nameB/Rohini+AB+1) 319,514
I guess because I already mapped it? With another browser the 95,854 are also displayed there but whatever.

The main point is 95,854 would be correct for a k value of 64831
`64831 + 64831 * 0.56591828 * 0.4323^0.2 = 95,854.69272`

But that's the k value of a _non terraformable_ water world. 
Earth likes have the same k value as a _terraformable_ water world. Which is `64831 + 116295 = 181,126`

To back this up with actual in game data:
[Here](https://imgur.com/wdiJ6X7) is a screenshot of the exploration values for the Rohini system
It lists the earth-like with a value of 1,115,825
This is with the mapping  and efficiency bonus. Calculated like this:
`181,126 + 181,126 * 0.56591828 * 0.4323^0.2 = 267,800.5441`
`267,800.5441 * 3.3333333333 (mapping multiplier) * 1.25 (efficiency bonus) = 1,115,835.6`
That is only 10 off. With a k value currently used that would be:
`95,854.69272 * 3.3333333333 (mapping multiplier) * 1.25 (efficiency bonus) = 399,393.553`

**Comment by AnthorNet** [comment]
Not at home, but bonus should now be applied.
If not I'll check on a computer, mobile doesn't help much!

**Comment by Qumfur** [comment]
Great, now it shows the correct values. Thank you!
