### ISSUE TITLE
Can't login anymore after clearing save

### ISSUE THREAD

**Issue by florian-boubou** [EDSM-NET/FrontEnd#288]
# After clearing my save in the danger zone, i can't login anymore on EDSM
So I recently created an account using Frontier Auth system for my CMDR [REDACTED] on EDSM. After importing the journal, I noticed something went wrong because parts of my records were missing.
I went to the danger zone and asked for my EDSM save to be cleared so I could re-import my journal and maybe fix the issue.
I tried to log back in after receiving the confirmation email but when trying I get the following error: "No account found, please try to register again... (#1423063)".
And when I follow the error message's directions I get this error: "That commander name is not available".
I may not have correctly understood the "Clear My Save" feature's purpose, but now I can't login or create a new profile for my CMDR.

**Comment by AnthorNet** [comment]
I think you need to try the lost password feature, using your email.
Once logged, you should be able to link again using the Frontier Auth Service.

**Comment by florian-boubou** [comment]
Hi Anthor, thank you for the fast reply!
I've already tried to reset my password but no email was sent to my inbox (i've given my Frontier's account email address).

**Comment by AnthorNet** [comment]
Send me your email and CMDR name on contact|at|edsm.net

**Comment by florian-boubou** [comment]
Thanks, I tried to find the contact page on EDSM but couldn't find it.
