### ISSUE TITLE
Systems API doesn't handle malformed requests properly

### ISSUE THREAD

**Issue by Thurion** [EDSM-NET/FrontEnd#29]
This call returns a few hundred systems I didn't ask the API about:
`https://www.edsm.net/api-v1/systems?onlyUnknownCoordinates=1systemName[]=Eol%20Prou%20ZO-U%20b18-28systemName[]=Eol%20Prou%20NH-K%20c9-107systemName[]=Eol%20Prou%20CP-U%20b18-10systemName[]=Eol%20Prou%20XT-U%20b18-44systemName[]=Eol%20Prou%20XT-U%20b18-26`

The call is missing all `&`. A HTTP error `400` would be better than just to respond as no system name was given.

**Comment by AnthorNet** [comment]
Not sure yet how to handle it properly without touching too much ^^

**Comment by AnthorNet** [comment]
Nothing I can do I suspect!
