### ISSUE TITLE
Work best as a team badge

### ISSUE THREAD

**Issue by Tromador** [EDSM-NET/FrontEnd#293]
I was about to raise this as an issue, complaining that despite having 10+ friends, I did not have the badge.

However, I checked the EDSM friends screen to verify that it knew I had multiple friends at which point it issued the badge.

So the issue (for me) is that despite having 10+ friends, the badge was not automatically issued. Only by opening the friends page on the website was the event triggered that issued the badge.

Pretty minor in the grand scheme, but there it is.

**Comment by klightspeed** [comment]
I think a lot of the badge logic is run in the display logic rather than in the submission logic so as not to slow down journal submission.  e.g. body type badges are often only processed on visiting the body page; travel distance badges would be processed on visiting the profile page.
