### ISSUE TITLE
65,000ly club badge not awarded

### ISSUE THREAD

**Issue by ladycaruso** [EDSM-NET/FrontEnd#294]
I completed Distant Worlds 2, and submitted my travel logs manually to the site about a week ago.  I haven't received the 65,000 LY club badge.  Is there a way to get this corrected?  I received several other badges, but not this one, even though I have definitely been more than 65k ly from Sol.

Any help is appreciated, thanks!  (EDSM username is "infiniterider")

**Comment by AnthorNet** [comment]
As it's not a game statistics, this badge required that you visit your dashboard so EDSM can calculate it ;)

**Comment by ladycaruso** [comment]
Hey, thanks so much for the super-speedy response!  I saw that one, and another one come through - so excited!  I thought I had been all over the place in my profile and other spots on the site, but I see that I missed the one I needed.  Thanks a bunch!
