### ISSUE TITLE
Language inconsistent across POI link in galactic map. 

### ISSUE THREAD

**Issue by Tromador** [EDSM-NET/FrontEnd#299]
As in the picture below, I'm logged in and using British English, but the link to the POI system page is to the Spanish version of that page.

![edsm](https://user-images.githubusercontent.com/38956076/60396881-b6489b00-9b3e-11e9-97bd-7115f44b595d.png)

**Comment by AnthorNet** [comment]
Something to see with the Galactic map project to fix :)
