### ISSUE TITLE
Krait Phantom Paintjob Not displayed in My Fleet

### ISSUE THREAD

**Issue by S-Blaze** [EDSM-NET/FrontEnd#300]
When looking at my Fleet page I noticed that my paint job has a weird line of text and a giant ? is displayed where the ship is normally displayed.

![image issue](https://user-images.githubusercontent.com/52519626/60639423-a6f07880-9df0-11e9-81f0-5f79f0461b1f.jpg)

**Comment by AnthorNet** [comment]
Name updated, but don't have the image right now ;) See FAQ if you want to provide one :)

**Comment by S-Blaze** [comment]
I read the FAQ section. I took the screens and have them zipped. Unfortionately the FAQ doesn't say where to send them?
