### ISSUE TITLE
Data inconsistencies between game log and site (XBox User)

### ISSUE THREAD

**Issue by iGRiMR3AP3R** [EDSM-NET/FrontEnd#301]
Console updater has pulled my data but the data is not updated correctly on the site. I have done all 10 waypoints in the Apollo 11 Anniversary Expedition and I only have a green tcik next to waypoint 1 which is where I am located right now. I made sure I stopped each waypoint on the way back today to verify and scanned all bodies at each waypoint. Up until today only waypoint 2 showed. Later updating it showed tick for 2,3,4,5,6,7,8,9 and was missing 1 and 10. And my credits in game don't match, ingame my view is 79,212,064CR but on site 75,378,873CR. I also made €10 donation today with paypal and didn't get benefactor badge. I have tried both chrome and edge browsers on my desktop pc to update and track EDSM data. Please assist!
![EDSM Credit balance](https://user-images.githubusercontent.com/52638237/60774736-b7666300-a110-11e9-92f4-fb3e4d87e7f4.jpg)
![07-07-2019_ingame credit balance](https://user-images.githubusercontent.com/52638237/60774755-f72d4a80-a110-11e9-8da8-346e34b017b7.png)
![Apollo 11 Waypoints](https://user-images.githubusercontent.com/52638237/60774780-555a2d80-a111-11e9-84ea-d5789656fa5c.jpg)
![Paypal donation](https://user-images.githubusercontent.com/52638237/60774801-93575180-a111-11e9-9d12-e00a8d008810.jpg)

**Comment by AnthorNet** [comment]
Hi,

Sorry about the donation delay, I am currently on vacation.
Credits are only balanced when you load the game, the total is not given at any other moment.
As for the waypoint, it depends when your start point was spotted, it will only grab them after the first passed one.
But I'm not at the office to check now.

**Comment by iGRiMR3AP3R** [comment]
Thanks for the update, I did all the waypoints back from 10 to 1 but didn't register, and now I started 1 to 3 it has worked, but took time to show up. Will continue on to 10 and see how it goes.

**Comment by iGRiMR3AP3R** [comment]
Hey there, situation got better but I still am not getting recognition for waypoint 7. Over the last few days I have been in and out of this system and landed planetside overnight. Please take a look, screenshots included with flightlog from EDSM showing I been there.
![EDSM flight log](https://user-images.githubusercontent.com/52638237/61124249-5509bb80-a49e-11e9-9171-8f8c3ae7a5b5.jpg)
![Apollo 11 25th anniversary Expedition](https://user-images.githubusercontent.com/52638237/61124260-5a670600-a49e-11e9-94d7-85f92c5662c3.jpg)

![EDSM flight log 2](https://user-images.githubusercontent.com/52638237/61124493-f0029580-a49e-11e9-8fc4-ffbcf535e082.jpg)

**Comment by klightspeed** [comment]
Were the visits to waypoint 8 before or after you visited waypoint 10?  I don't think EDSM will recognise any visits to a waypoint after you have completed the expedition.

**Comment by iGRiMR3AP3R** [comment]
I have done the waypoints in sequence 3 times now, twice 1 to 10 and once 10 to 1. I made sure I went in sequence so there would be no discrepancies. All the waypoints are bookmarked in my game, and I definitely did in correct order after I had problems the first time. At one point the waypoint ticks showed 2 to 9 ticked but 1 and 10 unticked. There has definitely been an issue with this and not a problem with my in game flight path. Please review my logs if you want to see I did the waypoints in sequence.

**Comment by AnthorNet** [comment]
The system most likely took the closest start point in time against the expedition dates, then closed after passing the end waypoint. I'll check after if I can update it manually

**Comment by iGRiMR3AP3R** [comment]
Thanks, I really don't want to have to do a fourth run just for the badge. I'm ready to find new systems I haven't mapped and explored.

**Comment by AnthorNet** [comment]
After looking, your end point is one day before the arrival on the 10th, not sure I can do anything about it right now.
