### ISSUE TITLE
[Request] Expose travel-map endpoint to the public

### ISSUE THREAD

**Issue by WaldemarLehner** [EDSM-NET/FrontEnd#303]
Good day,
as of now, the endpoint used to retrieve the array describing systems that have been traveled through with name, coordinates, and a timestamp is restricted to EDSM.net only, which means that accessing it from outside EDSM will an empty Array `[]`.
The endpoint in question is the following:
`https://www.edsm.net/en/user/travel-map/id/[CMDR id]/cmdr/[CMDR name]/json`

I hereby request to expose said endpoint to be used outside of EDSM, allowing Apps to use said data to easily provide a richer data visualization experience of the CMDR's travel logs.
The issue with private profiles could be circumvented by requiring the API key to be passed as an argument.

Greetings, Waldemar Lehner.

**Comment by AnthorNet** [comment]
Check here https://www.edsm.net/en/api-logs-v1

**Comment by WaldemarLehner** [comment]
'''startDateTime and endDateTime can be use together or separately, but the maximum interval will be 1 WEEK.
If both are set, endDateTime will be used to calculate the interval.'''

Why is this limitation in place? 
The aforementioned endpoint does not have this limitation.
With the endpoint you provided I don't see an efficient way to provide the entire cmdrs travel history.

**Comment by AnthorNet** [comment]
Limitation was added to avoid abuse on the server. Software are fine to get week per week and save for further usage. Travel map isn't a public endpoint and there is no plan to open it.

**Comment by WaldemarLehner** [comment]
`Software are fine to get week per week and save for further usage`
This does not apply to web-applications unfortunately.
