### ISSUE TITLE
Missing Distant Worlds 2 Credit

### ISSUE THREAD

**Issue by Ph4d3** [EDSM-NET/FrontEnd#305]
I completed Distant Words 2 and do not see myself on the list. I'm participant #10939

Here's a link to prove it.

https://docs.google.com/spreadsheets/d/1aCtqC9Md3DAQBFvccbdki6Ck9RG4OJR-j9r2zGZobQE/edit#gid=1352413375

10939 | 2019/01/14 | Ph4d3 | Ph4d3 | Anaconda | Hydragyrum | 9MK-DW | 67.91 | Fleet Mechanic, Fuel Rat | No | No | PC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by AnthorNet** [comment]
Just ran a new import, does it work now?

**Comment by Ph4d3** [comment]
Yes, thank you!
