### ISSUE TITLE
[PS4] Missing flight log data

### ISSUE THREAD

**Issue by mojohuka** [EDSM-NET/FrontEnd#306]
I created an EDSM account recently, and after linking my PSN account and pulling my flight log data, there's a large chunk of flight activity that didn't import correctly.
https://www.edsm.net/en/user/profile/id/87598/cmdr/Mojohuka
From Jul 24 @ 12:25:12 AM to Jul 25 @ 12:01:09 AM, there's a large amount of missing flight data, around 4K Ly (I'm not 100% positive, but it's most likely around 80 - 85 missing jumps).
Also, from Jul 25 @ 12:01:09 AM to Jul 25 @ 2:08:41 AM, the flight activity is missing the associated ship data.
Do I need to delete and recreate my profile to have EDSM go grab the data again? Or is there a way to manually trigger a re-import of these logs?

**Comment by AnthorNet** [comment]
I did a rewind on your account but it didn't seems to have taken anything new.
I'll debug further but it seems nothing more is sent from Frontier server.

**Comment by filthymick420** [comment]
My edsm is way off from what my info and stuff is in game on PS4. The money is wrong the location of where I'm at is wrong. I think the ships I own are wrong.  You are not alone. I do console updater every time I get on. Never has correct info, save for my cmdr name

**Comment by AnthorNet** [comment]
Except your account hasn't taken your history yet, still on the 11th of July, do it's not related at all...
Just let run the dashboard for a while and it will catch up.

**Comment by mojohuka** [comment]
I didn't ever get the data from 24 July. I assume that it will not show up. Everything else seems to be in order, thanks.

**Comment by AnthorNet** [comment]
I did make some retries on your account sadly the Frontier server never replied with any new information!
Main problem is the console needs to send to Frontier, then frontier needs to sends them, that makes some potential of error before the information can be retrieved :S
Really sorry that I couldn't do more.

**Comment by filthymick420** [comment]
So what can I do on my end?

**Comment by AnthorNet** [comment]
As I said, just let the dashboard run for a couple of hour to fetch the last month of history before going live.

**Comment by filthymick420** [comment]
I'm on an Android cellphone. I wouldn't be playing on console if I had a PC. It's not able to just run uninterrupted for an hour.
