### ISSUE TITLE
upload new logs?

### ISSUE THREAD

**Issue by akosmaroy** [EDSM-NET/FrontEnd#307]
Hi,

I'm a bit confused on how EDSM handles log updates. Initially when I created my EDSM account, I uploaded the log files from my PC, and they were processed fine. I also connected EDSM to Frontier.

Now, as I'm doing more things in Elite, is EDSM going to sync with Frontier to get my new data, as per the Frontier integration? Or should I manually upload the new log files? (and thus remember which files I've already uploaded in the past?)

Akos

**Comment by klightspeed** [comment]
EDSM only syncs logs from the Companion API (while running the Console updater) on Console, where there are no log files to upload to EDSM.

For PC, you need to either upload any new logs, or use a third-party tool (such as EDMC, EDDI, EDLogAgent, or EDDiscovery) to send your journals to EDSM as you play.
