### ISSUE TITLE
Sphere Systems API capped at 100ly?

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#308]
It looks like Sphere-systems API is now limited to 100ly

eg. https://www.edsm.net/api-v1/sphere-systems?systemName=Merope&minRadius=100&radius=200&showCoordinates=1 does not return any results. 

The API spec says default is 100 and max = 200 

Clearly I would prefer the max to be 200ly but maybe its the documentation that needs changing to match the new maxima.  :)

**Comment by Tkael** [comment]
Hmm... the query you submitted indeed returns empty. 
The modified query https://www.edsm.net/api-v1/sphere-systems?systemName=Merope&minRadius=99&radius=200&showCoordinates=1 does return results. 
The modified query https://www.edsm.net/api-v1/sphere-systems?systemName=Merope&minRadius=101&radius=200&showCoordinates=1 returns empty.

As soon as the minimum radius is set to 100 or greater, results are empty. 
This feels more like a bug with `minRadius` than an intended change.

**Comment by AnthorNet** [comment]
Checked from the code, seems that radius is topped to 100 and default was set to 50.
Right now, it cannot be raised, but when I switch the systems to Elastic, it shouldn't be a problem, results on the bodies search worked better than expected :D
