### ISSUE TITLE
EDSM Embeds showing wrong system

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#309]
I have  an odd issue with the EDSM Embed tool. It appears to be responding with the wrong system.
https://tool.canonn.tech/linkdecoder/?origin=Pleiades+Sector+dq-y+c4&data=HLH+HHH+LHL+%7C+LLL+LLH+LHH%0D%0AHHL+HHL+HHL+%7C+HLL+HHL+HHH%0D%0AHLH+HHL+LLL+HLL+%7C+HHL+LLL+LHL+HHH
It should be 12 Trianguli.
But showing Nang Ta-khian
The API its calling does not return Nang Ta-khian in its results
https://us-central1-canonn-api-236217.cloudfunctions.net/linkDecode-1?origin=Pleiades+Sector+dq-y+c4&message=HLH+HHH+LHL+%7C+LLL+LLH+LHH%0D%0AHHL+HHL+HHL+%7C+HLL+HHL+HHH%0D%0AHLH+HHL+LLL+HLL+%7C+HHL+LLL+LHL+HHH

It looks like it's interpreting a name starting with a number as the system id with that number - i.e. for 12 Trianguli, it's looking up system ID 12 (Nang Ta-khian).

Probably need to check if the entire string is numeric.

**Comment by AnthorNet** [comment]
Should be fixed :)
