### ISSUE TITLE
Earned Badges Not Awarded

### ISSUE THREAD

**Issue by PeteCarter1979** [EDSM-NET/FrontEnd#312]
Hi, I've noticed that various badges don't seem to ever get awarded. I know that some of these are because I met the requirement before registering with EDSM, such as Center of the Galaxy, 65000 club, Hutton Orbital, etc.

Others SHOULD have been awarded, within the limits of the tool, however. For example, I should have badges for Elite Trader, Benefactor and Ship Hoarder, none of which have been awarded.

Commander name: Peteanddan

**Comment by AnthorNet** [comment]
Hey, 
Thanks for your support, some badges are awarded by visiting your profile and or your dashboard ;) The benefactor one is done manually so it can take time, specially on an August Sunday!
