### ISSUE TITLE
Advanced Search sort by name returning duplicate results

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#314]
The following returns 100 entries all identical

https://www.edsm.net/en/search/systems/index/cmdrPosition/Sagittarius+A%2A/codexEntry/21152/onlyPopulated/0/radius/60000/sortBy/name

Changing to distanceSol returns a single record as expected

https://www.edsm.net/en/search/systems/index/cmdrPosition/Sagittarius+A%2A/codexEntry/21152/onlyPopulated/0/radius/60000/sortBy/distanceSol

**Comment by AnthorNet** [comment]
Should be fixed :)
