### ISSUE TITLE
Doublequote character in a ship name breaks the dashboard and needs to be espaced

### ISSUE THREAD

**Issue by WaldemarLehner** [EDSM-NET/FrontEnd#315]
having a `"` character inside the ship name causes the dashboard to break.
![screenshot](https://i.imgur.com/ebV6502.png)

**Comment by klightspeed** [comment]
Need to use `addslashes(shipname)` when writing the ship name to the javascript body from PHP, and `htmlentities(shipname)` when writing the ship name in the HTML from PHP.

**Comment by recrudesce** [comment]
OK, there's a more worrying issue here.
You can affect the format of the website via the ship name.

Setting ship name in the game:
![image](https://user-images.githubusercontent.com/6450799/63859761-cd213780-c99f-11e9-9909-230ac63f6a3c.png)

Fleet page:
![image](https://user-images.githubusercontent.com/6450799/63859787-ddd1ad80-c99f-11e9-879f-6e3225b15546.png)

![image](https://user-images.githubusercontent.com/6450799/63859810-e924d900-c99f-11e9-94c4-89af9246adbd.png)

**Comment by WaldemarLehner** [comment]
oh no. What happens if you name it `</body>`? or a make it a script?
If that is possible.. that has to be fixed

**Comment by recrudesce** [comment]
You don't have enough space to inject JS, but it basically accepts any HTML input.

Need to look into sanitising inputs ASAP @AnthorNet

**Comment by klightspeed** [comment]
Looking closer, it needs to be `addslashes(htmlspecialchars(shipname))` when writing the ship name in the javascript from PHP.

**Comment by WaldemarLehner** [comment]
hmm. `<script src="xx.xx/x.js"></script>` would be the shortest I could think of. That's 34 chars, which exceeds the limit. Still one could open the script tag, which would mean that everything that comes after it would be interpreted as JS, wouldn't it?

**Comment by recrudesce** [comment]
So I spoke to Anthor on Discord, his power is out but he's going to get on it ASAP.  I suggest, for the sake of common sense, that we do NOT attempt anything further.  The vulnerability is proven, no need to prove it more.

**Comment by WaldemarLehner** [comment]
\* exits the game after wanting to change the ship's name to <script> \*

**Comment by recrudesce** [comment]
Tried it, even trying to put the closing tag in the Ship ID field (it's too short).  I guess you could concoct some crazy XSS using a combination of ships with different payload names, but that's theoretical and I advise people not to try it.

**Comment by AnthorNet** [comment]
Thanks! Should be fixed ;)

**Comment by WaldemarLehner** [comment]
@recrudesce 
can you confirm that your ship's name is no longer interpreted as html?

**Comment by recrudesce** [comment]
Confirmed fixed.

![image](https://user-images.githubusercontent.com/6450799/63889313-aa5f4500-c9d8-11e9-82e7-5d4658586bd3.png)
