### ISSUE TITLE
Badge not unlocked

### ISSUE THREAD

**Issue by josseip** [EDSM-NET/FrontEnd#316]
Recently made my way to Oevasy SG-Y d0. The journal got updated and also my profile shows that in my flight log, yet the 65000ly club badge isn't unlocked. Public profile link: https://www.edsm.net/en/user/profile/id/82621/cmdr/Jossei

**Comment by AnthorNet** [comment]
Hi,

Try to visit your dashboard please :)

**Comment by josseip** [comment]
Now it's unlocked. Thanks!
