### ISSUE TITLE
Console updater hasn't worked in months

### ISSUE THREAD

**Issue by dredknot** [EDSM-NET/FrontEnd#317]
My console updater hasn't worked in months. PS4 player. Stuck with old info and never updates no matter how long I let it run. Is this tool still being maintained??

**Comment by AnthorNet** [comment]
What is your commander name so I can take a look?

**Comment by dredknot** [comment]
dredknot420

Thanks!

**Comment by AnthorNet** [comment]
Sync is at 19/08, let it run for it to catch up. Each loop goes for 1 day. I know the error message isn't ideal but they don't provide proper return.

**Comment by dredknot** [comment]
I didn't even see the 'error' messages until you mentioned that. I see it catching up slowly now.

Thanks again!
