### ISSUE TITLE
Can't reset paint job to default via the API

### ISSUE THREAD

**Issue by Marginal** [EDSM-NET/FrontEnd#32]
The default paintjob on a ship is unnamed in the Journal and Companion API. But a call to `update-ship` like
```url
https://www.edsm.net/api-commander-v1/update-ship?...&shipId=30&paintJob=
```
doesn't reset the paintjob to default. Instead, the previous paintjob is retained.

**Comment by AnthorNet** [comment]
I was thinking the default were having that form:
`adder_default_defaultpaintjob`

**Comment by AnthorNet** [comment]
Can you test if it works now?

**Comment by Marginal** [comment]
I've synthesised the names `paintjob_*_default_defaultpaintjob` in Marginal/EDMarketConnector@68f0d10
