### ISSUE TITLE
Commander Ranks API Endpoint returns wrong Response Number

### ISSUE THREAD

**Issue by WaldemarLehner** [EDSM-NET/FrontEnd#322]
When trying to access a private profile with no API key, the expected behaviour would be a `msgnum:207` , however a `100 (OK)` is returned.

See for yourself; this is account has been set to private:
https://www.edsm.net/api-commander-v1/get-ranks?commanderName=WDX

Given response is:
```json
{

    "msgnum": 100,
    "msg": "OK"

}
```

**Comment by WaldemarLehner** [comment]
It's the same with https://www.edsm.net/api-logs-v1/get-position?commanderName=WDX

The returned json is 
```json
{

    "msgnum": 100,
    "msg": "OK",
    "system": null,
    "firstDiscover": null,
    "date": null

}
```

**Comment by AnthorNet** [comment]
As much as I would like to change that, it's sadly to late as it would result in breaking change for software using them...

**Comment by WaldemarLehner** [comment]
I see. Please update the relevant API documentation.
