### ISSUE TITLE
[Feature Request] Sort nightly dump from newest to oldest

### ISSUE THREAD

**Issue by IgaguriMK** [EDSM-NET/FrontEnd#323]
Currently, nightly dumps are sorted by entry `id`.

`systemWithCoordinates.json` (≈ 6 GB) and `bodies.json` (≈ 100 GB) is huge file.
So I want to use diff-based update.
We can use `~~7days.json` to this purpose, but that can be used only when last update was within 1 week.

If these dumps were sorted from newest to oldest, We could read newest entries easily and wouldn't need download whole of huge dump files.

**Comment by AnthorNet** [comment]
Not gonna happened, it was the case earlier, but the index sorting performance were not worth it at all.
