### ISSUE TITLE
Delphi Bodies Lookup has old pgname copies of bodies

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#324]
The bodies are duplicated 

So it shows as having two Ammonia Worlds 

The second one is "Delphi Pleiades Sector IR-W d1-55 6"

It looks like the body database is a bit confused. Could this be a rogue client

https://www.edsm.net/api-system-v1/bodies?systemName=Delphi

**Comment by AnthorNet** [comment]
Thx

**Comment by NoFoolLikeOne** [comment]
Thank you !
