### ISSUE TITLE
No Picture for Krait MK2 with Salvage Red displayed

### ISSUE THREAD

**Issue by Melbar-Kaasom** [EDSM-NET/FrontEnd#325]
Hello, 
i have 2 ships Krait MK2 with the paintjob salvage red witch are not displayed in EDSM 
Sorry for my bad english

![image](https://user-images.githubusercontent.com/51875067/67185851-0ba70180-f3e7-11e9-9a81-da8a25357fc9.png)

o7 Melbar

**Comment by recrudesce** [comment]
Get one submitted !

> **Why is my ship image having a question mark?**
> We are still trying to grab screenshot of every variation of ships in the game.
> You can help us by sending a scrrenshot of your ship in the livery section of the outfitting screen, and send it to us.

> Screenshot must have a resolution of 1920*1080px and be taken with a default ship.
> Graphics settings must be on Ultra, with maximum FOV.

> To remove the UI, hold: CTRL + ALT + G

**Comment by Melbar-Kaasom** [comment]
Thanks for the Info,
As sonn as i arrived the station were the ship is standing in take a picture an d send it 
but i think my grafik card doesent support "ultra" 
if it´s not fitting feel free to delete.
