### ISSUE TITLE
Flightlog Update 404

### ISSUE THREAD

**Issue by Clinthulhu2000** [EDSM-NET/FrontEnd#327]
I'm trying to update my information (Flight Logs etc.) and every time I use the Console Updater I get a 404 error. I have tried logging out and back in. I've tried to log out with my user name and password as well as my Frontier account linked info. Is there something I'm missing. It updated on Oct. 14th and I haven't been able to get it to update since. I'm on the Lost Souls II expedition and I would like to be able to track this on your site but it's not letting me. I'm playing on a PS4 if that makes a difference.

**Comment by AnthorNet** [comment]
Hi,

Where exactly do you get a 404 error?

**Comment by Clinthulhu2000** [comment]
Hello... I get the 404 error when I am on the dashboard page and I attempt
to import my flight log... It takes me to the 404 error page. I have since
figured out that I needed to delete my browser data and cookies and then
log into the site again and re-link to Frontier/PS4 account. It is now
updating as it should be so I believe the issue is fixed.

As a side note you guys might want to put a "contact" or "help" link on the
site somewhere more obviously available. It took me two days to figure out
where to submit this ticket for help because it's kinda hidden at the
bottom of the page and under github. Me and three of my Squadron searched
your site for at least and hour to finally figure out where to submit this
for help.
