### ISSUE TITLE
System not showing commander name, only email.

### ISSUE THREAD

**Issue by Noodles4Pasta** [EDSM-NET/FrontEnd#332]
So I tried to join an expedition with my commander Noodles4Pasta and saw that it is displaying my email instead of my commander name on the roster. It also does not show my cmdr name in my profile page, instead it shows my email. Unfortunately I dont have any other ifo and i have to submit a typical "Dis is brok, plez fix..." issue... sorry bout that.

**Comment by AnthorNet** [comment]
You most likely didn't enter the correct information while registering! Did you try to update your settings?

**Comment by Noodles4Pasta** [comment]
Sorry, was out with health issues... went in and looked and there are no settings i can change to link with the Fdev acct.
Plus, I set this up at the same time as another acct that works fine.

**Comment by Noodles4Pasta** [comment]
Uppon looking further at this issue it seems that EDSM has stopped receiving my travel info from EDMC as it is trying to send it under my CMDR name, and the website is showing my CMDR name as my email address instead of the actual CMDR name. For some reason it is receiving my info on what ships i own and how much money I have.
