### ISSUE TITLE
EDSM Codex show another systems for Guardian objects than in-game codex

### ISSUE THREAD

**Issue by AndNovAtor** [EDSM-NET/FrontEnd#334]
For example, https://www.edsm.net/codex/discoveries/idR/18/region/Inner+Orion+Spur/details/idD/32061/nameD/Guardian+Beacon/idC/30000/nameC/Xenological/idS/32000/nameS/Guardian+objects shows that Guardian Beacon is in Synuefe IL-N c23-15, when in-game Codex shows that it is in HIP 36823. And I visited HIP 36823 and "confirmed" it.
Is it a bug? Or is it maybe some "outdated" information? - and if so, can it be "updated"?

![guardian_beacon_codex_ingame](https://user-images.githubusercontent.com/3628514/71691916-9f1e8a80-2db9-11ea-9c02-0fd39bf59822.jpg)
![guardian_beacon_codex_edsm](https://user-images.githubusercontent.com/3628514/71691915-9e85f400-2db9-11ea-80d2-33278df58f60.jpg)

**Comment by VAKazakov** [comment]
Codex in game and codex in edsm show first appeared data. But, it can be unequal because man, who explored object for game doesn't have software for reporting it to edsm. Nothing to fix here IMHO

**Comment by AnthorNet** [comment]
@VAKazakov is correct, I could not have answered better :)

**Comment by AndNovAtor** [comment]
@AnthorNet, I understand. But my question again - so, are there no way to manualy/half-manualy "update" this data?
(I know that it will stops be "first confirmed", but it's my question [not issue, yes])

**Comment by AndNovAtor** [comment]
@VAKazakov, in-game Codex show "real" data, that FDevs set MANUALLY. And maybe can change this sometimes (on some update or on the game server). I think.
