### ISSUE TITLE
[bug?] Expedition completion - not recording visited systems

### ISSUE THREAD

**Issue by kolin1979** [EDSM-NET/FrontEnd#336]
(Currently on the Lost Souls 2 expedition.)
Whilst at Colonia, I visited Kojerea (which co-incidentally is the last system on the expedition).
Now the EDSM tracker is telling me that i've completed the expedition and doesn't seem to be recording any of the other waypoint systems i visit.
Not sure this is a bug, or by intention that it doesn't record WPs after visiting the final system.

**Comment by AnthorNet** [comment]
Hello,

It is intended for performance purpose, as it's said it should be the final waypoint.
