### ISSUE TITLE
Distance API Vagueness

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#35]
https://www.edsm.net/en/api-v1
EDSM - Elite: Dangerous Star Map
The Galactic Positioning System of Elite: Dangerous at your service.

The system name which will be the center of the sphere.
doesnt give much clue as to what it is used for i guess
Just something quick that says "I get all the distances that have been submitted for a star"

You mentioned decommissioning or hiding this API.

**Comment by NoFoolLikeOne** [comment]
This is one I am using for an EDMC plugin that I am writing.  It seems pretty obvious to me. 

You tell it the name of a system and it tells you the names of all the systems with in min/max range

Sorry I see now you meant https://www.edsm.net/api-v1/distances it is a little vague

Seems a little redundant as the  HTTP Request: GET https://www.edsm.net/api-v1/sphere-systems will as much and more.

**Comment by klightspeed** [comment]
The API endpoint in question is https://www.edsm.net/en/api-v1/distances

@AnthorNet stopped generating the distances dump as nobody was using it and it was quite large.

It looks like the description for `systemName` was copied from `api-v1/sphere-systems`

The `api-v1/distances` API gets all of the distances that have been submitted for the system named in the `systemName` parameter.

**Comment by NoFoolLikeOne** [comment]
I see. I don;t think that would be useful to me .

My plugin is looking for systems in a sphere to find the nearest neutron star. I'm working on an algorithm than reduces the scope of the call to `api-v1/sphere-systems` and in some cases I don't need to call api-`v1/sphere-systems` at all.  

What I need to be able to do is calculate the distance between my current position and the last Neutron star that was in range. Are the coordinates measured in light years from the origin?

If i use pythagoras with the coordinates of start and end system is that going to give me the distance?

Actually I dont know why I even asked that question. I can test it out myself :)

**Comment by klightspeed** [comment]
@NoFoolLikeOne coordinates are measured from Sol, with +X being anti-spin-ward, +Y being toward the galactic north pole, and +Z being toward the galactic core.

**Comment by NoFoolLikeOne** [comment]
Thanks.

I was able to do the calculation and obtain the distance of Jackson's lighthouse from Sol using pythagoras so that works.

Of course my algorithm will be no use if I dont know the coordinates of the current system when it is unknown to EDSM.

**Comment by klightspeed** [comment]
@NoFoolLikeOne If you are watching events from the journal, then the coordinates are in the `StarPos` field in the `FSDJump` event.

In any case, this is off-topic for this issue, which is about the documentation for the `api-v1/distances` API.

**Comment by NoFoolLikeOne** [comment]
Of course. Thanks :)
