### ISSUE TITLE
Missing data from PS4 account.

### ISSUE THREAD

**Issue by Marcv74** [EDSM-NET/FrontEnd#357]
Hi, 
I’ve several missing bits of data from my profile. None of the rankings are showing up, as well as a gap in exploration data showing as an 890 light year jump between April and May, roughly 40 to 50 systems missing. Commander name is Marcv74. Thanks in advance.

**Comment by Marcv74** [comment]
Hi, 
Most of the data has now synced properly. The only missing bits are now fleet details and the 890 ly jump.

Thanks in advance.

**Comment by AnthorNet** [comment]
Sadly not much we can do about what Frontiers servers are giving back!
