### ISSUE TITLE
Jump In on FC

### ISSUE THREAD

**Issue by alexzk1** [EDSM-NET/FrontEnd#361]
Just jumped into system Plaa Thua KD-B b55-0 using FC.
On EDSM it was shown 2 stars only and saying 2 of 21 scanned for me. 
Then I lift up, scanned system and fly ahead by normal ship, then never returned to this sys.
Now, once log uploaded EDSM correctly shows all bodies I just scanned, however, my ship is NOT mentioned at the bottom like it just passed system. I think because you didn't have regular "jump in" event in log, instead that it was carrier.

**Comment by alexzk1** [comment]
New today. Jumping on carrier. Launch there, jump out to closest star, jump back to carrier. Both doiing FSS, and 1 of them missing all info (there are NO bodies on tab too):
![image](https://user-images.githubusercontent.com/4589845/85699857-85b12800-b6e4-11ea-9aac-4fa71cf120bd.png)

**Comment by alexzk1** [comment]
[Journal.200625112620.01.log](https://github.com/EDSM-NET/FrontEnd/files/4830521/Journal.200625112620.01.log)

**Comment by AnthorNet** [comment]
Should have been fixed
