### ISSUE TITLE
Account book graph not updating

### ISSUE THREAD

**Issue by TomW1605** [EDSM-NET/FrontEnd#362]
Hi
the graph on my account book page is not updating to reflect my recent sale of my DW2 exploration data. as shown in this photo there is a 1 day gap between the last data point on the graph and the last transaction and this photo was taken today, almost a week after the last transaction.
![2020-06-18 10 22 32](https://user-images.githubusercontent.com/17092573/84980710-5854ff00-b165-11ea-845b-80c6f9418600.png)

**Comment by TomW1605** [comment]
i also just noticed that the balance on my dashboard has not updated since eather.

**Comment by AnthorNet** [comment]
It updates on game load only

**Comment by TomW1605** [comment]
i'm not sure what you mean by game load. if you mean it only updates when i launch ED then it is still broken as i have played several times since it last updated.

**Comment by AnthorNet** [comment]
What is your cmdr name?

**Comment by TomW1605** [comment]
Admiral80

**Comment by TomW1605** [comment]
hi you reopened this but have not commented since. is there an update on this issue?

**Comment by AnthorNet** [comment]
There was a problem with timezone on the graph. should be fixed now.

**Comment by TomW1605** [comment]
unfortunately this is still an issue

**Comment by AnthorNet** [comment]
Looking at your account, the graph is coherent with the last Frontier regulation.

**Comment by TomW1605** [comment]
so does it not update until there is a Frontier Regulation? how often does it happen? it has been almost a month since last one. is there a reason it does not simply go off the latest transaction?

**Comment by AnthorNet** [comment]
Like I said regulation happens when loading the game, it's the only event where the game gives to total balance, hence it's the only one used for the graph and to calculate all the rest.
What software are you using, because you don't have any load event since June 10th?

**Comment by TomW1605** [comment]
EDDiscovery last logon was 19/6 when i refueled.

**Comment by TomW1605** [comment]
ok i logged in again and it worked this time so i'm not sure why it did not work last time.
