### ISSUE TITLE
Galaxy map solid black

### ISSUE THREAD

**Issue by Ranzer1255** [EDSM-NET/FrontEnd#363]
i seem to be having a issue  similar but probably unrelated to #182

the map screen is solid black and when i look in the console log its flooded with 404 errors under the URL `https://www.edsm.net/img/map/.../.../...`

This is happening in both Firefox and Chrome

![image](https://user-images.githubusercontent.com/5742529/85369744-48d20f00-b4f3-11ea-8a29-7f83d2adad2a.png)

**Comment by AnthorNet** [comment]
Fixing right now :)
