### ISSUE TITLE
credit graph errors

### ISSUE THREAD

**Issue by firebladed** [EDSM-NET/FrontEnd#364]
Im currently getting weird data on my credits graph including impossible dates e.g jan 1 1970 and backwards curves
![edsmcredits](https://user-images.githubusercontent.com/34522909/86501124-f368ee00-bd8d-11ea-9608-1c3a3801d08a.png)

i think its doing something weird with dates as last entry is listing as 4th March 2020 when is 4th July 2020 I can tell by exact number of credits

it appears to at least partially related to "Frontier Regulation" events as deleting them manually, temporeraly removes some of the "1970" points  

e.g
![edsmcredits2](https://user-images.githubusercontent.com/34522909/86501343-054b9080-bd90-11ea-8844-028a1c542cb2.png)

**Comment by AnthorNet** [comment]
Whoopsie! That should be fixed now ;)
