### ISSUE TITLE
Not updating anything from PS4

### ISSUE THREAD

**Issue by bob12341234** [EDSM-NET/FrontEnd#365]
The "console update"page is constantly doing the update timer and then resets and still says that the last update was last month the 19th of June ( I didn't own the game yet then).

So nothing from my account updates.

**Comment by AnthorNet** [comment]
What's your commander name?

**Comment by bob12341234** [comment]
Cmdr Mynameisindeed

**Comment by AnthorNet** [comment]
It actually is on 27th june now, but as it don't know when you bought the game it's testing every day, give it a little more time :)

**Comment by bob12341234** [comment]
Okay thanks, I'll wait a bit longer!
