### ISSUE TITLE
Unable to login using PS4 verification

### ISSUE THREAD

**Issue by calumcraig** [EDSM-NET/FrontEnd#368]
**Steps to reproduce:**
1. Login to PlayStation account.
2. Login to Frontier account.
3. Attempt to login to EDSM via Frontier Auth Service
4, Redirected to Frontier Auth Service, click PS4 icon.

**Expected:**
Able to login to EDSM using PS4 credentials.
**Actual:**
Error - unable to login and returned account not found message. Account definitely exists - have previously synced PS4 data with EDSM with no issues.
![Screenshot 2020-07-17 at 21 45 28](https://user-images.githubusercontent.com/44327924/87830003-0c869a00-c878-11ea-985c-8892e8716516.png)

**Comment by calumcraig** [comment]
Is this issue lies with Frontier authentication please let me know and I will raise it with them.

**Comment by AnthorNet** [comment]
Try using our lost password function to log in with a password, then once logged unsync from frontier, after that go back to the dashboard and it should ask again to log in.

**Comment by calumcraig** [comment]
OK, that worked, thanks. I'll close this issue but it still seems slightly clunky UX...
