### ISSUE TITLE
65000Ly Club badge not awarded

### ISSUE THREAD

**Issue by davidalex791** [EDSM-NET/FrontEnd#370]
Hello,
So I've been to Beagle Point (65279.35Ly from Sol) yet this badge was not awarded, any idea why?
Best regards,
David.

**Comment by RapidfireCRH** [comment]
Whats your commander name?

**Comment by davidalex791** [comment]
Commander name is davinator791.

**Comment by RapidfireCRH** [comment]
Thats not coming up either. Usually badges come through in 24-48 hours. Did you make sure your flight logs were uploaded?

**Comment by davidalex791** [comment]
I've completed that journey last month then I've run EDMC so I thought if EDSM travel map shows I've been there then the logs were correctly uploaded. 

Sent from Yahoo Mail on Android 
 
  On Fri, 24 Jul 2020 at 8:07, RapidfireCRH<notifications@github.com> wrote:   


Thats not coming up either. Usually badges come through in 24-48 hours. Did you make sure your flight logs were uploaded?

**Comment by AnthorNet** [comment]
Done, just needed to get the dashboard refresh once in order to do the calculation.
The fact is that the game doesn't provide that statistics! Only the distance from the start.

**Comment by davidalex791** [comment]
Thank you very much.
