### ISSUE TITLE
Import journal can run into an error at FSSDiscoveryScan and FSSAllBodiesFound

### ISSUE THREAD

**Issue by Thurion** [EDSM-NET/FrontEnd#371]
I'm importing a journal file with lots of scan and in some cases the import stops at `FSSDiscoveryScan` or `FSSAllBodiesFound`.
The javascript console shows this:
```Uncaught TypeError: data is null
    startSendingData https://www.edsm.net/en_GB/settings/import/journal:823
    jQuery 4
        u
        fireWith
        k
        n
```

A snippet around a `FSSDiscoveryScan` event where it stopped:
```
{ "timestamp":"2020-07-22T15:08:52Z", "event":"FSDJump", "StarSystem":"Plio Aim ZH-Y b3-1", "SystemAddress":2759384118305, "StarPos":[-8225.03125,554.87500,9262.21875], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemSecondEconomy":"$economy_None;", "SystemSecondEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$GAlAXY_MAP_INFO_state_anarchy;", "SystemSecurity_Localised":"Anarchy", "Population":0, "Body":"Plio Aim ZH-Y b3-1 A", "BodyID":2, "BodyType":"Star", "JumpDist":53.262, "FuelUsed":3.438916, "FuelLevel":54.302059 }
{ "timestamp":"2020-07-22T15:08:52Z", "event":"Music", "MusicTrack":"DestinationFromHyperspace" }
{ "timestamp":"2020-07-22T15:08:57Z", "event":"Music", "MusicTrack":"Supercruise" }
{ "timestamp":"2020-07-22T15:08:58Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Plio Aim ZH-Y b3-1 A", "BodyID":2, "Parents":[ {"Null":1}, {"Null":0} ], "StarSystem":"Plio Aim ZH-Y b3-1", "SystemAddress":2759384118305, "DistanceFromArrivalLS":0.000000, "StarType":"M", "Subclass":8, "StellarMass":0.222656, "Radius":273186624.000000, "AbsoluteMagnitude":10.918182, "Age_MY":406, "SurfaceTemperature":2270.000000, "Luminosity":"Va", "SemiMajorAxis":31983268260.955811, "Eccentricity":0.178490, "OrbitalInclination":-9.819879, "Periapsis":344.518471, "OrbitalPeriod":21488800.644875, "RotationPeriod":127465.228487, "AxialTilt":0.000000, "WasDiscovered":false, "WasMapped":false }
{ "timestamp":"2020-07-22T15:08:58Z", "event":"FSSDiscoveryScan", "Progress":0.342050, "BodyCount":17, "NonBodyCount":11, "SystemName":"Plio Aim ZH-Y b3-1", "SystemAddress":2759384118305 }
{ "timestamp":"2020-07-22T15:08:59Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Plio Aim ZH-Y b3-1 B", "BodyID":3, "Parents":[ {"Null":1}, {"Null":0} ], "StarSystem":"Plio Aim ZH-Y b3-1", "SystemAddress":2759384118305, "DistanceFromArrivalLS":311.598875, "StarType":"L", "Subclass":4, "StellarMass":0.140625, "Radius":218404992.000000, "AbsoluteMagnitude":12.614670, "Age_MY":406, "SurfaceTemperature":1718.000000, "Luminosity":"V", "SemiMajorAxis":50640177726.745605, "Eccentricity":0.178490, "OrbitalInclination":-9.819879, "Periapsis":164.518476, "OrbitalPeriod":21488800.644875, "RotationPeriod":158885.972558, "AxialTilt":0.000000, "Rings":[ { "Name":"Plio Aim ZH-Y b3-1 B A Belt", "RingClass":"eRingClass_Rocky", "MassMT":6.3458e+12, "InnerRad":4.1715e+08, "OuterRad":1.2548e+09 } ], "WasDiscovered":false, "WasMapped":false }
{ "timestamp":"2020-07-22T15:08:59Z", "event":"Scan", "ScanType":"AutoScan", "BodyName":"Plio Aim ZH-Y b3-1 C", "BodyID":4, "Parents":[ {"Null":0} ], "StarSystem":"Plio Aim ZH-Y b3-1", "SystemAddress":2759384118305, "DistanceFromArrivalLS":37650.390202, "StarType":"L", "Subclass":7, "StellarMass":0.113281, "Radius":163793120.000000, "AbsoluteMagnitude":13.961441, "Age_MY":406, "SurfaceTemperature":1455.000000, "Luminosity":"V", "SemiMajorAxis":8119539618492.126953, "Eccentricity":0.057723, "OrbitalInclination":20.577103, "Periapsis":276.378072, "OrbitalPeriod":27460209727.287292, "RotationPeriod":85612.842798, "AxialTilt":0.000000, "WasDiscovered":false, "WasMapped":false }
{ "timestamp":"2020-07-22T15:09:05Z", "event":"FuelScoop", "Scooped":2.445099, "Total":56.747105 }
```

I can provide the entire file upon request.

**Comment by klightspeed** [comment]
That looks like you copied the call stack, and not the actual error.  Is it possible to get the actual error?

**Comment by Thurion** [comment]
Oops... I thought I copied it and then I didn't check... The error is:
`Uncaught TypeError: data is null`

**Comment by klightspeed** [comment]
I'm guessing this is in Firefox?  Firefox would give `Uncaught TypeError: data is null`, while Chrome would give something like `Uncaught TypeError: Cannot read property 'events' of null` (assuming the error is that the server is returning null or no content).

Since the page is dynamically generated, and the line numbers change each time, I wonder if you could look in the Debugger tab at `www.edsm.net => en_GB/settings/import => journal` the next time it occurs, and copy the code from that line, and maybe the line above and below it, in order to help Anthor find and fix the issue when they get back.  You don't want to copy the whole page, as otherwise you'd then have to reset your API key.

I'm guessing it's on the following line:
```
                             $.post('https://www.edsm.net/api-journal-v1', post, function(data){
>                                data = data['events'][0]; // Remove batch events ;)
```

**Comment by Thurion** [comment]
Yes I'm using Firefox. I assume something goes wrong in the line you posted because it crashes right after that in this line when it wants to access the data variable.
```javascript
if(data.msgnum == 100 || data.msgnum == 101 || data.msgnum == 102 || data.msgnum == 103 || data.msgnum == 402) 
{
    current.hide();
}
```

**Comment by AnthorNet** [comment]
Should be bypassed?

**Comment by Thurion** [comment]
What do you mean?

**Comment by klightspeed** [comment]
Erroring out on that line suggests that instead of returning
```
{"msgnum":100,"msg":"OK","events":[{"msgnum":100,"msg":"OK"}]}
```
it is occasionally returning
```
{"msgnum":100,"msg":"OK","events":[null]}
```

If you look in the network tab at the last `journal-v1` request, and look at Response -> Response Payload, is this what you see?

> Should be bypassed?
> What do you mean?

It looks like Anthor has added code into the javascript for the case where null is returned from the post.  Now for the case where it returns null for the event status.

**Comment by Thurion** [comment]
> 
> 
> Erroring out on that line suggests that instead of returning
> 
> ```
> {"msgnum":100,"msg":"OK","events":[{"msgnum":100,"msg":"OK"}]}
> ```
> 
> it is occasionally returning
> 
> ```
> {"msgnum":100,"msg":"OK","events":[null]}
> ```
> 
> If you look in the network tab at the last `journal-v1` request, and look at Response -> Response Payload, is this what you see?
> 

Yes that's exactly what I see when I get the error.

**Comment by AnthorNet** [comment]
Should be fixed now, I think

**Comment by Thurion** [comment]
I was able to import my journal files without any issues. It seems that it is fixed, indeed 👍
