### ISSUE TITLE
EDSM showing vast LY travelled due to CQC matches being imported into Flight Log via Journal files

### ISSUE THREAD

**Issue by CMDR-Evolution** [EDSM-NET/FrontEnd#375]
Good afternoon EDSM.
I found an issue with EDSM, where the Flight log is showing CQC systems as destinations in the flight path when imported via Journal files. 
![image](https://user-images.githubusercontent.com/56416336/89529074-fff4c200-d7e3-11ea-9a1c-6ebcad5dfbbf.png)

In turn, those events are being fed to EDD. For EDD, they have two tickets open to resolve a similar issue for their side when the PR is approved and merged:
https://github.com/EDDiscovery/EliteDangerousCore/pull/16
https://github.com/EDDiscovery/EliteDangerousCore/pull/17

For EDSM, would you be able to apply a similar fix please?

Kind regards, Alan - CMDR Evolution

**Comment by CMDR-Evolution** [comment]
Sorry. Should this be a backend ticket rather than frontend and should I move this request to another section? 

Many thanks

**Comment by AnthorNet** [comment]
Is this happening on EDSM journal import?
If yes do you have the concerned journal to take a look?

**Comment by CMDR-Evolution** [comment]
Hello AnthorNet,

Thanks for getting back to me. Yes, that's correct. To play CQC since finding the bug (which is quite rare), I've opened the journal files in notepad++ and removed the 'location' line before importing them. I'm so sorry, I manually went through EDSM and EDD to remove the entries of the 4 CQC systems in my history so they won't be showing now as they were causing my exploration stats to be wrong in EDD. However, the four systems are: 

- Theta Ursae Majoris, 
- Boepp SU-E d12-818, 
- Eta Cephei
- Bleae Aewsy GA-Y d1-14. 

Here's a journal file which has 'Theta Ursae Majoris' listed on line 34 (mirroring the issue from the original screenshot):
[Journal.200805164309.01.log](https://github.com/EDSM-NET/FrontEnd/files/5138028/Journal.200805164309.01.log)

Thank you so much o7

**Comment by Strategeru** [comment]
I got same error when I import Flight Log via Console updater. It adds these systems to Flight Log.
![Скриншот 2020-09-22 14 59 00](https://user-images.githubusercontent.com/25680266/93879327-2f07ba00-fce4-11ea-8d7b-ff44676512b3.png)

**Comment by CMDR-Evolution** [comment]
Can I check if this has been fixed in the last 4 months yet please?

**Comment by AnthorNet** [comment]
Not really, not sure how to check it properly, but you should be able to just delete them from your flight log?

**Comment by CMDR-Evolution** [comment]
Yeah, there's the time consuming work around of opening every log file, searching and manually deleting them.

For anyone reading this - if you play CQC and use EDSM journal import, you'll have incorrect flight logs and in turn, vastly different EDD stats.

You will need to either open the files and remove the CQC lines as mentioned or delete the flight log from EDSM, EDD and wherever else has an incorrect record of your travels... Although it's a hassle, I'd suggest using a text editor like notepad++ then search for the lines from the 4 systems in the bug report.

Be warned, Frontier are planning new CQC updates for Odyssey so you'll likely need to search for more systems from Q1 2020.

Get BlueMail for Android<http://www.bluemail.me/r?b=16117>
On 5 Dec 2020, at 15:12, AnthorNet <notifications@github.com<mailto:notifications@github.com>> wrote:

Not really, not sure how to check it properly, but you should be able to just delete them from your flight log?

**Comment by AnthorNet** [comment]
Should be fixed now!
