### ISSUE TITLE
[Enhancement] By id64 lookup path

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [EDSM-NET/FrontEnd#379]
Currently the only way (we could find) to get some sort of link to an EDSM page for an id64 is `https://www.edsm.net/typeahead/systems/query/$id`

We'd like to be able to link directly to system/stations from EDMC, and currently do so with a name lookup: `https://www.edsm.net/en/system?systemName=$name`, however this has issues when there are renamed or duplicate system names involved. We'd like a way to link out without having to hammer your API with requests that 90% of the time wont be used by our users.

**Comment by AnthorNet** [comment]
You can do : https://www.edsm.net/en/system?systemID64=XXX
