### ISSUE TITLE
Expand the galactic records

### ISSUE THREAD

**Issue by Thurion** [EDSM-NET/FrontEnd#38]
Currently there are a few records for celestial bodies in the statistics. It would be nice if they had their own section and more possible records to look up (hint elitegalaxyonline).

If possible, showing the record in the information for the body itself would also be nice. Example:
https://www.edsm.net/en/system/bodies/id/27/name/Sol/details/idB/3794/nameB/Sol
Would show the record for the best sun in the entire galaxy.

**Comment by ibanix** [comment]
What does "best sun" mean?

**Comment by Thurion** [comment]
That was an example.

But there are lots of stats which could be tracked: biggest star of that type, hottest star of that type, ...

**Comment by AnthorNet** [comment]
Will be done as part of #80
