### ISSUE TITLE
Carrier jump into a system doesn’t give you first discovery

### ISSUE THREAD

**Issue by alterNERDtive** [EDSM-NET/FrontEnd#380]
So when you jump into a system with a carrier, it auto-scans the main star (IIRC also secondaries, but the case here only has one, so w/e).

It properly ends up on EDSM, but doesn’t credit you for first discovery. Neither for the system, nor the main star:

![edsm-carrier-00-sys](https://user-images.githubusercontent.com/53827887/91371644-d7278180-e811-11ea-9f77-ba903376af3b.png)
![edsm-carrier-01-star](https://user-images.githubusercontent.com/53827887/91371654-dbec3580-e811-11ea-82e0-bd85844bf784.png)

Honking nor FSSing afterwards help. Other bodies FSSed in there work fine:

![edsm-carrier-03-planet](https://user-images.githubusercontent.com/53827887/91371675-ead2e800-e811-11ea-902a-6c03e69bbe0c.png)
![edsm-carrier-04-bodies](https://user-images.githubusercontent.com/53827887/91371679-ed354200-e811-11ea-9a8c-2f9bcd8820cb.png)

After relogging, the system is credited correctly (probably based on the location event):

![edsm-carrier-05-relog-system](https://user-images.githubusercontent.com/53827887/91371698-fde5b800-e811-11ea-9ba8-f5c5a10a8757.png)

The main star still isn’t.

Now, manually uploading journals works fine, as does “manually” doing a forced sync with EDDiscovery. I haven’t done that yet to give you the current state: https://www.edsm.net/en/system/id/56070002/name/Plio+The+BL-E+d12-0

Also I was NOT there in a Sidewinder. I was in a Dolphin. Incidentally, my alt account actually is carrier exploring in a Sidey, and the traffic breakdown keeps saying Imperial Eagle :)

**Comment by AnthorNet** [comment]
Mostly happening when the scan is send before the event was processed by our EDDN listener.
The current queue is a little late, so it's been monitored..
