### ISSUE TITLE
Holo-Me Upload Capture Window

### ISSUE THREAD

**Issue by brkamp** [EDSM-NET/FrontEnd#382]
When uploading a file for Profile Picture, the visable-area-capture window is small and doesn't seem to allow resizing.

![screenshot20200904-181704](https://user-images.githubusercontent.com/28462629/92293768-ecb83d80-eeda-11ea-8a4f-27d6bc0ac78b.png)

**Comment by klightspeed** [comment]
Please read the line above the "Upload Holo-Me"

> Only use screenshots from the main codex screen

The selection is the right size if you do what it says

![image](https://user-images.githubusercontent.com/147116/92296990-dca56a00-ef7d-11ea-801a-d656cc679338.png)

**Comment by brkamp** [comment]
That's where my screenshot came from. You can see that.

**Comment by brkamp** [comment]
Or do you mean the entire view? That is not so clearly stated... I took my
image from that page.

**Comment by klightspeed** [comment]
> Or do you mean the entire view? That is not so clearly stated... I took my image from that page.

Maybe it should read

> Only use screenshots **of** the main codex screen

**Comment by AnthorNet** [comment]
Changed the text
