### ISSUE TITLE
Ads take up too much room on mobile

### ISSUE THREAD

**Issue by spip01** [EDSM-NET/FrontEnd#384]
All the ads are almost full screen on mobile which makes the app unusable. I don't mind ads but there are 3 huge copies of the same ad on the page.

**Comment by AnthorNet** [comment]
Oh I'm sorry about it, Google did activate the automated placement, which can suck :D
I'll have to take a closer look, that said if you're a proud benefactor of EDSM, you shouldn't see any ;)

**Comment by AnthorNet** [comment]
Removed the auto ones ^^
