### ISSUE TITLE
EDSM likely hacked

### ISSUE THREAD

**Issue by WinslowActual** [EDSM-NET/FrontEnd#386]
I just received an email saying that EDSM has deleted my account as requested and is sorry to see me go. I have not requested such action, so barring a very unfortunate bug, your accounts have been hacked. The following is that email, with the obvious parts redacted for privacy.

--removed for security due to response--

**Comment by AnthorNet** [comment]
Hey,
Sorry about that we effectively started to prune old account without activity for at least 3 years.
The email sent will be changed :)

**Comment by WinslowActual** [comment]
Could a warning email not have been sent before deleting an account? I entered a lot of info on this database. It would be nice to still have it tied to my name when I come back.

**Comment by AnthorNet** [comment]
I'll add it soon, but to be fair we're talking here about an account that haven't be logged in or played the game for at least 3 years.

**Comment by WinslowActual** [comment]
Understood, and I understand that the people handling these issues are probably donating time to do so, so I definitely harbor no ill will. It is just that warnings before something as drastic as account deletion is an industry standard now, especially considering the upsurge in returning players that game updates tend to generate. Case in point: No Man's Sky. Now, this is only considering simple policy procedures. If the issue is hardware related (space, maintenance issues, etc.), then obviously different methods are warranted.
Thanks for listening.

**Comment by AnthorNet** [comment]
I totally understand what you mean, being alone on this project it can sometime be tedious or lacking time. I'll stop the process and review my copy.so the mail is more comprehensive and to let a little more time for the user to keep things up.

That said it's not a win win if user kept their account and not using the tool as it takes a lot of space and slow things down for our current user database.

**Comment by WinslowActual** [comment]
I created and maintained Dell Computer's (just Dell now) database for the engineering department's quality history, alone, so I completely understand. I also see that a warning email could have the unintended result of getting accounts renewed just for situations like mine - where I _intend_ to play again and add to the database again, but I might not.
Again, thanks for listening, and know that everyone I played with truly appreciated that this database exists. I honestly think it should be merged into the full game and you should be paid for the effort, if anyone asks.
