### ISSUE TITLE
Polaris is not found in EDSM

### ISSUE THREAD

**Issue by Sortam** [EDSM-NET/FrontEnd#387]
Hi! 
It looks that something is not good with EDSM at the moment. Main page graph shows that flight log entries quantity gradually decreasing over several last days, I do not know if this is normal, but today I've found that Polaris cannot be found in EDSM. It was there and its page still exists in Google cache. (used to be here https://www.edsm.net/en/system/id/25526/name/Polaris) 
Is the database OK?

**Comment by klightspeed** [comment]
It sounds like it got caught up in the purge of systems that have not been modified in the last 2 years and that nobody that has been active in the last 3 years has visited.

Polaris is a permit-locked system with no known way of getting the permit, so nobody would have ever visited it.

**Comment by Sortam** [comment]
I got the impression that EDSM is the database of all systems ever visited, no matter how long ago or how often. If I properly understand what you are saying, it now has deleted all the systems which were discovered long time ago and were not visited since that time... It's a huge number, I suppose. And this would be illogical action in general, if you ask me.
Also, it sounds like all permit-locked systems with unobtainable permit have been deleted. 
I don't believe this is true. For instance, Bellica and Wolf 262 are still present despite of having unobtainable permit lock from the very beginning and never been visited by anyone.
But if you really know what you are talking about and that is not just a wild guess... Well. It's a pity.

**Comment by klightspeed** [comment]
See https://www.patreon.com/posts/prune-old-data-42187136

I suspect Anthor discovered the issue of systems being incorrectly pruned after Polaris was pruned but before the prune reached Wolf 262 or Bellica.

**Comment by Sortam** [comment]
Thank you for the information. RIP EDSM as we knew it.

**Comment by AnthorNet** [comment]
I added an exception to the pruning process, so Galactic Mapping systems aren't deleted.
