### ISSUE TITLE
Would Like To Share Krait Phantom Salvage White Paint Job

### ISSUE THREAD

**Issue by SurfinBird37** [EDSM-NET/FrontEnd#390]
I have one of the missing paint jobs and am trying to share it.

I am trying to make the HUD disappear in the Livery section by using Ctrl + Alt + G.  This feature seems to work everywhere else in the game for me except for in this section of the game.

Is there something I am doing wrong?

I could take a docked picture in free camera instead if this would be acceptable.

**Comment by AnthorNet** [comment]
We need to find a new solution about that!
Going here: https://github.com/EDSM-NET/ED-Ships-ScreenShots/issues/6
