### ISSUE TITLE
Errors Loading bootstrap.js from bootstrapcdn

### ISSUE THREAD

**Issue by pioto** [EDSM-NET/FrontEnd#396]
Seems that edsm.net relies upon https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js to serve bootstrap.js (which the UI relies upon or the menus don't work), but that's failing to load for me frequently, giving `net::ERR_CONNECTION_RESET` in Chrome.

Eventually it works, but it's.. frustrating.

Perhaps it would be better to bundle bootstrap with the site itself to avoid this?

**Comment by pioto** [comment]
I'm also seeing similar issues for the code.jquery.com CDN, which even more completely breaks the page...

**Comment by AnthorNet** [comment]
I've changed the used CDN, tell me if it's better

**Comment by pioto** [comment]
Does seem to be improved.

FWIW, I've been very satisfied with the performance & availability of cdnjs: https://cdnjs.com/

They seem to host jQuery, Bootstrap, etc.

**Comment by pioto** [comment]
Also note, cdnjs provides ways to let use [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) trivially (just copying their script tags includes it by default). That helps improve the security of your app should someone compromise the CDN.
