### ISSUE TITLE
Account creation problem.

### ISSUE THREAD

**Issue by UseLessUK** [EDSM-NET/FrontEnd#398]
I have the same commander name on the Xbox and the PC.

I started playing the game on the xbox first so when I created the EDSM account it was tied to the xbox, when I later got the game on the PC I thought I'd change the account from the xbox to the PC but there was no option on the site to do this. So I removed the account and now when I go to create a new PC one with the same commander name I am greeted with the error;

**That commander name is not available**

Both accounts have the same commander name but obviously different email addresses. The game and Frontier never complained when I created the commanders in either version of the game and used the same commander name. Perhaps the platforms gave them a unique ID?

It would have been nice if I could have had an account on EDSM for both platforms, but as that's not possible I'd settle for one account tied to the PC which is the platform I play on most.

**Comment by AnthorNet** [comment]
There's apparently already a PC commander account on EDSM.
Send me a private email to contact at edsm.net

I can assure you that creating both account is possible.

**Comment by UseLessUK** [comment]
> There's apparently already a PC commander account on EDSM.
> Send me a private email to contact at edsm.net
> 
> I can assure you that creating both account is possible.

And how can I send you a private message on edsm.net when I no longer have an account and therefore I'm unable to sign in?

**Comment by AnthorNet** [comment]
Like said, send me an email to contact at EDSM.net

**Comment by UseLessUK** [comment]
Oh! Missed that ... ;)

But problem solved, turns out it was me that created the account for PC but not with the normal email address I use, Turns out I used the one I used to create the Frontier account, once I entered that along with the correct password I could login rather than try an re-register.

Hey! I'm old what can I say ;)
