### ISSUE TITLE
EDSM isn't sending through the SAASignalsFound event for console accounts

### ISSUE THREAD

**Issue by chris4t** [EDSM-NET/FrontEnd#399]
Comment from Anthor (EDSM/SCIM)11/09/2020
I think the patch was done on EDDN?
So I'll need to add it

**Comment by AnthorNet** [comment]
It should since 2/3 weeks?

**Comment by chris4t** [comment]
Sent you an update email through Patreon messages.

**Comment by AnthorNet** [comment]
Hey, is it working for you or not?

**Comment by AnthorNet** [comment]
OK, added some more stuff, is it working now?

**Comment by chris4t** [comment]
Okay, I'll do some more testing when I get on again and let you know. Thanks!

**Comment by chris4t** [comment]
Still not working, first discovered PYULT AR-E B59-0, 9x hotspot signals, unable to find the system or signals using Spansh Body search.

**Comment by klightspeed** [comment]
Odd - it looks like a lot of the scans came in as `AutoScan` scans (which usually only occur when you are within 5ls of the body).

There is also one `Basic` scan (i.e. an old-style scan without a detailed surface scanner), and one `Detailed` scan of a ring (which used to only be possible with a detailed surface scanner).

The speed at which the scans were done suggests that a detailed surface scanner was not used.

`SAASignalsFound` is only generated by the game when you scan the body with a detailed surface scanner.  It is not generated when you fly close enough to the body for surface signals to be generated.

```
# bzcat 2021-02/*-2021-02-12.jsonl.bz2 | grep -i 'Pyult AR-E b59-0' | jq -c '.message | {timestamp,event,StarSystem,BodyName,ScanType}'
{"timestamp":"2021-02-12T04:01:12Z","event":"FSDJump","StarSystem":"Pyult AR-E b59-0","BodyName":null,"ScanType":null}
{"timestamp":"2021-02-12T04:01:17Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 A","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:01:17Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 B","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:01:18Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 C","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:01:18Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 D","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:03:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 2 a","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:03:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 2","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:03:24Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 2 b","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:03:24Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 2 c","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:03:24Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 3","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:05:25Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 2 A Ring","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:05:32Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 2 B Ring","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:08:04Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 3 A Ring","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 c","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 a","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 b","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:23Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 e","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:24Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 e a","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:13:24Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 d","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:14:31Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 A Ring","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:14:32Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 5 B Ring","ScanType":"Detailed"}
{"timestamp":"2021-02-12T04:16:05Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6","ScanType":"Basic"}
{"timestamp":"2021-02-12T04:16:31Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6 b","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:16:31Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:16:32Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6 e","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:16:32Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6 a","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:16:32Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6 d","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:16:32Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6 c","ScanType":"AutoScan"}
{"timestamp":"2021-02-12T04:17:27Z","event":"Scan","StarSystem":"Pyult AR-E b59-0","BodyName":"Pyult AR-E b59-0 ABC 6 A Ring","ScanType":"AutoScan"}
```

**Comment by chris4t** [comment]
The scans of the rings were done with a detailed surface scanner using probes, this is the scanner from the community event which has 50% more scan radius, I used to use an engineered version which has 30% more scan radius, so hence fewer probes but should still work. 

Also this system was not visible in Spansh Body search yesterday but today it is, but using ring signal search for the hotspots does not produce any results. Maybe this is a Spansh end problem?

Also this system is now visible in EDDB but no bodies.

**Comment by AnthorNet** [comment]
I'll try to debug a little more but I don't have a console to test it ;) that said it should be easy to check over EDDN if signals where send from EDSM condlle updater.

**Comment by chris4t** [comment]
Okay, I assume you can check EDDN, I don't know anything about that :(. I'm just jumping my carrier back to the bubble but I can go back out to generate some new signals next week. I can submit screenshots too if it helps.

**Comment by chris4t** [comment]
Latest comment from Spansh today; Looking at my logs I'm still not getting any SAASignalsFound from EDSM Console, only from EDSM journal

**Comment by chris4t** [comment]
Hello Anthor, any update from the previous comment regarding "not getting any SAASignalsFound from EDSM Console" I'm guessing this is for the ring signals? The system/body signals appear to be working after your last update.
Thanks!

**Comment by AnthorNet** [comment]
Hello I need to find real data for testing, so still no idea why you don't get what you need.

**Comment by chris4t** [comment]
It looks like klightspeed had some data in a previous post above. I can generate more data for you if you can let me know what you need.
This issue affects all console players, none of their discoveries, systems, bodies and ring signals are available to the third party tools such as EDDB or Spansh, I would have thought this was important to fix? It seems that your previous efforts have fixed the Systems/Bodies part, so just need to fix the ring signals.
Thanks!

**Comment by chris4t** [comment]
Latest update, it looks like the Systems/Bodies discovery is still not getting through, see attached images for data.
![Elite Dangerous_20210327232608](https://user-images.githubusercontent.com/76181379/113954651-de6b3080-97df-11eb-852a-d53faf537e5a.jpg)
![Elite Dangerous_20210330233240](https://user-images.githubusercontent.com/76181379/113954673-e88d2f00-97df-11eb-8f67-87b20e0960f1.jpg)

**Comment by AnthorNet** [comment]
Not sure how those screens relates to your issue?

**Comment by AnthorNet** [comment]
I've successfully send one, but you need to update the same day for them to be send to EDDN.

**Comment by klightspeed** [comment]
Just to clear up any potential confusion, it looks like Anthor fixed this at around 09:30 UTC - 5 `SAASignalsFound` events have been sent by `EDSM - Console` since then.

**Comment by chris4t** [comment]
Anthor, the screens show newly discovered systems, the purpose was to generate new data that should be sent to EDDN/EDDB. When I checked EDDB the system was not available, so therefor the data was not sent, proving that it is not working. I was hoping that by giving you the screenshots you could see the time and date, to check logs.

klightspeed, I'm not sure what the confusion is here. Spansh previously commented that "Looking at my logs I'm still not getting any SAASignalsFound from EDSM Console, only from EDSM journal" What is the confusion with that comment? If I'm not understanding this correctly please explain.

If it has indeed been fixed I will test again. That means I have to take a ship out far enough to discover new, previously undiscovered, systems to check if everything is being updated correctly. I will let you know.
Thanks again for your work.

**Comment by bgol** [comment]
The system was added to EDSM [Swoiwns VL-C a26-3](https://www.edsm.net/en/system/id/64104758/name/Swoiwns+VL-C+a26-3) but never send over [EDDN](https://edgalaxydata.space/eddn-lookup/systems.php?systemName=Swoiwns%20VL-C%20a26-3).

**Comment by chris4t** [comment]
> The system was added to EDSM [Swoiwns VL-C a26-3](https://www.edsm.net/en/system/id/64104758/name/Swoiwns+VL-C+a26-3) but never send over [EDDN](https://edgalaxydata.space/eddn-lookup/systems.php?systemName=Swoiwns%20VL-C%20a26-3).

Thank you for confirmation. Has this been fixed?

**Comment by klightspeed** [comment]
> klightspeed, I'm not sure what the confusion is here. Spansh previously commented that "Looking at my logs I'm still not getting any SAASignalsFound from EDSM Console, only from EDSM journal" What is the confusion with that comment? If I'm not understanding this correctly please explain.

The fix to SAASignalsFound events not being sent was not a retroactive fix, so any events from before 2021-04-08 09:30Z will have remained unsent.  There have now been 62 SAASignalsFound events sent by `EDSM - Console` since then.

> The system was added to EDSM [Swoiwns VL-C a26-3](https://www.edsm.net/en/system/id/64104758/name/Swoiwns+VL-C+a26-3) but never send over [EDDN](https://edgalaxydata.space/eddn-lookup/systems.php?systemName=Swoiwns%20VL-C%20a26-3).

This is likely a separate issue to SAASignalsFound events not having been sent.

**Comment by chris4t** [comment]
> > klightspeed, I'm not sure what the confusion is here. Spansh previously commented that "Looking at my logs I'm still not getting any SAASignalsFound from EDSM Console, only from EDSM journal" What is the confusion with that comment? If I'm not understanding this correctly please explain.
> 
> The fix to SAASignalsFound events not being sent was not a retroactive fix, so any events from before 2021-04-08 09:30Z will have remained unsent. There have now been 62 SAASignalsFound events sent by `EDSM - Console` since then.
> 
> > The system was added to EDSM [Swoiwns VL-C a26-3](https://www.edsm.net/en/system/id/64104758/name/Swoiwns+VL-C+a26-3) but never send over [EDDN](https://edgalaxydata.space/eddn-lookup/systems.php?systemName=Swoiwns%20VL-C%20a26-3).
> 
> This is likely a separate issue to SAASignalsFound events not having been sent.

Okay, I understand there was fix on 2021-04-08 09:30Z, that is not retroactive, so I will test now and give an update.

I'm not sure I understand the second comment where you state that "this is likely a separate issue"? Are there two issues?

**Comment by AnthorNet** [comment]
Events  aren't sent to EDDN if older than current day. So if you want them passed you need to update as you play.
