### ISSUE TITLE
Site in infinite loading loop in Firefox 84.0 due to NS_BINDING_ABORTED 

### ISSUE THREAD

**Issue by 1UPNuke** [EDSM-NET/FrontEnd#401]
I was unable to access the site using Firefox 84.0 due to it getting stuck in an infinite loading loop.
Looking into the network tab I saw NS_BINDING_ABORTED and doing a bit of googling, it could be because of the site not sending HTTP expires headers.
Clearing the cache for EDSM resolved the issue.

**Comment by klightspeed** [comment]
```
GET / HTTP/1.1
Host: www.edsm.net

HTTP/1.1 200 OK
Server: nginx
Date: Wed, 23 Dec 2020 16:02:24 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: PHPSESSID=d9s3e48lak9u4phqs4s4t8dmnd; path=/; secure
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```
It _is_ sending the `Expires` header, and it's telling the browser not to cache the site, so if the browser is caching the site then it is a browser issue.

**Comment by floatingatoll** [comment]
I confirmed on 84.0.1 with a fresh profile and no special addons or content blockers that it is honoring the nocache headers.

**Comment by 1UPNuke** [comment]
Hmm, I guess I'll have to see if any of my add-ons are causing it to be cached.
I thought this wasn't the case, but since on a fresh profile it respects it, it must be one of them.
