### ISSUE TITLE
Distance from start has gotten stuck at 3207Ly

### ISSUE THREAD

**Issue by gbravery** [EDSM-NET/FrontEnd#402]
Currently out beyond the bubble, doing the travel 5000Ly trip to unlock an engineer.

I’m at system: Traikaae QJ-I c9-32
It says it is 4650Ly from Sol, but 3207Ly from start.

last few systems have all said the same distance from start (3207).

I've refreshed browser, and tried checking on another device..

**Comment by AnthorNet** [comment]
From start is only updated when the game launch as it uses the game stats

**Comment by gbravery** [comment]
So if I exit and re-enter now (5091Ly from Sol) I’ll get a different answer now?

**Comment by AnthorNet** [comment]
Yes it should update when the game sends the stats event.
