### ISSUE TITLE
"el-" prefix in username leads to garbage in headline in various frontend pages 

### ISSUE THREAD

**Issue by GrimmerSchnitter** [EDSM-NET/FrontEnd#403]
For my secondary Elite:Dangerous user I chose a username with a minus-sign in the name, pretty common I think.

Going to my users's profile page, fleet page etc. leads to an wrong username "PROFILE\CMDR %1$" instead of "user-name" in the headline.
The user name ist written correctly in other fields.
Verified for my account for the german and english locales.

Screenshot:
![grafik](https://user-images.githubusercontent.com/76740144/103292963-37604700-49ef-11eb-92a2-e112ea2c8341.png)

**Comment by AnthorNet** [comment]
Very odd, tested on other account with a dash and they work properly.

**Comment by GrimmerSchnitter** [comment]
> Very odd, tested on other account with a dash and they work properly.

Indeed.
Even more odd: when I replace the minus by an space, the display is fine, reentering the minus leads to the same garbage. spooky...

Haven't checked that with my primary account yet, but will do as soon ans possible.


EDIT:

I have just tested the problem with my primary access.
This phenomenon does not occur there.

As long as there are no further "inconsistencies" in the backend, I can live with it.

**Comment by klightspeed** [comment]
Confirmed here - prepending `el-` to a commander name results in the issue.  Prepending `ej-` or `al-`, or adding a dash somewhere does not result in the issue.

**Comment by GrimmerSchnitter** [comment]
In addition to klightspeed's reply, I was able to reproduce this issue of at last the following prefixes:
de-, fr-, da-, en-, es-, pt- and br- (only these have been tested by me).
This leads me to the idea, that this could be an language-related issue, since all prefixes mentioned above are ISO 639-1 language codes for german, french, danish, english, spanish, portuguese and brazilian portuguese. (see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
This issue may or may not affect all of the mentioned ISO language codes, I didn't try all of them.
It may also lead to security related issues.

**Comment by AnthorNet** [comment]
Looking at the framework code, there's a locale check before getting the string to replace :D
It should not lead to any security issues, but I need to runs some tests in order to fix it :)

**Comment by GrimmerSchnitter** [comment]
> Looking at the framework code, there's a locale check before getting the string to replace :D
> It should not lead to any security issues, but I need to runs some tests in order to fix it :)

thanks, that was fast!
