### ISSUE TITLE
My Emergence Livery Sidewinder

### ISSUE THREAD

**Issue by PhoenixRiver** [EDSM-NET/FrontEnd#405]
It is showing up with an odd string instead of the livery name and the image of a Sidewinder has an orange question mark over it... I presume this is because it is a new Sidewinder variant that you don't have a screenshot for.

Update: Text shown on Fleet page:

**Name: Softly Does it [softly]
Paintjob: %%sidewinder_pilotreward_01%%**

**Comment by PhoenixRiver** [comment]
Here is a screenshot of my Sidewinder with it's livery with Ultra graphics, @1920x1080 from the Livery page... it looks different from previous shots you have but Ctrl+Alt+G only removed the UI elements outside the livery page... I can gimp it if that would help and produce an acceptable result for you.

![Sidewinder-Emergence_Livery](https://user-images.githubusercontent.com/5155303H/103867862-62434d00-510b-11eb-8e3d-f0c54ff85f20.jpg)

Update: please tell me if you can't see the image... I dragged and dropped it into the git webpage comment box but I'm not sure it worked...

**Comment by AnthorNet** [comment]
Hello,

We will handle it there: https://github.com/EDSM-NET/Alias/issues/12
