### ISSUE TITLE
EDDI cannot connect to EDSM

### ISSUE THREAD

**Issue by Strawey** [EDSM-NET/FrontEnd#407]
After a catastrophic drive failure I had to reinstall Win10, ED, EDDI, Voice Attack etc. EDSM cannot load my Journal Logs and reports errors. EDDI cannot obtain Log from EDSM. I have regenerated an API in EDSM and entered it in EDDI but that did not help. Hope you guys can help.

**Comment by Slegnor** [comment]
There is currently a server migration occurring so It its likely due to this

**Comment by Strawey** [comment]
> There is currently a server migration occurring so It its likely due to this

Thanks for the reply, EDSM has been very slow, so that is as you say probably the reason. Any idea of the time scale?

**Comment by Tkael** [comment]
Could be a couple of days before most services are back. Likely a little bit longer for sphere and cube system queries (affecting EDDI routing functions).

For the latest updates, you can follow along on Discord: https://discord.gg/0sFOD6GxFZRc1ad0
If you're feeling generous and want / are able to help support EDSM: https://www.patreon.com/bePatron?u=4682480

**Comment by Strawey** [comment]
> Could be a couple of days before most services are back. Likely a little bit longer for sphere and cube system queries (affecting EDDI routing functions).
> 
> For the latest updates, you can follow along on Discord: https://discord.gg/0sFOD6GxFZRc1ad0
> If you're feeling generous and want / are able to help support EDSM: https://www.patreon.com/bePatron?u=4682480

Thanks for the reply, appreciate both you guys help.
