### ISSUE TITLE
Account was deleted

### ISSUE THREAD

**Issue by Cojo96** [EDSM-NET/FrontEnd#408]
I made my account yesterday, and was using it earlier today. I was uploading my logs, all was well, and I was doing fine.
I tried to log back in now, and it kept telling me I had the wrong email/password, despite not only having just made the account, but using my autofill. I tried to reset my password, but no email arrived. I then, on a whim, tried to make a new account, and it appears my account was deleted, as, using the same email, and even autofill for most of it, I was able to make a new account.

**Comment by AnthorNet** [comment]
Hello,

I am very sorry about that, we had some serious trouble during our migration to a new server wheee the performance were so bad that I had to rent another new one and migrate using our previous rollback.

Some data have vanished, but be assured it is not happening often, and you can now create your account again and enjoy :)

Sorry about that mess
