### ISSUE TITLE
Data missing between 10-Jan and 15-Jan

### ISSUE THREAD

**Issue by psdevil** [EDSM-NET/FrontEnd#409]
Data for my account is missing. SPARROWHAWK56

Will this be rectified and if not, can the data be sent again from EDDiscovery?

Great site - very useful !!!
![Inkededsm-data-missing_LI](https://user-images.githubusercontent.com/60613594/104815451-8f2ee880-580c-11eb-8d7c-52b897a78dae.jpg)

**Comment by klightspeed** [comment]
The migration of the server did not go as planned, and a rollback needed to be performed.  You will need to use the journal uploader (Import Journal in the Profile menu in EDSM -> https://www.edsm.net/en/settings/import/journal) to re-upload the missing data to EDSM.

**Comment by psdevil** [comment]
Was happy to do that. All completed. Thank you for making it so easy...
