### ISSUE TITLE
Ship paintjob delivery

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#41]
Could we have a github repository for ship screenshots so that we can upload them. 

Then it might be easier to manage

**Comment by AnthorNet** [comment]
I usually update it at the same time as EDSM: https://github.com/EDSM-NET/ED-Ships-ScreenShots

On EDSM, I have a crop occurring before production, but all raw PNG are going there.

**Comment by NoFoolLikeOne** [comment]
Thanks Anthor. I'l; figure out how to add these ships.

**Comment by AnthorNet** [comment]
I could write something better to auto-deploy and crop from these repo, but not sure it worth the time.
