### ISSUE TITLE
Cannot upload logs to EDSM.net

### ISSUE THREAD

**Issue by onura46** [EDSM-NET/FrontEnd#410]
When trying to upload missing logs to EDSM.net, I go to the "Import Journal" page and attempt to upload one of my journal files (titled something like "netLog.##########.01.log") and nothing happens on the page. I have confirmed this is not a fluke; it does not function on any of my computers, across browsers and across accounts. I am able to upload logs via EDDiscovery, however I need to individually upload logs that I lost in the migration last week.

Steps to reproduce:
1. Visit [the Import Journal page](https://www.edsm.net/en/settings/import/journal)
2. Attempt to upload a journal file
3. Observe that the page doesn't respond as expected.

**Comment by AnthorNet** [comment]
Could you send one of your file?
Not at he office right but from memory, you need to upload journal files, not the netlog one.

**Comment by onura46** [comment]
[netLog.210111204548.01.log](https://github.com/EDSM-NET/FrontEnd/files/5824974/netLog.210111204548.01.log)

Yes, here's one of the files. Where can these journal files be found?

**Comment by onura46** [comment]
I think I found the files you're mentioning. I apologize; I misunderstood the difference between the netlogs and journal files. For future reference by troubleshooters: the required journal files are in your User folder: C:\Users\%userprofile%\Saved Games\Frontier Developments\Elite Dangerous.
