### ISSUE TITLE
Dashboard: Wrong body on duplicate name in same system

### ISSUE THREAD

**Issue by booiiing** [EDSM-NET/FrontEnd#411]
Given: A system has multiple bodies with the same name
Given: At least one of the bodies is worth mapping
Given: The body has not yet been mapped by me
When: I sit in the system and watch the EDSM dashboard
Then: The wrong body might be shown as „worthy to map“
Expected: The right body is shown

Example: Leesti: Star and terraformed ELW are both named „Leesti“. Dashboard shows star as „worth mapping“.

**Comment by AnthorNet** [comment]
Do you have a screen capture for that?

**Comment by klightspeed** [comment]
EDSM does not distinguish between bodies with the same name within a system, so what <https://www.edsm.net/en/system/bodies/id/13814/name/Leesti/details/idB/4128/nameB/Leesti> displays as would be determined by the most recent scan to have come in.

The same with <https://www.edsm.net/en/system/bodies/id/14322/name/Tethlon/details/idB/14385710/nameB/Tethlon> and <https://www.edsm.net/en/system/bodies/id/3087/name/Rasmussen/details/idB/3205188/nameB/Rasmussen>

**Comment by AnthorNet** [comment]
Doing some tests about that: https://github.com/EDSM-NET/EDDN-Events/commit/b298de366799c85f6f5c0089c0f6a9b9d73fdf2a

**Comment by AnthorNet** [comment]
Updated the unique index to take Star/Planet into account
