### ISSUE TITLE
EDSM Dashboard refresh can get stuck.

### ISSUE THREAD

**Issue by Tenzian** [EDSM-NET/FrontEnd#413]
Occasionally the dashboard timer will get stuck & forces you to manually refresh the page.

It looks like the code to reset the timer is only called if there's a successful get() request from `dashboard/index/live`:

```javascript
    $(document).ready(function() {
        $('#dashboardLiveTimer').timer({
            duration: '10s',
            callback: function() {
                $('#dashboardLiveTimer').parent().hide();
                $('#dashboardLiveLoading').show();

                $.get("/en_GB/dashboard/index/live", function(data) {
                    $('#homeDashboard').html(data);
                    $('#dashboardLiveLoading').hide();
                    $('#dashboardLiveTimer').parent().show();

                    $('#dashboardLiveTimer').timer('reset');
                });
            },
            countdown: true
        });
    });
```

I think that if the get() doesn't return data, the timer reset is not getting called.

Looks like it needs an action to reset the timer in case of a failure or timeout.

**Comment by Tenzian** [comment]
For clarification, this isn't the scenario where the dashboard isn't the current tab so the timer's been carrying on unattended and giving you a garbage value when you return.

In this scenario, the dashboard has been the active tab all along, the timer becomes hidden and the loading icon is present permanently instead.

**Comment by klightspeed** [comment]
Call `$('#dashboardLiveTimer').timer('reset');` within a `.always(function(){})` on the promise returned by `$.get()`?

i.e.
```js
                $.get("/en_GB/dashboard/index/live", function(data) {
                    $('#homeDashboard').html(data);
                }).always(function(){
                    $('#dashboardLiveLoading').hide();
                    $('#dashboardLiveTimer').parent().show();
                    $('#dashboardLiveTimer').timer('reset');
                });
```

**Comment by Tonyindahouse** [comment]
I have this issue too.  It happens about 30% of the time.

**Comment by AnthorNet** [comment]
Should be fixed
