### ISSUE TITLE
Holo-me Selection not resizeable

### ISSUE THREAD

**Issue by quinnell** [EDSM-NET/FrontEnd#416]
When uploading a holo-me image, it's not resizeable.  
![image](https://user-images.githubusercontent.com/47070375/107079619-b9454c00-67b5-11eb-878b-9e4ec16096d4.png)

**Comment by Tenzian** [comment]
I don't think thats actually a bug. 

Your screenshot looks to me like you've pre-cropped the image of your commander from the screenshot of the codex page before you uploaded it.

If so, you need to upload the _whole_ screenshot of the codex page without cropping it and then the selection box will be the right size:

![Screenshot 2021-02-05 at 23 45 32](https://user-images.githubusercontent.com/13963952/107100445-4a471200-680c-11eb-9376-4fbeca1ed6c3.png)

**Comment by quinnell** [comment]
Yup, you're right.  Did as you suggested and it works.
