### ISSUE TITLE
Filter Sphere Systems by Star Class.

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#42]
I was having a look at the API and thought that sphere-systems API might be useful if it could return the star class or if it had an additional parameter to restrict it to a particular star class.

I was thinking that a really cool application would be to create a plugin for EDMC looked up the nearest Neutron star in a 60ly Sphere from the commander position and then displayed the name.
Another application would be to look up the nearest scoopable star.

**Comment by AnthorNet** [comment]
Have you tried `?showPrimaryStar=1` ?
It should work on all system query API.

**Comment by NoFoolLikeOne** [comment]
Will give it a try

**Comment by NoFoolLikeOne** [comment]
I gave it a go and it worked. Show primary would allow me to filter the stars myself. 

If this were in a plugin then an explorer would execute it ever jump or once every 45 seconds

I'm thinking it would reduce the amount of data the plugin was having to sort and also reduce the load on EDSM if we could limit the results to a particular star class.

**Comment by NoFoolLikeOne** [comment]
I've prototyped the EDMC plugin and its taking around 16 seconds to find the nearest Nuetron star.

**Comment by AnthorNet** [comment]
Is it good enough ?
Are you making multiple request to find it or the APi is to slow for that?

**Comment by NoFoolLikeOne** [comment]
Its a single api request every jump. 

Ideally I think it needs to run faster because you want to start planning your next jump while your fsd is cooling down. 16s os a bit long. But I could trigger it at the start of the jump instead of arrival.

Also Im running it with a 200ly range out of Sothis. I imagine it would take a lot longer to query at Sagitarius A. I'll try hard coding Sag A tonight and see how long it takes.

It will probably be good enough but Im also considering the impact on EDSM if the plugin gained widespread use.

That said I have no idea how widespread EDMC isage is.

**Comment by AnthorNet** [comment]
Ok, can you post the request ? I will try to optimise a little more.

**Comment by NoFoolLikeOne** [comment]
Just ran this one for Sothis and it was a lot slower than last night. It would ideally need to be a lot faster or it will take longer to return the results than then next jump. 

https://www.edsm.net/api-v1/sphere-systems?systemName=Sothis&minRadius=0&radius=200&showPrimaryStar=1

Colonia is a little slower returning 68,000 systems 

https://www.edsm.net/api-v1/sphere-systems?systemName=Colonia&minRadius=0&radius=200&showPrimaryStar=1

Sagitarius A* surprisingly is a faster and less systems than Colonia but then I guess less systems have been explored

https://www.edsm.net/api-v1/sphere-systems?systemName=Sagittarius%20A*&minRadius=0&radius=200&showPrimaryStar=1

So each query is going to return somewhere between 1 and 4 megabytes of data. 

If we had an extra parameter eg &type=Neutron Star then when the query is executed for systems in the bubble most of the time it would only return two systems.

**Comment by NoFoolLikeOne** [comment]
Ive created a repository for my prototype. Its pretty straightforward as you can see

https://github.com/NoFoolLikeOne/EDMC-Highway-N

**Comment by klightspeed** [comment]
I'm guessing that would require storing the primary star class in the system table, and indexing on (PrimaryStarClass, Z, Y, X).  Either that, or changing what I'm guessing would be a left join with the bodies table into an inner join when requesting by star class.

**Comment by NoFoolLikeOne** [comment]
The existing query already joins to get the class as its in the results, so where class = 'N' would probably suffice.

**Comment by AnthorNet** [comment]
The existing query do not do any join, it makes uses of our internal cache, because we're not filtering.
I'll run some tests with true filtering.

**Comment by AnthorNet** [comment]
Should be better, not sure I can do more without a complete rewrite of that part.

**Comment by NoFoolLikeOne** [comment]
Thanks Anthor, I  really appreciate you looking into this. Will have a play with it tonight and will see if there are any optimisations I can do from my side to avoid hitting the server every jump.
