### ISSUE TITLE
EDSM records page no longer loads record holders.

### ISSUE THREAD

**Issue by ErkCurley** [EDSM-NET/FrontEnd#420]
https://www.edsm.net/en/statistics/bodies

![SmartSelect_20210302-023841_Chrome](https://user-images.githubusercontent.com/9462966/109614310-76e70480-7b00-11eb-823e-c7d304c7b40a.jpg)

**Comment by ErkCurley** [comment]
Confirmed this issue on mobile and desktop using chrome web browser.

**Comment by AnthorNet** [comment]
Hello, we're waiting for our ElasticSearch index to recover
