### ISSUE TITLE
Login/registration Error....

### ISSUE THREAD

**Issue by CmdrBrajha** [EDSM-NET/FrontEnd#421]
Hi, Complete Noob here !!
I followed the instructions to connect my PS4/Frontier account to EDSM. this worked perfectly.
the page then told me that i was logged in incorrectly (poss forgot to click console) and that i needed to re-register, unfortunately this also fails, reporting : "that email is not available"
please help.
I have been to both Colonia and Sag A* in a 36ly Anaconda and have loads of exploration data to contribute.

**Comment by CmdrBrajha** [comment]
ok it seems as though i may have jumped the gun !!!!!

im in and everything is updating....................................AWESOME !

**Comment by CmdrBrajha** [comment]
close this issue and put it down as a PICNIC error

Problem In Chair Not In Computer  👍

**Comment by AnthorNet** [comment]
:)
