### ISSUE TITLE
Celestias bodies records seams to be broken

### ISSUE THREAD

**Issue by vrampal** [EDSM-NET/FrontEnd#423]
Hello,
I tried to access the following pages and the content seams to be broken:
https://www.edsm.net/en/statistics/bodies
https://www.edsm.net/en/statistics/bodies/planets
(Tested with Firefox 86 and Chrome 88)
Any plan to fix ?
Thanks

**Comment by AnthorNet** [comment]
As soon as our Elasticsearch index is complete again ;)
