### ISSUE TITLE
Oldest stations -- bug or malfunction

### ISSUE THREAD

**Issue by athulin** [EDSM-NET/FrontEnd#426]
At present the 'oldest stations' page (https://www.edsm.net/en/systems/stations) is choked with fleet carriers.  After checking out some of them (including the one in Deciat, where there usually are lots of them around), I get a distinct impression that the listed fleet carriers are not in the identified systems anymore. (The ones in Deciat and 62 Ursae Majoris have definitely checked out)

If this is correct, it means this page no longer provides any useful functionality.

**Comment by AnthorNet** [comment]
Correct, stripped Fleet Carrier from spawning here!

**Comment by athulin** [comment]
Thanks! It seems to be restored to normal now.
