### ISSUE TITLE
[Feature Request] Oldest Station: Sort by "Space Stations" and "Landing Pad Size"

### ISSUE THREAD

**Issue by BobDaBilda** [EDSM-NET/FrontEnd#429]
Hello, I've recently begun using EDSM in earnest, trying to learn all the facets of Elite. I enjoy Trading, and Exploration, and have found that what Traders wish for, is updated Market Data. I would like to update the Market Data of space stations. I notice you have a great "Oldest Station" feature, linked on the home page. I would like to have the ability to sort the Oldest Stations for only Stations in space, rather than Settlements/etc. on Planets. 

I do not think I'm any good at Planetary Landings. I've found tips online to make them easier, but they still take me quite some time, and I don't really enjoy them. It would be lovely if I could use the Oldest Stations feature with Planetary Settlements excluded. This way, I can give Traders updated Market Data without repeatedly being sent to landings that take me much longer, and make me lose motivation to play.

Let me know if there's another site with similar functionality on the EDDN, so that you don't have to waste valuable dev time if this feature exists somewhere else, and I hadn't noticed. Thanks!

**Comment by spansh** [comment]
https://spansh.co.uk/stations/search/4A5A81D2-8E49-11EC-AFE8-2EA494EB4526/1

**Comment by BobDaBilda** [comment]
Feature is provided on spansh, closing this issue. Thanks to both spansh and EDSM for the great features.
