### ISSUE TITLE
blast resistant HRP shows up unengineered in coriolis export

### ISSUE THREAD

**Issue by bof** [EDSM-NET/FrontEnd#435]
Just felt trolled by EDSM ;-) engineered a kinetic resist and a blast resist HRP today, for a sidey; console updater synced what I did, was happy.... then later quickly did an export to coriolis to look at the stats - and had a shock seeing the kinetic HRP, but the blast one looked unengineered.

Back into the game, checked + all was well, engineering is okay; even engineered life support again, one more console updater round, life support eng shows - actually also seeing then that edsm fleet entry itself shows the blast resist engineering - but another coriolis export, is still missing it.

conclusion: there is some kind of bug in that exporting blast resistand HRP engineering to coriolis, does not show, while the other kinds of engineering for the same module type, do work.

(check the sidewinder on my "fredinspace23" acct, if that helps)

**Comment by isotopp** [comment]
Known Error on Coriolis Side.

https://github.com/EDCD/coriolis/issues/631

Also: Hi, long time no see (CMDR Isotopp in game)

**Comment by bof** [comment]
Hi Kris! Fun to meet again this way, and thanks for the info.

Closing this here then.
