### ISSUE TITLE
Not updating from PS5

### ISSUE THREAD

**Issue by JMYPINS** [EDSM-NET/FrontEnd#437]
Hi

My EDSM account will not update. I currently use a PS5, is this the cause?

Thanks.

**Comment by keelerad** [comment]
Can confirm that since the Odyseey update it doesn't work for PS4 commanders either, ie the console updater does its countdown but doesn't download any data

**Comment by AnthorNet** [comment]
Frontier have not restarted their API for that.

**Comment by keelerad** [comment]
OK @AnthorNet thanks for the info

**Comment by keelerad** [comment]
Seems to be working again now so guess they started the API up again

**Comment by AnthorNet** [comment]
Yep, all good now !
