### ISSUE TITLE
Import directly from Frontier API

### ISSUE THREAD

**Issue by daniloraisi** [EDSM-NET/FrontEnd#439]
I'm using EDSM a lot during my exploration. Thanks for a great job!

I'm missing some valuable information in my Flight Log and on the Dashboard page because I'm using more than one PC to play.

Sometimes I use my main Gamer PC to play Elite (connected to EDSM using EDMC). Other times I use other devices with GeForce NOW.

Since the Journal Entry is not transferred from one PC to another, I cannot see scanned and mapped systems (from GFN) into my EDSM account. Also, missing these systems in my Flight Log.

Any chance to implement importing directly from Frontier API?

**Comment by AnthorNet** [comment]
Sadly it cannot be done for performance reason, this is why it is only for Console users.
