### ISSUE TITLE
api=v1/system not returning data

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#44]
The following systems are not returning data but when I do a search on the front end I can find them, they have coordinates and a primary star.

NB: This is not a priority at all for me, just pointing out that they are missing

https://www.edsm.net/api-v1/system?systemName=PSR J0633+1746&showPrimaryStar=1&showCoordinates=1
https://www.edsm.net/api-v1/system?systemName=PSR J0953+0755&showPrimaryStar=1&showCoordinates=1
https://www.edsm.net/api-v1/system?systemName=PSR J0659+1414&showPrimaryStar=1&showCoordinates=1
https://www.edsm.net/api-v1/system?systemName=PSR J0030+0451&showPrimaryStar=1&showCoordinates=1
https://www.edsm.net/api-v1/system?systemName=PSR J1136+1551&showPrimaryStar=1&showCoordinates=1

**Comment by klightspeed** [comment]
Try urlencoding the name - e.g. https://www.edsm.net/api-v1/system?systemName=PSR+J0030%2B0451&showPrimaryStar=1&showCoordinates=1

**Comment by NoFoolLikeOne** [comment]
Doh! I should have thought of that. Thanks
