### ISSUE TITLE
Galactic News not updating

### ISSUE THREAD

**Issue by psdevil** [EDSM-NET/FrontEnd#442]
Not sure if this is a bug or not, but your Galactic News panel has not been updated since the '**_The Fall of the Oracle_**' item on 24th of May.

**Comment by AnthorNet** [comment]
Sadly the URLs used to catch those and community goals have been removed.
Not sure they are other yet to handle?

**Comment by bgol** [comment]
see: https://gist.github.com/corenting/b6ac5cf8f446f54856e08b6e287fe835

**Comment by AnthorNet** [comment]
Thanks!
