### ISSUE TITLE
Bug: incorrect API response

### ISSUE THREAD

**Issue by hurricup** [EDSM-NET/FrontEnd#446]
Request:  `https://www.edsm.net/api-v1/systems?systemName=hd+66`

Expected: all systems starting with `hd 66`
Actual: only `hd 66` 

Feels like system first checks exact match and returns it if any. But If I want the exact match, I use `system` endpoint, instead of systems.

**Comment by AnthorNet** [comment]
Hey!

https://www.edsm.net/api-v1/systems?systemName=hd+66%

Cheers

**Comment by hurricup** [comment]
Thank you. 
Would be nice to have this [documented](https://www.edsm.net/en/api-v1) then.
