### ISSUE TITLE
Forbidden Systems due to Alpha

### ISSUE THREAD

**Issue by AuraChad** [EDSM-NET/FrontEnd#449]
Wandered into Adityan last night.  When I imported my log it classified Adityan as forbidden software due to the Odyssey Alpha.

**Comment by AnthorNet** [comment]
??

**Comment by AuraChad** [comment]
![image](https://user-images.githubusercontent.com/86523215/123526014-0f525780-d6a3-11eb-9a9d-b11d6bef6981.png)

**Comment by esrise** [comment]
Same issue. Applies to some other actions in that system

![adityan-error](https://user-images.githubusercontent.com/84562438/136901972-6b3563c5-d897-4349-81f8-1f9eaa0e83eb.png)

**Comment by AnthorNet** [comment]
Fixed :)

**Comment by esrise** [comment]
Thank you :)
