### ISSUE TITLE
Linking EDSM and my Xbox Account

### ISSUE THREAD

**Issue by CMDR-Rashfest** [EDSM-NET/FrontEnd#450]
I don't know if i'm doing something wrong when creating an EDSM account and linking to Frontier with my xbox details but It doesn't seem to load anything. Ranks are all at 0 and travel is empty. Will this only populate from now or does it backdate and include my previous travel. Will it only populate once I return to a station?

Please let me know if theres something I need to do in order to link my accounts.

**Comment by AnthorNet** [comment]
Hey, you need to go to the dashboard and let it fill your data. It can take some time on first progressions.
