### ISSUE TITLE
Updating CMDR name in User Profile returns "Internal Error"

### ISSUE THREAD

**Issue by RearAdmiralPants** [EDSM-NET/FrontEnd#451]
When I created an EDSM account for my alt (CMDR FrontLtShirt), I made a typo and my username became FronLtShirt.

That was fine until I tried uploading my journals, when the site complained that they had nothing to do with the registered CMDR.

So I tried updating my profile - I changed "FronLtShirt" to "FrontLtShirt" and clicked save.

Immediately get "Internal Error." No additional text. Tried multiple times over the course of about a half hour.

**Comment by AnthorNet** [comment]
I see what is the problem but I'm not at the office until a week  I'll fix that when I'll be able to connect directly to the database.
Sorry about that
