### ISSUE TITLE
cant get my info to load

### ISSUE THREAD

**Issue by socaltrash65** [EDSM-NET/FrontEnd#457]
I've been trying to get my profile info to show up my frontier account and still nothing. Is there anything you can do to help?

**Comment by AnthorNet** [comment]
Are you on console or PC?

**Comment by socaltrash65** [comment]
console

**Comment by AnthorNet** [comment]
Have you let the dashboard page open to let it grab data from Frontier?

**Comment by socaltrash65** [comment]
yes ive had this account for 8 months now... ive unlinked my frontier account and linked it back and went to dashboard and waited refreshed still nothing..

**Comment by AnthorNet** [comment]
Doesn't seems like you have used the dashboard page. The last synced try is empty. Connecting to your account seems to work perfectly.

**Comment by socaltrash65** [comment]
ok some stuff is popping up thanks... will my ranks show up soon?

**Comment by AnthorNet** [comment]
You need to keep the dashboard open to sync data, right now it catches your data around mid August, so you have to wait a little to get the last data, but then if you open it when you play it will mostly keep up to date
