### ISSUE TITLE
Incorrect location of Abel Laboratory port (and possibly others)

### ISSUE THREAD

**Issue by hexedit** [EDSM-NET/FrontEnd#462]
Current shown location of **Abel Laboratory** (_Professor Palin_) is _Maia_ which is wrong. Right location is **_Arque_**
Also, in engineer tree, the location of Palin is fully incorrect - _Nanomam / Gresley Dock_

**Comment by AnthorNet** [comment]
I've deleted the old station which was incorrect and it has lead to unexpected changes :D
I'll fix it soon.
