### ISSUE TITLE
EDDN: Uploads: Bad journal/Scan messages

### ISSUE THREAD

**Issue by Athanasius** [EDSM-NET/FrontEnd#466]
The EDDN Gateway is rejecting some messages, e.g.

```
Failed Validation "[<ValidationError: "{'type': ['array', 'boolean', 'integer', 'number', 'null', 'object', 'string']} is not allowed for 'Hierro'">]" (1805, "EDSM", "1.0.1", "https://eddn.edcd.io/schemas/journal/1", "Scan")
```

The `Hierro` implies the code has put something like a system name in as a *key* ?

**Comment by Athanasius** [comment]
NB: Also affects softwareName `EDSM - Console`, version `1.0`

**Comment by Athanasius** [comment]
> The `Hierro` implies the code has put something like a system name in as a _key_ ?

Actually it's going to be that you have some key in the messages that's tagged 'disallowed' in the schema.  I would hazard a guess that it's going to be `HappiestSystem` and/or `HomeSystem`, *but* those aren't even on `Scan` events, only Location/FSDJump/CarrierJump.

Anyway, check the keys marked `disallowed` in the schema.

**Comment by klightspeed** [comment]
`.message.Materials[].Name_Localised="Hierro"`? (Google Translate tells me `Hierro` is spanish for `Iron`)

**Comment by Athanasius** [comment]
> `.message.Materials[].Name_Localised="Hierro"`? (Google Translate tells me `Hierro` is spanish for `Iron`)

That itself would point to an issue as no _Localised key/values are ever meant to be passed to EDDN.

**Comment by AnthorNet** [comment]
Make some change, let's see if it's better.
Don't have recent journal file to test against, or console account.

**Comment by Athanasius** [comment]
Did you bump the reported softwareVersion in the messages?  If not then my report script is going to continue **not** reporting on these again.

**Comment by Athanasius** [comment]
I did a manual grep of today's logging, and it's still occurring:

```
2022-01-09 10:51:31,603 - ERROR - Gateway:233: Failed Validation "[<ValidationError: "{'type': ['array', 'boolean', 'integer', 'number', 'null', 'object', 'string']} is not allowed for 'Soufre'">]" (1779, "EDSM", "1.0.1", "https://eddn.edcd.io/schemas/journal/1", "Scan")
```

Although if this is in-browser there's every chance a user might *still* have it open from before your changes, right?  I think that version bump would really help with this.

**Comment by AnthorNet** [comment]
Version bumped for both

**Comment by Athanasius** [comment]
Doesn't look to be fixed in EDSM/1.0.2:

```
2022-01-09 21:22:54,362 - ERROR - Gateway:233: Failed Validation "[<ValidationError: "{'type': ['array', 'boolean', 'integer', 'number', 'null', 'object', 'string']} is not allowed for 'Fer'">]" (1740, "EDSM", "1.0.2", "https://eddn.edcd.io/schemas/journal/1", "Scan")
2022-01-09 21:23:52,876 - ERROR - Gateway:233: Failed Validation "[<ValidationError: "{'type': ['array', 'boolean', 'integer', 'number', 'null', 'object', 'string']} is not allowed for 'Biological'">]" (439, "EDSM", "1.0.2", "https://eddn.edcd.io/schemas/journal/1", "SAASignalsFound")
```

**Comment by Athanasius** [comment]
I'm not seeing *any* errors from `EDSM - Console` now though.

**Comment by AnthorNet** [comment]
Yep made a mistake, should be revised now ^^ 1.0.3

**Comment by Athanasius** [comment]
> Yep made a mistake, should be revised now ^^ 1.0.3

No errors showing up this morning for 1.0.3 👍🏼
