### ISSUE TITLE
Credits balances aren't in sync with one another

### ISSUE THREAD

**Issue by olivvybee** [EDSM-NET/FrontEnd#469]
The various places on the site that show my credits balance are out of sync with one another. 

The latest transaction on the Account Book page is correct and up to date with the game. But the current balance display on the My Profile page and the graph on the Account Book page are out of date and showing 1,349,878 Cr which was my balance on Sunday 6th February.

My profile is CMDR olivvybee.

**Comment by AnthorNet** [comment]
The game only tells you the proper amount with the on load event,, so it is normal.
On the fly computation is only done on the credit page.
