### ISSUE TITLE
Test API cube-systems response missing showPrimaryStar

### ISSUE THREAD

**Issue by CrustyOldMan** [EDSM-NET/FrontEnd#47]
http://beta.edsm.net:8080/api-v1/cube-systems?x=0&y=0&z=0&size=1&showPrimaryStar=1
[
    {
        "name": "Sol"
    }
]

While it should be like:
https://www.edsm.net/api-v1/cube-systems?x=0&y=0&z=0&size=1&showPrimaryStar=1
[
    {
        "name": "Sol",
        "primaryStar": {
            "type": "G (White-Yellow) Star",
            "name": "Sol",
            "isScoopable": true
        }
    }
]

**Comment by AnthorNet** [comment]
hi,
Is there any specific need to use the BETA endpoint to test?

The beta wasn't updated for a long time, and the endPoint is only getting data. But if needed, I can update it next week.

**Comment by CrustyOldMan** [comment]
Hi,
No specific need. 

I'm working on a mini-map HUD-like overlay that will give users a 100 LY interactive scatter plot around their ship. I was trying to respect the alert in the API page "If you need to do some testing on our API, please use the http://beta.edsm.net:8080/ endpoint."

I used the main API instead and dumped the json to file for dev purposes. 

Cheers!

**Comment by AnthorNet** [comment]
I should update the alert to reflect that ^^
