### ISSUE TITLE
Calculated pathing inconsistent

### ISSUE THREAD

**Issue by Dushess** [EDSM-NET/FrontEnd#471]
I'm checking point to point travel and the site gives me straight path on full distance w/o even touching all transit stars. I've selected 17LY as jump distance but it ignores that and offering me single 151LY jump :facepalm:

Screen from the site:
![image](https://user-images.githubusercontent.com/15954961/154551651-001f640e-73c5-4586-9401-764c46232cb5.png)

**Comment by AnthorNet** [comment]
Hey,
As per the description above: The route planner will try to find waypoints every 1.000ly or so, based on the best range provided by your max jump range.

**Comment by Dushess** [comment]
Ahh ok ok, I will try with something bigger.
