### ISSUE TITLE
Lost Souls 3 Expedition - EDSM showing exped 'complete'.

### ISSUE THREAD

**Issue by SMaloo** [EDSM-NET/FrontEnd#475]
Hi... first time on this forum so apologies if posting in wrong place. I am a member of The Fatherhood and am taking part in the Lost Souls 3 exped. I jumped into and out of Hajangai just once today and now EDSM is showing me as 'completed' the whole expedition. I have not been to any waypoints for the exped. Can you assist?

**Comment by jberanek** [comment]
This is a problem for a number of members of the expedition, including one of the expedition leaders, Drazkul.

**Comment by jberanek** [comment]
So, it seems this may have been fixed/worked around by changing the endpoint to a different system.

However, myself (Dolen Lornaki) and other have reached the first waypoint (with EDSM showing that in the flight log) but the Expedition doesn't show the waypoint as reached.

**Comment by AnthorNet** [comment]
I've reset most of the faulty completed. The rest is just a cache problem that will resolve by itself. 
As long as the flight logs are correct, everything should recalculate properly.

**Comment by SMaloo** [comment]
Thank you and o7

 :) 🐯

On 5 Apr 2022, at 05:41, AnthorNet ***@***.***> wrote:

﻿

I've reset most of the faulty completed. The rest is just a cache problem that will resolve by itself.
As long as the flight logs are correct, everything should recalculate properly.
