### ISSUE TITLE
Engineers Juri Ishmaak Surface Scanner completely wrong 

### ISSUE THREAD

**Issue by Halderim** [EDSM-NET/FrontEnd#476]
The section for Scanners at least the Surface Scanner is totally wrong and needs a update
There is only one effect in the game 
 - Expanded probe scanning radius 

And the needed materials are not correct from Tier 3 and up 

![image](https://user-images.githubusercontent.com/13415330/162182859-18e71239-897a-49e0-8215-dcd46a9eaa07.png)
![image](https://user-images.githubusercontent.com/13415330/162182880-f5596cf5-ea87-472b-a10d-5c1247d3b3b2.png)
![image](https://user-images.githubusercontent.com/13415330/162182903-19121ea8-c532-4803-a375-524443e45ec9.png)

**Comment by AnthorNet** [comment]
Thanks, I'll take a look next week :)

Should be here: https://github.com/EDSM-NET/Alias/blob/master/Station/Engineer/Blueprint/Available.php#L373
