### ISSUE TITLE
Unable to login to edsm account

### ISSUE THREAD

**Issue by stevan54** [EDSM-NET/FrontEnd#477]
I noticed my email address was not correct in my EDSM account so I changed it and now am unable to login. I tried change password etc, but do not receive an email.

Cmdr Name: Tinieblas Obscuridad.
Old email ***
Correct email ***

**Comment by AnthorNet** [comment]
You have created multiple account with other emails. Should be fixed now

**Comment by stevan54** [comment]
Thank you very much.
All working as should.
