### ISSUE TITLE
Import does not check commander name when importing log files

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#48]
https://www.edsm.net/en/settings/logs/import

Its a nice problem to have, but when i submitted my logs i just dumped my entire directory into edsm. This caused all my RapidfireCRH data to be put on my slowice account. Can we have the importer read the active user so it puts the correct name in?

**Comment by klightspeed** [comment]
i.e. have an option to only include logs from a particular commander, and ignore any logs that contain a `LoadGame` for a commander that does not match that commander name?
