### ISSUE TITLE
401 Unauthorized Error

### ISSUE THREAD

**Issue by Rumzfeld** [EDSM-NET/FrontEnd#483]
Hello,
I am unable to sync my CMDR via EDSM
I am playing on console (Xbox series X)
CMDR Name:  Rumzfeld
Email:  DMK769@Gmail.com

Attaching the error from sync:

Oops! An Error Occurred

The server returned a "401 Unauthorized".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Any assistance would be greatly appreciated!
o7

**Comment by AnthorNet** [comment]
Hey,
Are you sure that error isn't on frontier domain?

**Comment by Rumzfeld** [comment]
Wow - Thank you for the quick response.....  User error....
I was signed into the wrong Outlook. D' oh.... flippin' noob.  :)

Appreciate the fast reply.  Apologies, it was on my end.
Fly Dangerously CMDR  o7


Cheers,


*David Kieser*
*M:* 781/639.9729
*E:* ***@***.***
35 Pitman Road
Marblehead, Massachusetts 01945-1433
[image: Facebook icon] <https://www.facebook.com/DMK769> [image: Twitter
icon] <https://twitter.com/DavidKieser> [image: LinkedIn icon]
<https://www.linkedin.com/in/david-kieser-4737294/>
