### ISSUE TITLE
Commodity Values are Not Correct for Silver in Some Areas

### ISSUE THREAD

**Issue by zaxlofful** [EDSM-NET/FrontEnd#484]
I recently went to use the tool so that I could make a good amount of money, but the value of silver in a few locations appears to be wrong. I went there only to find out it was the same price as other places not 10x cheaper.

Here is a link to the one of the systems with silver....It says 3,389 cr, but its actually 33,902 (i'm there in game right now).

https://www.edsm.net/en/system/stations/id/13245/name/44+chi+Draconis/details/facility/market/idS/265/nameS/Steinmuller+City

**Comment by klightspeed** [comment]
That station was last updated 12 days ago by someone visiting the station and submitting market data for it to EDDN using something like EDMC.
