### ISSUE TITLE
Authentication - Have to login with my Frontier account every time I want to use EDSM

### ISSUE THREAD

**Issue by louisrousseau** [EDSM-NET/FrontEnd#487]
Browser: Chrome 104.0.5112.81 on Windows 10.
Login is done through the Frontier Auth Service.
Upon trying to open EDSM again, typically one or two days later, have to login again.
Any logs or reports that would be useful to troubleshoot?

Thanks,

Louis

**Comment by klightspeed** [comment]
Are you on Epic?  The Epic OAuth2 refresh tokens have a very short lifetime, and expire after a day or two.

**Comment by louisrousseau** [comment]
So far I've been using the Frontier login and password directly; my Frontier account is linked to my Steam account, just attempted using Steam via Frontier, will update if it makes a difference.

**Comment by klightspeed** [comment]
I don't think "Remember Me" is an option for Frontier logins, so the session cookie keeping you logged in will vanish when you close your browser.  I think sessions are also aged out on the server if they haven't been used for a certain amount of time.

**Comment by louisrousseau** [comment]
> I don't think "Remember Me" is an option for Frontier logins

I don't see one.

> the session cookie keeping you logged in will vanish when you close your browser

Looks like that's what's happening: even with explicit "allow cookies + third party site cookies" settings for [\*.]frontier.co.uk, [\*.]frontierstore.net, and [\*.]edsm.net closing the browser scraps the session.

I tried checking the "Remember me" box below the e-mail login form in the hope it might affect the Frontier login as well but no such luck.

Can something be done on the site with respect to the Frontier login feature or is it a system limitation and I should simply look into creating an e-mail based account instead?

**Comment by klightspeed** [comment]
If you want to use normal EDSM authentication, you should be able to do a password reset on EDSM using the email address associated with your frontier / steam account.

**Comment by louisrousseau** [comment]
> If you want to use normal EDSM authentication, you should be able to do a password reset on EDSM using the email address associated with your frontier / steam account.

Did that, checked "Remember me" - looks like it maintains the session now, thanks!
