### ISSUE TITLE
Console to PC (Steam Deck) Transfer Options

### ISSUE THREAD

**Issue by TheBazzer** [EDSM-NET/FrontEnd#488]
Hi, I've recently migrated from PS4 to PC using Frontier's Console Migration service. The email I used with my Sony account is the same as the email registered with Frontier for the new PC account. I'm actually running Elite Dangerous on a Steam Deck. When I login to EDSM.net using the Frontier Auth Service, as a Frontier account (i.e. not using PlayStation Auth) I get this message when I go to the Dashboard:

<img width="1355" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/80899788/194783696-7824bf32-a90c-47a8-85d7-b254a450d78d.png">

No matter if I unlink the accounts, when I login I get the same message again, and the Console updated doesn't appear to be functioning.

**Comment by AnthorNet** [comment]
Hey, switched your account to PC.

**Comment by TheBazzer** [comment]
Thank you!
