### ISSUE TITLE
Steam Deck Data Upload

### ISSUE THREAD

**Issue by TheBazzer** [EDSM-NET/FrontEnd#492]
Hi, I've moved from PlayStation to Steam Deck. I can login to EDSM because someone switched me to a PC player, but Steam Deck doesn't run Windows and I can't see how to run anything that will do the same as the old "Console Uploader" on the Dashboard.

Any assistance would be appreciated. I've got a whole load of exploration data to upload.

**Comment by AnthorNet** [comment]
On PC, we can only allow software to sync, or manual journal upload.
You could also try Journal Limpet to try to get access to your journal file, but no idea if it's working correctly with update 14 :(

**Comment by TheBazzer** [comment]
... buts it's not really a PC, it's much more like a hand-held console, it just is able to run the Steam version of Elite Dangerous.

https://store.steampowered.com/steamdeck

**Comment by TheBazzer** [comment]
Hi,

The problem is that the Steam Deck isn't really a PC. It's more like a console that can run the Steam version of Elite Dangerous. I can't see how I can get the journal files.

https://store.steampowered.com/steamdeck

**Comment by klightspeed** [comment]
From the Steam Deck's Desktop mode, you should theoretically be able to find your journals (likely somewhere like `/home/deck/.local/share/Steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Frontier Developments/Elite Dangerous`), and upload them directly to EDSM using its journal upload.
Unless desktop mode allows you to run programs in the background while playing a game, most of the third-party tools to upload to EDSM / EDDN are unlikely to be useable for uploading to EDSM after each play session - EDMC only sends data to EDSM and EDDN as you're playing, and not after the fact, and EDDiscovery and EDDI both require Mono to run under Linux.
