### ISSUE TITLE
How can I switch my account to PC (from console)

### ISSUE THREAD

**Issue by Kash0321** [EDSM-NET/FrontEnd#495]
Hi.

I have switched from console to PC, and now EDSM is not updating my data, can you help me?

EDSM says this from the dashboard, in red background:

The currently linked account is your Frontier account associated with your console one.
Please unlink it from the [Settings > Security page](https://www.edsm.net/es/settings/security), go back to the dashboard and link again making sure you click the console icon when signing in the Frontier Auth Service.
Due to the new Update 14, we cannot support the console player base anymore. I'm very sorry about that.

**Comment by AnthorNet** [comment]
Your account was switched on PC on EDSM.

**Comment by Kash0321** [comment]
Thank you very much

**Comment by Kash0321** [comment]
Sorry to bother you again... I think it is not working on my account the data update process, it is stuck at 20% and the data collected is from a long time ago.

![image](https://user-images.githubusercontent.com/10654401/228136425-b5b87e67-9a0b-4b23-9245-b8010709e1cb.png)

![image](https://user-images.githubusercontent.com/10654401/228136934-67e04b7d-3ebb-45f8-80d4-ef5221bc7251.png)

Thanks
