### ISSUE TITLE
How can I switch my account to PC (from PS4)

### ISSUE THREAD

**Issue by Mr-Radagast** [EDSM-NET/FrontEnd#499]
Hi.

I have switched from console to PC, and now EDSM is not updating my data, can you help me?

EDSM says this from the dashboard, in red background:

The currently linked account is your Frontier account associated with your console one.
Please unlink it from the [Settings > Security page](https://www.edsm.net/es/settings/security), go back to the dashboard and link again making sure you click the console icon when signing in the Frontier Auth Service.
Due to the new Update 14, we cannot support the console player base anymore. I'm very sorry about that.

**Comment by AnthorNet** [comment]
Done :)
Make sure to use a software to update to EDSM as you play.
