### ISSUE TITLE
Badges / Achievements

### ISSUE THREAD

**Issue by AnthorNet** [EDSM-NET/FrontEnd#5]
Add an achievement system:

- Travelled across the galaxy (Reach Beagle Point)
- 10.000ly club
- Triple Elite
- ...

Suggestions are opened

**Comment by AnthorNet** [comment]
See EDSM-NET/FrontEnd#5

**Comment by muerta** [comment]
* Triangulator (submit xx valid distances)
* Humboldt's Trail (take part and finish x expeditions)

**Comment by RapidfireCRH** [comment]
Off the Mean - get x off the galactic mean
Well travelled - submit x amount newly discovered stars

**Comment by RapidfireCRH** [comment]
Earth-like Scanner - Add an earthlike to EDSM Bodies
Ammonia Scanner - Add an ammonia to EDSM Bodies
WaterWorld Scanner - Add an waterworld to EDSM Bodies
Terraformer Scanner - Add a terraformable body to EDSM Bodies
etc... There are alot of types. you might also do 100 and 1000 entries for the first 3
Might also be able to do top 3 or top 100 for each type. depending on how crazy you want to go

Ice Planets matter too - Scan[x] ice planets

Honk, Scan, Scoop - scan [x] primary bodies ([System name] A scans)
Scan all the bodies - scan [x] non-primary bodies (non [System name] A scans)

Going, going... - Make a 50+ly jump
...Gone - Make a 200+ ly neutron jump

Why fly when you can drive - get one planet surface material
Most the rest of the materials and data tracking isn't refined enough for other badges (synthesis vs dropping resources)

Share the Love - Create a POI in EDSM
I Double-Dog Dare you - Create a challenge in EDSM
Challenge Accepted - Complete EDSM Challenge

**Comment by RapidfireCRH** [comment]
XX new bodies discovered - Scan xx amount of bodies into EDSM from one system

**Comment by RapidfireCRH** [comment]
Star Confirmed - Confirm coordinates for x amount of stars

**Comment by RapidfireCRH** [comment]
Biggest, smallest, Hotest, Coldest - Get your name on this page https://www.edsm.net/en/statistics/bodies 
I would say you earn this one, you keep it, even if you get beat out by another.

**Comment by ghost** [comment]
Great idea! 👍 

Home, sweet home - Visit the same system 100 times.

**Comment by NoFoolLikeOne** [comment]
Alien Hunter, -- Visited all thargoid sites

**Comment by AnthorNet** [comment]
Thank you all for your ideas, things are being implemented, designed... etc ^^
You can have a preview here: https://www.edsm.net/en/test/badges
