### ISSUE TITLE
Suggestion: Expedition Logo Merchandising

### ISSUE THREAD

**Issue by NoFoolLikeOne** [EDSM-NET/FrontEnd#50]
It occured to me today that the expedition badges would look awesome printed as actual embroidered badges. Unfortunately that probably wouldn't fly because of setup costs,. 

But I was thinking that maybe EDSM could offer a merchandising link for the badges to raise funds for the service. I imagine people would pay for mugs hoodies and the like.

**Comment by AnthorNet** [comment]
Don't think we can have time for that, likely we could do an EDSM shop, but the other logos aren't copyrighted to us.
