### ISSUE TITLE
Missing msg/msgnum fields in the API response

### ISSUE THREAD

**Issue by negativefix** [EDSM-NET/FrontEnd#500]
`msg` and `msgnum` fields  are missing in the system/systems endpoint responses. These endpoints repond with `{}` provided an incorrect parameter value (see the example request below).  It would be much easier to check if the request has yielded something useful or not if `msg` and `msgnum`  are included in the response.

```http
GET https://www.edsm.net/api-system-v1/stations/shipyard
    ?systemName=Sol
    &stationName=Daedxalus
```

**Comment by AnthorNet** [comment]
Sadly won't be changed as it would results in breaking software that are coded to use that for a couple of years now ;)
