### ISSUE TITLE
Erroneously added stars that should be removed.

### ISSUE THREAD

**Issue by Tharkon** [EDSM-NET/FrontEnd#513]
While trying to find a solution to the problem that planets and stars scanned by wingmates are not recognized by any third-party tools my log generated some errors that made their way to the EDSM database.
The stars in question are:
- Preae Thae JV-K b51-0 Preae Thae TA-E d12-1 A
- Preae Thae JV-K b51-0 Preae Thae TA-E d12-1 B
- Preae Thae JV-K b51-0 Preae Thae TA-E d12-1 C

As the names should make obvious, these stars don't exist and should be removed from the database. I am not sure if Github is the most appropriate place to report this but I could not find a better solution.

**Comment by klightspeed** [comment]
This is often where the data submitted to EDSM is missing the `FSDJump` event for the system the stars are in.
The Death Star has been deployed to remove those stars.

**Comment by Tharkon** [comment]
That explanation makes sense.
It looks like the stars have been removed and the records restored.
