### ISSUE TITLE
Smuggling Information

### ISSUE THREAD

**Issue by GroundStop** [EDSM-NET/FrontEnd#514]
I've been trying to develop a tool that may provide insight as to what goods would be useful to smuggle in order to affect a minor factions INF in the BGS. I had a few questions that might help me understand if that's possible.

- A member of my squadron noticed that EDSM had a list of prohibited goods. Would it be possible to expose that via the API?
- Does the market endpoint include information about the black market demand of items?

**Comment by PaletzTheWise** [comment]
If I recall correctly, prohibited goods are based on the system state - controlling faction, its government type, etc. It should be possible to compute it from the already exposed data.

**Comment by GroundStop** [comment]
I had assumed this whole time that it differed somewhat randomly on a station by station basis, but you are absolutely correct about it being possible to compute this information. Thank you!

On the off-chance that someone else who needs this info stumbles across this later, I'm going to use the table from the wiki: 
https://elite-dangerous.fandom.com/wiki/Illegal_Goods
