### ISSUE TITLE
Restore deleted account/account deletion notices

### ISSUE THREAD

**Issue by JesusFreke** [EDSM-NET/FrontEnd#516]
I just got a notice that my edsm account was deleted. There was no prior warning or anything, just a notice that it was deleted for inactivity. Kindof a bummer, tbh. I haven't played E:D in quite a while, but I may still log back in at some point. It's just a bit of a bummer to lose all my edsm info.

If there's a way to restore it, that would be great. It was under the email ***. If not, oh well. No big deal. But I would like to recommend that notices be sent before any account deletion. Something along the lines of:

"Your account has been inactive for X years and will be deleted in 1 month. If you want to prevent account deletion, you can log in before that time."

**Comment by AnthorNet** [comment]
Hey,

Sorry about that did not have time to handle previous notice but still got 2 years of inactivity means generally the users are gone forever. You can still create a new account if you still have your old journal files to import

**Comment by Ponjimon** [comment]
Sorry for basically reopening this issue, but I just came back to Elite after a long hiatus and unfortunately, my account has also been wiped.

While I understand that you may want to keep your data clean of zombie data, deleting an account without any prior warning is a really bad experience.

> 2 years of inactivity means generally the users are gone forever.

I don't agree. Especially in an MMO like game, people take breaks. I play WoW, and I generally only play when a new expansion comes out for like 1-2 months, then I usually wait for the next expansion. Everyone has different preferences in life and things can happen.

I would appreciate it if there was at least a deletion notice email prior to actually deleting any data to let the user know that they can still take action and keep their data. Maybe they also forgot their EDSM account even exists and such email could remind them of it and make them come back to EDSM and/or Elite.

**Comment by alecvance** [comment]
I also wanted to chime in and say that a warning would have been nice!
