### ISSUE TITLE
Load issue while using large amount of recipes

### ISSUE THREAD

**Issue by DIDIx13** [EDSM-NET/FrontEnd#525]
Using large amount of alternate recipes result in huge load time.

Context : Once you get to (very) late game, you most likely have all the hard drives scanned. Therefore 

Simple exemple : [1 Iron Ore / Simple View Mode / All alternate recipes](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_OreIron_C%22%3A%221%22%2C%22altRecipes%22%3A%5B%22Recipe_Bauxite_Caterium_C%22%2C%22Recipe_Bauxite_Copper_C%22%2C%22Recipe_Caterium_Copper_C%22%2C%22Recipe_Caterium_Quartz_C%22%2C%22Recipe_Coal_Iron_C%22%2C%22Recipe_Coal_Limestone_C%22%2C%22Recipe_Copper_Quartz_C%22%2C%22Recipe_Copper_Sulfur_C%22%2C%22Recipe_Iron_Limestone_C%22%2C%22Recipe_Limestone_Sulfur_C%22%2C%22Recipe_Nitrogen_Bauxite_C%22%2C%22Recipe_Nitrogen_Caterium_C%22%2C%22Recipe_Quartz_Bauxite_C%22%2C%22Recipe_Quartz_Coal_C%22%2C%22Recipe_Sulfur_Coal_C%22%2C%22Recipe_Sulfur_Iron_C%22%2C%22Recipe_Uranium_Bauxite_C%22%2C%22Recipe_ResidualFuel_C%22%2C%22Recipe_ResidualPlastic_C%22%2C%22Recipe_ResidualRubber_C%22%2C%22Recipe_Alternate_RocketFuel_Nitro_C%22%2C%22Recipe_Alternate_IonizedFuel_Dark_C%22%2C%22Recipe_Alternate_Diamond_Turbo_C%22%2C%22Recipe_Alternate_Coal_1_C%22%2C%22Recipe_Alternate_Coal_2_C%22%2C%22Recipe_Alternate_Diamond_Pink_C%22%2C%22Recipe_Alternate_Diamond_Petroleum_C%22%2C%22Recipe_Alternate_Diamond_OilBased_C%22%2C%22Recipe_Alternate_Diamond_Cloudy_C%22%2C%22Recipe_Alternate_DarkMatter_Trap_C%22%2C%22Recipe_Alternate_DarkMatter_Crystallization_C%22%2C%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_TurboHeavyFuel_C%22%2C%22Recipe_Alternate_SteelRod_C%22%2C%22Recipe_Alternate_SteelCanister_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_RubberConcrete_C%22%2C%22Recipe_Alternate_RecycledRubber_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureCateriumIngot_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_PolymerResin_C%22%2C%22Recipe_Alternate_PlasticSmartPlating_C%22%2C%22Recipe_Alternate_HighSpeedWiring_C%22%2C%22Recipe_Alternate_HeavyOilResidue_C%22%2C%22Recipe_Alternate_HeavyFlexibleFrame_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_Alternate_FlexibleFramework_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_CopperRotor_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_CoatedIronPlate_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CoatedCable_C%22%2C%22Recipe_Alternate_BoltedFrame_C%22%2C%22Recipe_Alternate_AdheredIronPlate_C%22%2C%22Recipe_Alternate_TurboPressureMotor_C%22%2C%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_SuperStateComputer_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_RadioControlSystem_C%22%2C%22Recipe_Alternate_PlutoniumFuelUnit_C%22%2C%22Recipe_Alternate_OCSupercomputer_C%22%2C%22Recipe_Alternate_InstantScrap_C%22%2C%22Recipe_Alternate_InstantPlutoniumCell_C%22%2C%22Recipe_Alternate_HeatFusedFrame_C%22%2C%22Recipe_Alternate_FertileUranium_C%22%2C%22Recipe_Alternate_ElectricMotor_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_CoolingDevice_C%22%2C%22Recipe_Alternate_ClassicBattery_C%22%2C%22Recipe_Alternate_AutomatedMiner_C%22%2C%22Recipe_Alternate_AlcladCasing_C%22%2C%22Recipe_Alternate_SteelPipe_Molded_C%22%2C%22Recipe_Alternate_SteelPipe_Iron_C%22%2C%22Recipe_Alternate_SteelCastedPlate_C%22%2C%22Recipe_Alternate_SteelBeam_Molded_C%22%2C%22Recipe_Alternate_SteelBeam_Aluminum_C%22%2C%22Recipe_Alternate_AluminumRod_C%22%2C%22Recipe_Alternate_AILimiter_Plastic_C%22%2C%22Recipe_Alternate_Silica_Distilled_C%22%2C%22Recipe_Alternate_Quartz_Purified_C%22%2C%22Recipe_Alternate_Quartz_Fused_C%22%2C%22Recipe_Alternate_IronIngot_Leached_C%22%2C%22Recipe_Alternate_IronIngot_Basic_C%22%2C%22Recipe_Alternate_CopperIngot_Tempered_C%22%2C%22Recipe_Alternate_CopperIngot_Leached_C%22%2C%22Recipe_Alternate_CateriumIngot_Tempered_C%22%2C%22Recipe_Alternate_CateriumIngot_Leached_C%22%2C%22Recipe_Alternate_Wire_2_C%22%2C%22Recipe_Alternate_Wire_1_C%22%2C%22Recipe_Alternate_UraniumCell_1_C%22%2C%22Recipe_Alternate_TurboMotor_1_C%22%2C%22Recipe_Alternate_Stator_C%22%2C%22Recipe_Alternate_Silica_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Screw_C%22%2C%22Recipe_Alternate_Rotor_C%22%2C%22Recipe_Alternate_EncasedIndustrialBeam_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_1_C%22%2C%22Recipe_Alternate_RadioControlUnit_1_C%22%2C%22Recipe_Alternate_Quickwire_C%22%2C%22Recipe_Alternate_Plastic_1_C%22%2C%22Recipe_Alternate_NuclearFuelRod_1_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ModularFrame_C%22%2C%22Recipe_Alternate_IngotSteel_2_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_IngotIron_C%22%2C%22Recipe_Alternate_HighSpeedConnector_C%22%2C%22Recipe_Alternate_ModularFrameHeavy_C%22%2C%22Recipe_Alternate_HeatSink_1_C%22%2C%22Recipe_Alternate_Gunpowder_1_C%22%2C%22Recipe_Alternate_ElectromagneticControlRod_1_C%22%2C%22Recipe_Alternate_CrystalOscillator_C%22%2C%22Recipe_Alternate_Concrete_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Computer_1_C%22%2C%22Recipe_Alternate_CircuitBoard_2_C%22%2C%22Recipe_Alternate_CircuitBoard_1_C%22%2C%22Recipe_Alternate_Cable_2_C%22%2C%22Recipe_Alternate_Cable_1_C%22%2C%22Recipe_Alternate_PolyesterFabric_C%22%5D%7D)
Complex exemple : [Tier 9 items / Simple View Mode / All alternate recipes](https://satisfactory-calculator.com/en/planners/production/index/json/%7B%22Desc_SingularityCell_C%22%3A%221%22%2C%22Desc_FicsoniumFuelRod_C%22%3A%222%22%2C%22input%22%3A%7B%22Desc_PlutoniumFuelRod_C%22%3A%221.2%22%7D%2C%22altRecipes%22%3A[%22Recipe_Bauxite_Caterium_C%22%2C%22Recipe_Bauxite_Copper_C%22%2C%22Recipe_Caterium_Copper_C%22%2C%22Recipe_Caterium_Quartz_C%22%2C%22Recipe_Coal_Iron_C%22%2C%22Recipe_Coal_Limestone_C%22%2C%22Recipe_Copper_Quartz_C%22%2C%22Recipe_Copper_Sulfur_C%22%2C%22Recipe_Iron_Limestone_C%22%2C%22Recipe_Limestone_Sulfur_C%22%2C%22Recipe_Nitrogen_Bauxite_C%22%2C%22Recipe_Nitrogen_Caterium_C%22%2C%22Recipe_Quartz_Bauxite_C%22%2C%22Recipe_Quartz_Coal_C%22%2C%22Recipe_Sulfur_Coal_C%22%2C%22Recipe_Sulfur_Iron_C%22%2C%22Recipe_Uranium_Bauxite_C%22%2C%22Recipe_ResidualFuel_C%22%2C%22Recipe_ResidualPlastic_C%22%2C%22Recipe_ResidualRubber_C%22%2C%22Recipe_Alternate_RocketFuel_Nitro_C%22%2C%22Recipe_Alternate_IonizedFuel_Dark_C%22%2C%22Recipe_Alternate_Diamond_Turbo_C%22%2C%22Recipe_Alternate_Coal_1_C%22%2C%22Recipe_Alternate_Coal_2_C%22%2C%22Recipe_Alternate_Diamond_Pink_C%22%2C%22Recipe_Alternate_Diamond_Petroleum_C%22%2C%22Recipe_Alternate_Diamond_OilBased_C%22%2C%22Recipe_Alternate_Diamond_Cloudy_C%22%2C%22Recipe_Alternate_DarkMatter_Trap_C%22%2C%22Recipe_Alternate_DarkMatter_Crystallization_C%22%2C%22Recipe_Alternate_WetConcrete_C%22%2C%22Recipe_Alternate_TurboHeavyFuel_C%22%2C%22Recipe_Alternate_SteelRod_C%22%2C%22Recipe_Alternate_SteelCanister_C%22%2C%22Recipe_Alternate_SteamedCopperSheet_C%22%2C%22Recipe_Alternate_RubberConcrete_C%22%2C%22Recipe_Alternate_RecycledRubber_C%22%2C%22Recipe_Alternate_PureQuartzCrystal_C%22%2C%22Recipe_Alternate_PureIronIngot_C%22%2C%22Recipe_Alternate_PureCopperIngot_C%22%2C%22Recipe_Alternate_PureCateriumIngot_C%22%2C%22Recipe_PureAluminumIngot_C%22%2C%22Recipe_Alternate_PolymerResin_C%22%2C%22Recipe_Alternate_PlasticSmartPlating_C%22%2C%22Recipe_Alternate_HighSpeedWiring_C%22%2C%22Recipe_Alternate_HeavyOilResidue_C%22%2C%22Recipe_Alternate_HeavyFlexibleFrame_C%22%2C%22Recipe_Alternate_FusedWire_C%22%2C%22Recipe_Alternate_FlexibleFramework_C%22%2C%22Recipe_Alternate_ElectrodeCircuitBoard_C%22%2C%22Recipe_Alternate_ElectroAluminumScrap_C%22%2C%22Recipe_Alternate_DilutedPackagedFuel_C%22%2C%22Recipe_Alternate_CopperRotor_C%22%2C%22Recipe_Alternate_CopperAlloyIngot_C%22%2C%22Recipe_Alternate_CokeSteelIngot_C%22%2C%22Recipe_Alternate_CoatedIronPlate_C%22%2C%22Recipe_Alternate_CoatedIronCanister_C%22%2C%22Recipe_Alternate_CoatedCable_C%22%2C%22Recipe_Alternate_BoltedFrame_C%22%2C%22Recipe_Alternate_AdheredIronPlate_C%22%2C%22Recipe_Alternate_TurboPressureMotor_C%22%2C%22Recipe_Alternate_TurboBlendFuel_C%22%2C%22Recipe_Alternate_SuperStateComputer_C%22%2C%22Recipe_Alternate_SloppyAlumina_C%22%2C%22Recipe_Alternate_RadioControlSystem_C%22%2C%22Recipe_Alternate_PlutoniumFuelUnit_C%22%2C%22Recipe_Alternate_OCSupercomputer_C%22%2C%22Recipe_Alternate_InstantScrap_C%22%2C%22Recipe_Alternate_InstantPlutoniumCell_C%22%2C%22Recipe_Alternate_HeatFusedFrame_C%22%2C%22Recipe_Alternate_FertileUranium_C%22%2C%22Recipe_Alternate_ElectricMotor_C%22%2C%22Recipe_Alternate_DilutedFuel_C%22%2C%22Recipe_Alternate_CoolingDevice_C%22%2C%22Recipe_Alternate_ClassicBattery_C%22%2C%22Recipe_Alternate_AutomatedMiner_C%22%2C%22Recipe_Alternate_AlcladCasing_C%22%2C%22Recipe_Alternate_SteelPipe_Molded_C%22%2C%22Recipe_Alternate_SteelPipe_Iron_C%22%2C%22Recipe_Alternate_SteelCastedPlate_C%22%2C%22Recipe_Alternate_SteelBeam_Molded_C%22%2C%22Recipe_Alternate_SteelBeam_Aluminum_C%22%2C%22Recipe_Alternate_AluminumRod_C%22%2C%22Recipe_Alternate_AILimiter_Plastic_C%22%2C%22Recipe_Alternate_Silica_Distilled_C%22%2C%22Recipe_Alternate_Quartz_Purified_C%22%2C%22Recipe_Alternate_Quartz_Fused_C%22%2C%22Recipe_Alternate_IronIngot_Leached_C%22%2C%22Recipe_Alternate_IronIngot_Basic_C%22%2C%22Recipe_Alternate_CopperIngot_Tempered_C%22%2C%22Recipe_Alternate_CopperIngot_Leached_C%22%2C%22Recipe_Alternate_CateriumIngot_Tempered_C%22%2C%22Recipe_Alternate_CateriumIngot_Leached_C%22%2C%22Recipe_Alternate_Wire_2_C%22%2C%22Recipe_Alternate_Wire_1_C%22%2C%22Recipe_Alternate_UraniumCell_1_C%22%2C%22Recipe_Alternate_TurboMotor_1_C%22%2C%22Recipe_Alternate_Stator_C%22%2C%22Recipe_Alternate_Silica_C%22%2C%22Recipe_Alternate_Screw_2_C%22%2C%22Recipe_Alternate_Screw_C%22%2C%22Recipe_Alternate_Rotor_C%22%2C%22Recipe_Alternate_EncasedIndustrialBeam_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_2_C%22%2C%22Recipe_Alternate_ReinforcedIronPlate_1_C%22%2C%22Recipe_Alternate_RadioControlUnit_1_C%22%2C%22Recipe_Alternate_Quickwire_C%22%2C%22Recipe_Alternate_Plastic_1_C%22%2C%22Recipe_Alternate_NuclearFuelRod_1_C%22%2C%22Recipe_Alternate_Motor_1_C%22%2C%22Recipe_Alternate_ModularFrame_C%22%2C%22Recipe_Alternate_IngotSteel_2_C%22%2C%22Recipe_Alternate_IngotSteel_1_C%22%2C%22Recipe_Alternate_IngotIron_C%22%2C%22Recipe_Alternate_HighSpeedConnector_C%22%2C%22Recipe_Alternate_ModularFrameHeavy_C%22%2C%22Recipe_Alternate_HeatSink_1_C%22%2C%22Recipe_Alternate_Gunpowder_1_C%22%2C%22Recipe_Alternate_ElectromagneticControlRod_1_C%22%2C%22Recipe_Alternate_CrystalOscillator_C%22%2C%22Recipe_Alternate_Concrete_C%22%2C%22Recipe_Alternate_Computer_2_C%22%2C%22Recipe_Alternate_Computer_1_C%22%2C%22Recipe_Alternate_CircuitBoard_2_C%22%2C%22Recipe_Alternate_CircuitBoard_1_C%22%2C%22Recipe_Alternate_Cable_2_C%22%2C%22Recipe_Alternate_Cable_1_C%22%2C%22Recipe_Alternate_PolyesterFabric_C%22]%7D)

**Comment by AnthorNet** [comment]
Not related to EDSM.
That said I know some infinite loop still exists right now.
