### ISSUE TITLE
Add a fixer for respawning Spheres, Sloops and Slugs by comparing two save files.

### ISSUE THREAD

**Issue by Rainbow3D** [EDSM-NET/FrontEnd#527]
After update Patch v1.0.0.5 all spheres, some sloops and some slugs re-appeared in all save files.
I did some tests and the transition from the previous update to this one seems to be the cause, re-opnening a save file already updated and with artifacts collected does not seem to regenerate them again. Reading on reddit this seems to have happened before.
I uploaded some older saves to the editor map and the items have not re-appeared there (so older save files are still un-touched).
It would be useful to use the editor to directly compare two save files, one changed and one not, and for it to automatically eliminate all the re-spawned spheres (so the ones extra in the newer save file) and then download a third fixed file.
The number of each artifact is known, so it might also show if too many are present (even counting ones in structures) to let players fix the extras that will be missed by this.
The interactive map can already keep track of how many artifacts have been taken and their positions too, but can't delete them (or at least users can't), it can delete storage units containing them or built with them. I assume there is a list of them that the map checks to know if each is already collected or not, and I also assume the two lists can be compared to know which one has been re-spawned and then mark it as collected, make a third save file and let the user download it to put it back in the save folder.

**Comment by klightspeed** [comment]
I think you meant to post this issue to https://github.com/AnthorNet/SC-InteractiveMap?

**Comment by Rainbow3D** [comment]
Yes, I clicked on the wrong channel on the discord, sorry for the mistake.
