### ISSUE TITLE
Direct link to POIs

### ISSUE THREAD

**Issue by ibanix** [EDSM-NET/FrontEnd#53]
There is currently no way to link directly to a POI, to share with others. 

If you wish to share the details for the Witch Head Nebula, you tell the other person to do all of these:
1) Go to edsm.net
2) Click on Galactic Mapping -> Galactic Map
3) Enable 'Nebula'
4) Have them put 'Witch Head Nebula' in the search bar
5) Have them actually click the object

This is waaaay too complex. I'd like to request that each POI have an associated URL that will redirect to the EDSM Galactic Map page and open up the correct POI, like the above steps would do, but in one single step.

**Comment by AnthorNet** [comment]
1. I'm not sure how to delete that point ^^
2/3. Not true, the link are in the form that they can get you directly to coordinates and enabled layers. See: https://www.edsm.net/en/galactic-mapping#10/379/0/-741|nebula
5. I will take a look about passing to that url another parameter.

**Comment by AnthorNet** [comment]
https://www.edsm.net/en/galactic-mapping#6/2900/0/16640|nebula|232

Now working, but you need to clear your browser cache.
