### ISSUE TITLE
New Account issue 

### ISSUE THREAD

**Issue by AirHunter47** [EDSM-NET/FrontEnd#537]
Hi, I created a new account for EDSM and also logged in with frontier account as well. But still see no statistics. Everything is 0 and I've played Elite Dangerous for years. Any tips on how to fix this issue?

**Comment by klightspeed** [comment]
You should be able to import your existing journals from `shell:SavedGames/Frontier Developments/Elite Dangerous` to <https://www.edsm.net/settings/import/journal>, then use a program such as EDMC or EDDiscovery to push any new journal entries to EDSM.

**Comment by AirHunter47** [comment]
Thank you very much for your response. To "push" new entries, does that mean I have to do it manually? Or are these third parties retracting such data automatically?

**Comment by klightspeed** [comment]
As long as they are configured with your EDSM command name and API key (from <https://www.edsm.net/settings/api>), and you have them running during your play session, they should automatically push new journal entries to EDSM. Alternatively, after a play session, you can import those new journal files using the above journal import.

**Comment by AirHunter47** [comment]
Understood. I will begin the process with this information.

**Comment by AirHunter47** [comment]
Hi, just wanted to let you know that thanks to you I was able to fully synchronize my EDSM, and I'm currently using EDDiscovery in order to Automatically upload my logs. o7 and may the endless black be kind to you CMDR.

![Screenshot 2024-12-23 233422 EDSM](https://github.com/user-attachments/assets/b5bd35b4-a54d-4447-a454-803369e43b63)
