### ISSUE TITLE
Add Query Params to api-system-v1 to filter history between given dates

### ISSUE THREAD

**Issue by markjfisher** [EDSM-NET/FrontEnd#57]
The influence history is awesome but is getting quite large and will continue to grow per request.

Can you add additional parameters to limit the dates the data returns back please?

e.g. `https://www.edsm.net/api-system-v1/factions?systemName=Njiri&showHistory=1&startTS=1506643200&endTS=1506729600`

so the user fills in the appropriate epoch timestamps (above is midnight 29/9 to 30/9)

With a startTS and endTS filter history for values between the 2 given values.
Without an endTS specified, it defaults to all data since the startTS.
Without a startTS specified, it returns everything up to the endTS.
Without both it does what it does at the moment and returns all data.

**Comment by AnthorNet** [comment]
Actually the history cannot get more than 180 days of history before beginning to clean the old values.

**Comment by markjfisher** [comment]
Ah, I see. I noticed at least one chrome json parser was erroring at the current size of data (157k for about 4 months of data), and all of my queries only extend back a week, so wondered if it was worth reducing the load on the query and results sets/bandwidth to constrain by a timeframe.

**Comment by AnthorNet** [comment]
I think a debouncing was put in place, so it should not be too big
