### ISSUE TITLE
Debounce history data - improve filtering repeated old data

### ISSUE THREAD

**Issue by markjfisher** [EDSM-NET/FrontEnd#58]
The following data is seen in the faction history from Exioce, but there are plenty of examples abound.

```
"1506303617": 0.48,   # 25/9 01:40:17
"1506388943": 0.505,  # 26/9 01:22:23
"1506398208": 0.48,   # 26/9 03:56:48  ***
"1506405482": 0.505,  # 26/9 05:58:02
```

I've added timestamps to illustrate the data.
The one marked with *** is (I believe) from the following message `https://ross.eddb.io/eddn/log/47751312`:

```
{
    "header": {
         "gatewayTimestamp": "2017-09-26T03:56:52.064130Z",
    },
     "$schemaRef": "https://eddn.edcd.io/schemas/journal/1",
     "message": {
         "timestamp": "2017-09-26T00:44:21Z",
```

The message timestamp is over 3 hours different to the gatewayTimestamp, which may be due to the 'only send data when docked' setting in EDMC.

This caused the faction history to bounce back to the previous day's value.

Is it possible to improve the history storage to ignore data that would set the value back like this?

One method that may work would be to ignore data whose message timestamp is before the last known update. Additionally to store against the message timestamp and not the gateway timestamp (if that is what is happening). There was some discussion on discord that the ED client may cache faction data, so this may have to include checking if the value (here 0.48) is changing back to a previous days value.

**Comment by AnthorNet** [comment]
Related to #84 also

**Comment by AnthorNet** [comment]
Will see if it's better, older message are not processed anymore.
