### ISSUE TITLE
Can't select galactic map POI you're at

### ISSUE THREAD

**Issue by andrewgoz** [EDSM-NET/FrontEnd#62]
If you travel to a POI on the galactic map, your current position marker is laid over the top of the POI markers, meaning you can no longer click on the POI drops for information.

If your position marker could be turned off (checkbox), that would work. Or treating your current position like a POI itself and then treating the combined POIs and position marker like closely positioned POIs are already handled - by doing that thing where POIs are pulled apart so they can be individually clicked on - just include the current position marker.

**Comment by ibanix** [comment]
The option to disable your current position already exists in the selection box for POI types.

**Comment by AnthorNet** [comment]
In the right menu, under the Options tab, you can click the "My position" checkbox to hide your current position.

**Comment by andrewgoz** [comment]
Sorry guys, I would have sworn I had unticked *every* checkbox in an effort to resolve this. I have no idea how I missed that.
