### ISSUE TITLE
Provide regular dumps of all bodies

### ISSUE THREAD

**Issue by EoD** [EDSM-NET/FrontEnd#63]
Create a new dump of all bodies, similar to EDDB. Similar to https://www.edsm.net/en/nightly-dumps

As a daily dump might be tough on the available resources, a weekly dump is still interesting and useful imho.

Why another dump, when EDDB already provides one?
Well, everyone can edit in EDDB and thus the quality is lower compared to EDSM. When you try to find outliers, most of those on EDDB are mere typos.

**Comment by AnthorNet** [comment]
Soon

**Comment by EoD** [comment]
@AnthorNet can you specify this a little more?

**Comment by AnthorNet** [comment]
@EoD https://www.edsm.net/en/nightly-dumps
