### ISSUE TITLE
In API System, provide DistanceToArrival as a double instead of a whole number

### ISSUE THREAD

**Issue by MagicMau** [EDSM-NET/FrontEnd#64]
In the System API, bodies are shown with a field DistanceToArrival that is always a whole number. For example, when I call https://www.edsm.net/api-system-v1/bodies?systemName=Koamul, the planet Koamul 3 is shown as DistanceToArrival: 500, whereas the scan I made 2 days ago shows it as DistanceToArrival: 499.643860. 
Is it possible to show this value as a double instead of a whole number?

**Comment by klightspeed** [comment]
Note that DistanceToArrival is not static - it is time-varying, and the value you will get would be the most recently submitted value.

That said, I suspect the DistanceToArrival is stored as an integer, likely based on the value in EDDB also being an integer.

If it is indeed stored in the database as an integer, it would require some scheduled downtime to convert that column to a `float` or `double precision` column.

**Comment by MagicMau** [comment]
Yes, it's a continuously changing value, but it gives a good idea how far away the body is from the main star. 
I use the info mainly to generate an orrery view based on this data. Especially with moons, they now often get rounded down to the same DistanceToArrival value. Having it as a fractional number would increase the accuracy of the view, especially as the Journal now also can provide that detail.

**Comment by AnthorNet** [comment]
Applied to both stations and bodies.
