### ISSUE TITLE
Calculate Jumponium system and list them

### ISSUE THREAD

**Issue by AnthorNet** [EDSM-NET/FrontEnd#65]

**Comment by AnthorNet** [comment]
@ibanix Could you state what exactly makes a system a jumponium system?

**Comment by klightspeed** [comment]
https://forums.frontier.co.uk/showthread.php/302833-Prospection-Farm-Locations-for-Engineers-Jumponium
https://forums.frontier.co.uk/showthread.php/236381-DISTANT-WORLDS-Cartographic-amp-Prospecting-Public-Service-NEW

J1: Vanadium + Germanium
J2: Vanadium + Germanium + Cadmium + Niobium
J3: Arsenic + Niobium + Yttrium + Polonium
Green system: Yttrium + Polonium + Arsenic + Niobium + Cadmium + Germanium + Vanadium

**Comment by ibanix** [comment]
@AnthorNet The above is correct; landable planets in system that contain all of: 
Yttrium + Polonium + Arsenic + Niobium + Cadmium + Germanium + Vanadium

They really also should not be high-gravity (above 3g) for pilot safety.

**Comment by AnthorNet** [comment]
Within the same planet or system wide?

**Comment by ibanix** [comment]
System-wide

**Comment by AnthorNet** [comment]
We now show an alert for GREEN system.

![image](https://user-images.githubusercontent.com/654353/32539354-756b2c68-c469-11e7-93e9-effe9838b434.png)

Test shown that almost 33% of the systems are green, so not sure it worth adding a list of them.
May be I can expand the thing by storing that in database for the advanced search

**Comment by AnthorNet** [comment]
Seeing how much of them they are, we can now simply find nearby systems to commander and check the icon: https://www.edsm.net/en/search/systems/index/onlyPopulated/0/radius/50/sortBy/distanceCMDR
