### ISSUE TITLE
Adding/updating a comment on a system adds 17 copies of the comment (in the comment stream)

### ISSUE THREAD

**Issue by claycle** [EDSM-NET/FrontEnd#68]
1. Add a comment to a system
2. Later, return to the system, edit the comment.
3. View comment stream (from Dashboard/Comments)
4. 17 copies of the comment now appear in the comment stream

System where comment was made:
https://www.edsm.net/en/system/id/24734/name/HR+1185

Comment stream link:
https://www.edsm.net/en/dashboard/comments (user Macallen)

**Comment by claycle** [comment]
Repeatable.

But only on HR 1185.

**Comment by AnthorNet** [comment]
Tried and couldn't reproduce, will check more in the database tomorrow.

**Comment by claycle** [comment]
Here is a screenshot of my comment feed showing what is happening:

<img width="1207" alt="screen shot 2017-10-18 at 12 53 57 pm" src="https://user-images.githubusercontent.com/419840/31734180-7ec5ede6-b403-11e7-9cd6-e2c55b1843dc.png">

**Comment by AnthorNet** [comment]
Morning,
Can you test again?

**Comment by claycle** [comment]
Looks much better.

**Comment by AnthorNet** [comment]
Great!
