### ISSUE TITLE
List record breaking stellar objects found. Related to the "Bigger, Better" badge.

### ISSUE THREAD

**Issue by Jastebro** [EDSM-NET/FrontEnd#70]
So, I had this idea...
Among the badges you can earn is one for finding galactic records, but it doesn't show what record you've found (to my knowledge).
It would be cool if EDSM could track that too, since it apparently can detect if you've found some record breaking stellar object. 

If this is possible, it can even get turned into an automated version of the long dead "Universal Cartograpic Records" that logged them manually, before the admins lost interest.

**Comment by AnthorNet** [comment]
Will be part of #80
