### ISSUE TITLE
Bug in ship import from EDMC

### ISSUE THREAD

**Issue by Gerdofal** [EDSM-NET/FrontEnd#72]
Noticed something odd in the ship import from EDMC. I've tried this multiple times, deleting ships and then watching them come back in, and it's consistent.

My Eagle, Viper Mk IV, Asp Explorer, and Python all show up as expected, and they get the cargo, fuel level, and outfitting links as expected.

My Federal Corvette shows up, but does not get the cargo, fuel level, or outfitting links.

This is the build of the corvette when this happens: [https://eddp.co/u/iLkMdx8X](url)

See attached image.
![shipscreen](https://user-images.githubusercontent.com/6471848/31917744-a8bc853c-b805-11e7-8ff0-14bfba11838b.JPG)

**Comment by AnthorNet** [comment]
It can happened when the URL is too long for Coriolis to be processed.
I should update the import page to use POST request.

Can you send me the file you try to import for further tests?

**Comment by AnthorNet** [comment]
Can you also test again and tell me if it works now?

**Comment by Gerdofal** [comment]
Will do. Should be able to test tomorrow :)

**Comment by Gerdofal** [comment]
Sorry, not resolved.

Deleted ship and allowed it to automatically import again from EDMC.  Ship created, but links to build/cargo/etc... are not present. (Screenshot looks virtually identical to the one I sent above)

Full Coriolis link from EDMC at this time is:

https://coriolis.edcd.io/import?data=H4sIABFq-lkC_-1bbW_bRhL-K4GAu94BMbGz75v7VFt2ktZpfZZx-Sgw0lomQpHCknTqFv3vN0takpcSTUp5O6CXD45MmzOzu8_MPDOz_mN066wdvbqN08K-HCXz0SuAl6M0rrLZ3Wn8UIxe_TGapHlJxHSS_G5l_X31oX7kP6d5PM-rcvRqVH7KRy_X3_8SL1Hq6B_X-aKyf__ldHL1r4t_4o-z5nmSze3K4pesnN4mi7vSutGfL9eC4QsL9pK9WFIvgXUvoShj599oa5tsnj-qKW1RfqgWiwcUjtKX-bxKbb1XP7plXjn_qXnoP-1uMdWEG6bIRuCFnVsXl0meTc9yd2_L0k4bUdPXLp5bQN15NnpVugplrFySu6R8QEkvR_dxWqEI4g0Z21mcQr92qUEx2GivX5uOE1x_Vr7PXTovDtBH-_UpRgWjLX1Xafxg3WuXV6vp5Pzq6gCV7JuqPM8WSWbP8nTQySpOFJUbxY8vV0WZL5OiOeKrJPs4TPWFQymTu-S2HLvkvtaJ5_PxbXbl8oWzRTFFY5LbZFYLrhH4a1XeJmWZZIuLxKbzm4eVnZ7meXmTLOv350mxwm34T6NlRCPG_zbaaIWIUMaEpoRxRRSasE_exWT8xsbldVzuEykjQUKRUhBquORSUugW-euqTJZx-i4uij1SOY0MBGI5NcAEmguS6Q6xb7PSLpqt3ZF4Qklk9BORJFKGoDDDUTCYrtV3GHjCIAIaWMgAwBjQmjLKO6X9dlHZ9Mq6n6rlao9cFlERbidCGzgCHFfeIfQq_2Td2MWf9tkJMlLhmYNE1AJQikEJPO5sjVpbw339-S3imxEChGx__ss6fKXJDDf5xUXsCltHSmdnycpe2nubjl6J9ffr35-Mp5d5triOs4UdbSJoZ7CUHKjauBSe6fQNrtLNvU80eWl6luKpiA6vItu1MiWoJLR2Ltz2mxhdsT9aS84ECQxYv1yrF4161uvUmhFTO_abamHfxG6-ypOsSXjH-PU4XsaL_V6tdcurEYRSaUmJoB2gaaQhECd2lmfzLyYW84pLPlRl3oVIESkVihVKCiYU5UDYEZ5NRaRlIJEKjX6NKEL_hgP9mvOItCIPegv1Tmgko91-nSyrZQPxXamGRSY00TCD2yiBEwH6KL82kQwjBRjJEe9MSaJ73BqdYsetb_L5ix9u7uyLU0Q3EqAfXryb_btKsqzPv9_beIV57gAXR0ZizDZrvlmV03dVWiZncZahpNfJ8gPmb-81HT5GN8sWnBIjCaosVmgUJpS2Kz0-n85y5_LCx5Dizqa4jqxK0x3vpMd6ZxeegEc8xDtwrrgxphPs_WDSpgUmbSinghotzVFgUpEJszgobbQwFFOu7kqNCBaHKfwS6fO-TEbDxEMiqagwUiimKf73f4juQDTJZljOJLF7mCJrzZCYb0B6GbsvkkN6w_OJwDjfis-EEmAUoz_jR8RnQLyGERWYBvB0iQolDozPVCHDDKO9IpIipTH0ORb3rEsJGkEYTAUFjusl2hApj3EpFakWkVOKK6XRTaXhfbRL7wE_4n78CSPXLuNinw13rFBxAwO4X1X4C5dxYd1p5YpyelM5Z8tpDcRezEuNJcUQyBczLHo-pBiU8QHKWz6BfHJrJ9VqlbtyEGkDYQLS9uT9p7yNdhjPNsYrw3l9Qu_iJGtKumKQBcSEvLV5t1auhnJW5J5GKC5r_XaeVMvQ6_vPkYVh69TGy_oY1yfYSO09QswAWBmJPXbQ72ZHkiYlRkcypOshteAyLCMQWNc2yW5zN7NL3zUaAIstnce0JQgJ7KDf144rxGf5U_5hWJ_CbGua9YvTfa2od7aMUyzx6PR1ns57z6exJI0z67fkx9XK5fHsblIlTbugZ3cUZRA6TSMqlNO3JRhUayvqgLxNcYOclrb1t4TUh6OHui8uR4LRbGOOX055bLr2fZfzW_y1xGazvV0NE0GYW4kBwPIMhK9YjumTmIjJgLYZH1uVppxRZQ5M1xqrp1AYCKGQ-ypkgvBsQ-MsXsWzDkaBSZ-FjAIo5hvEE1P8a_Q0oJVht0fr223IReeDGhtIVHaxtqrFDEgSsDdJXMfzeCDSBQ-0T2xW5K54CvD-5Ii0iDKp6j77XbJ6OyYDoo_QRm29zO8hLhpDTSMBDcgWqb30uRKZ_Wxgu7R5Gb6n-p-T8rRaruywTjFR_NkZgJf4MSlh2sjkB9kxwdScDjZEDDPkUSgcZMlNnKTDzNBkmBleIj3Ihvd4pMVAI-QwI2qRB5yJh9lA3xB6Dziv0B0xSllHMBE7-3CYZvj2mv2IDZo4dvTowuUfbXZtF_hl_7jBt_GlarXxGdaRXHFtDO1qf5zlSGkK1H1ti3r0Nds_zDAsTFeMKNAgJOems6l_nlm3eLiyrjZ83zRjp6nPKZdAJddKd2XU899Wad2vetZiwSIepmvum6mYYDVFHV39yp8x2JXJ7FnRnEcQihZCc18SMy2NEMdUxSxi4eEZKX0zCPeDCd3VCH0WEBpr9RbF4AhtTYBLQrsaAugn-PG1zZ6fQ7F2X4Aw4IJjbcM19ImelA7dqLzb17Om7ekRpQDKKKEIHtxzDbeeUztBciRNixxJLZHBKcVMLzna03Y7T-8TF794F7uyqj72NR82y_ehFOnzptIZQJGkAsZCOt4W94QnselFXJS90UlRiWxJb2IU3cao_kEQDynTWewW-TVyhKd29KdH8Bsr1MYE9v1N4NsrHn0FLJawsDMOm8zyfDVkHMe3tZFWkknYZgsx1AaFlQdr2dBc-DiNH54aAf0zQQwNhpmNDbIpvoeUqoBBKrBh7HJ_VSArXZ7WGcbOavLwpJzv3xUp6-7w2h411J4vOqaEjX5dv8yH4IIJGZ7JpLRpGrvTfP6ABfQsv7fuYTKLM_Td6Y_zex-x5v1AZYD5fLshZrhBaFLoK2NbInW080nlbuOZXdtyk2T9pIbCus3Svk_U29KgOuxEnvrbQ2uk0ucrrS0wQLNHXGB-Sr_i_PiERCS8GWGMAUUUgowijzh6gnys4N4hBdvhaZJIgzGCMCLpoRMFFonWRAGRzZDvcdY5m-0ZKEhceThQk6T-R5nmcNSMzkRUtjo9VFLl6RNT6n9yoKCGDBRqdPd2GTlHRrfrDPQrDsKAhRyNRFpqzdG7hVYgjumt8Ui2_EEwwChDOHDN9YHABRXpnaktQR4pOBYsR15VwIKChR1FwdCptECQAT3qChIjYUsRIvRTv4cU_5fwl4GuTzufH8aH1YU0oq3Gq1ISpBRUc3nUGPdkn0iBpZs2ipjOO3lDKs3jjO0pNHXrpiMGXoIh03BM7J9RX7GIQiv1KG24ACS3WMB9g95zUxE1bWdfXnlj_XXR_urKe3E4lAtleXpChvagMZNpsYtr-rVxzUkLKsIgn9CirvKOwTVEXIQiNYJaY-HFsCj_PFwfY2xnuI9U62IGKAz4wLgxnX2OPidhbSdh_ioFOnQnSRniJH0L_6s7yZAyQlLBSGDHmUuWmxrmiRnQX0qAALZjBR9mBQ1z4VmaV_M9VrB-K3y2FztmiEHXCQSlYUpGncv4ygsY21uLOFxn5Wequ6dtACV3TZEDd6R1Lr4j8wXPRQ27VfDVUaq_68E0xG3wH2IwDNXbqvvx5eAPMU69_AGjjD-fmwehgKKeGuKPL88vT_j48clj3MEImMRZ-WLsLD5w2xj4x-iu8rdOQSB8MMDqJ39JBBo5IjUCD7TMy9izWGYklv8SoVJlaR5nFpepjTYCGcZ_AeNAysPINQAA

**Comment by klightspeed** [comment]
What version of EDMC are you using?  At least 2.45 is required to correctly update EDSM with those long Coriolis links.

**Comment by AnthorNet** [comment]
Ok I thought you were using the fleet import on EDSM, using the raw JSON from EDMC. ^^

**Comment by Gerdofal** [comment]
2.4.5.1 is the version

**Comment by AnthorNet** [comment]
Should be good now with the new API
