### ISSUE TITLE
Badges: Bigger, Smaller, Hotter, Colder

### ISSUE THREAD

**Issue by PaulHedges** [EDSM-NET/FrontEnd#79]
I see that one of my CMDRs has obtained this badge, but not able to determine which record I hold.  I visited the Statistic pages and strolled through systems and celestial bodies pages and did not see the CMDR on the list.  Is there are way to determine the record?

On a related note, maybe a Feature Request.  It would be nice to be able to click on a badge and be able to see the relevant data.  This may not work for all badges, such as Play Time or Paintjobs.

CMDR name: Reise Lang

Thanks!

**Comment by AnthorNet** [comment]
THis will be part of #80
