### ISSUE TITLE
Galactic Record Revamp

### ISSUE THREAD

**Issue by AnthorNet** [EDSM-NET/FrontEnd#80]
This issue is there to summarise all the issues concerning the records ;)

- [x] Records should be a page at the top menu, and include all TOP 100 pages in their sub-menu.
- [ ] Needs to be calculated at night, the scanner is actually doing them, but it holds the background process for too long.
- [x] Body scanner should be shown instead of system discover when available.
- [x] Record badge should asing body id when possible.
- [ ] Record should be shown on system page.
- [ ]  New Water Giants badge

**Comment by NoFish22** [comment]
I was told to list my sugestion for the records, i was under the impression that this was already in anyways.

1: The ability to find my own personal records, ie CMDR Joe wants to see the largest O type star he has found. or CMDR Joe wants to see the largest system he has found. and so forth

i should also be able to share this list and compare it with friends, hell maybe a group list or something. so in our group,clan,thing? CMDR spaceman has found the largest O type star. 

2:  The ability to search by estimated monitary value of a system. and find the system you have found that gave you the most money.

3: The ability to filter one answer records, a good example would be Sag A, VY Canis Majoris, this would be hard to do, not sure if it would be acomplished by having a procidurally generated system check by outside bubble/known space or something not sure.

I just dont want to see one answer hand placed records it gets rid of the entire point of having a record.


Im not sure this is even the right place to list this stuff, in fact im pretty sure its not lol but whatever. if i get any more good ideas ill list them.
