### ISSUE TITLE
Option to only show green systems in advanced search

### ISSUE THREAD

**Issue by Jim-Anderson** [EDSM-NET/FrontEnd#81]
The "green" icon for systems that have all jumponium materials is nice, but it can be tedious to find a system nearby. For instance, I'm 551 ly from a green system, but I had to wade through 13 pages of advanced search results to find it.

It would be nice to have an option in the "show all systems/show populated systems" dropdown for "show green systems", so you could display only the known green systems near you.

**Comment by AnthorNet** [comment]
Not sure, the main trouble is performance about calculating them and store them for processing, right now, it's calculated per system on the fly, which makes it possible.

**Comment by Jim-Anderson** [comment]
You know, the more I think about this, the more I think it could be fairly easily done (I know, famous last words, but hear me out, I did the search service for HBO GO, so I'm not speaking from total ignorance here :D )

Right now you're doing a paged search out to X light years, which means you have all the data you'd need in the results as-is. Instead of presenting it per-page and doing the system calculations on the fly, you could run through the *whole* set of results and discard any that aren't green. It would take longer, and I imagine you'd want to set some sort of upper limit to the value of X, but I also imagine this wouldn't be a search people would be doing too often.

**Comment by AnthorNet** [comment]
Starting implementing ;)
Main trouble is ALTER a big table. I might end just adding a new one.

**Comment by AnthorNet** [comment]
Done, just give the database a little time to fill all the systems ;)
