### ISSUE TITLE
Add distance to SagA as a record category

### ISSUE THREAD

**Issue by Jastebro** [EDSM-NET/FrontEnd#86]
THe current distance categories are Sol and Colonia.
Having distance to the center of the galaxy as a category for records seems relevant.

**Comment by AnthorNet** [comment]
Soon

**Comment by klightspeed** [comment]
The furthest from Sol would in theory tend to be on the north edge of the galaxy (12 o'clock).  In practice the furthest systems from Sol tend to be around The Solitude Void (about 65.5kly, 12 o'clock).

The furthest from Colonia would in theory tend to be at around 2 o'clock on the edge of the galaxy.  In practice the furthest systems from Colonia tend to be around the Silentium (about 50kly, 1 o'clock) and the Tenebris (about 50kly, 3 o'clock).

The furthest from Sagittarius A* should not in theory prefer any edge of the galaxy.  In practice the furthest systems from Sag A tend to be on the edge of The Perseus Fade (about 45kly, 5 o'clock) and The Abyssal Plain (about 44kly, 10 o'clock).
