### ISSUE TITLE
Distance page generates host system as first distance when generating stars to get distances for

### ISSUE THREAD

**Issue by RapidfireCRH** [EDSM-NET/FrontEnd#87]
When landing on Distance page for a star, it generates an entry for the host star as the first distance needed. Ive reproduced on two pages and even tried refreshing the page.

**Comment by AnthorNet** [comment]
THe first distance should be the current CMDR position, apart if you're looking at that system?

**Comment by RapidfireCRH** [comment]
Well it should check if that is the host system, because it takes up the first slot when opening the distance page. i open up distances to put in a group of distances, i do it form the system i am in.

**Comment by AnthorNet** [comment]
Please try again, should be fixed :)

**Comment by RapidfireCRH** [comment]
That works, thanks
