### ISSUE TITLE
Ability to adjust time frame for credit/loan graph on profile

### ISSUE THREAD

**Issue by radioactiv** [EDSM-NET/FrontEnd#89]
It would be nice to be able to select what time period is shown for the credit/loan graph (last 3 months/last year, etc).  

As an example, here's my profile: https://www.edsm.net/en/user/profile/id/10124/cmdr/37Penguins
The graph goes back to December 2016, but I don't think there was an api to report credits back then (or it wasn't being reported correctly by some tools).

**Comment by AnthorNet** [comment]
Hello,
Yes that part needs a little fix, but you can also try to upload all your old journal files here: https://www.edsm.net/en/settings/import/journal

It should update the old Unknown entries and get you a better chart along with a full detailed account book.

EDIT: From what I see on your chart, it's the max plot limit of the charts being applied.

**Comment by radioactiv** [comment]
My guess is that because loan and credit are on the graph it can't scale when it always has to have the lower limit at 0 (or a low number for cmdrs who had to take a loan).
