### ISSUE TITLE
[FEATURE] Add a heatmap representing the systems with known coordinates to Galactic Mapping > Galaxy Map

### ISSUE THREAD

**Issue by WaldemarLehner** [EDSM-NET/FrontEnd#92]
My proposal would be a new layer for the Galaxy Map (https://www.edsm.net/en/galactic-mapping) which updates every week or month by taking the systemsWithCoordinates.json and plotting it onto an overlay image. 
One could map for example 10ly*y*10ly onto one pixel of said image and represent one system by one color value (rgb( 1, 1, 1) for one system in said area, rgb( 23, 23, 23) for 23 systems in said area ... from 255 onwards it's just pure white).

Was thinking of something like this:
https://i.redd.it/81zlytqvkprz.png

[Here is my code by I doubt it'll be of any use since it's poorly written](https://github.com/WaldemarLehner/EDEDSMVisualizer)

**Comment by AnthorNet** [comment]
I did some tests about it:
https://cdn.discordapp.com/attachments/156642424339300352/387992499588956160/2017-01-05.png

**Comment by AnthorNet** [comment]
It's in the Galactic Mapping > Traffic Report.
