### ISSUE TITLE
Suggestion on completing coordinates

### ISSUE THREAD

**Issue by SirAdams** [EDSM-NET/FrontEnd#94]
I have a suggestion regarding https://www.edsm.net/en/systems/front
Can you do it so that the layouts to which I entered co-ordinates from my current position / system did not show up on this list.

CMDR SirAdams

**Comment by AnthorNet** [comment]
If you go to the current system you are, on the distances page and generate reference or pushed systems, the systems you already done should not be shown.

**Comment by SirAdams** [comment]
Do not close if you do not understand what I mean.
Now I'm on the expedition and every X jumps I want to update the data from my current position to the planets on this list:
https://www.edsm.net/en/systems/front
So I open the planets on this list in the tabs and write the distance from my position to them. But if I refresh the page https://www.edsm.net/en/systems/front, I do not know which items have already been updated and I need to open and check whether the entry is already or not.
I entered the first 10 items, go to sleep and then before the jump I want to finish, so again i need check positions.

**Comment by SirAdams** [comment]
And the second thing. What if I want to update entries to more than 20 items? With the current system, this is not possible because after refreshing most of the items are the same only the order can change.

**Comment by AnthorNet** [comment]
I understood the first time...
The list in the front is only containing 20 entries on purpose, there is no reordering, if they are coordinated they moved on, then another is added at the end of the list. If you want more than 20, then you can check the [Unresolved Systems](https://www.edsm.net/en/systems/unresolved) list where the first one in that list is the one added to the pushed to front list.

Again if you only want the list from where you are, and without the distances you already submitted, take the from the distances tab of your system. Only systems for which you didn't send distances will be generated.
