### ISSUE TITLE
Missions that show as accepted yet have expiration dates in the past cannot be manually removed

### ISSUE THREAD

**Issue by MooseOnTehLoose** [EDSM-NET/FrontEnd#98]
https://www.edsm.net/en/dashboard/missions shows some missions that cannot be completed due to having expiration dates in the past. There does not appear to be a way to manually purge these entries.

![missions in past](https://user-images.githubusercontent.com/549934/33801982-976c2ad0-dd3a-11e7-84fa-ba07c94c56b1.png)

EDSM should recognize expiration dates of missions and take some action once a mission expires but has not been marked complete, failed or abandoned in a set time period.

**Comment by AnthorNet** [comment]
After accepting another mission, the expired one should no longer be shown.
For now they will just fall into the limbo until we find a better solution.
