### ISSUE TITLE
System Traffic Report and 3D Map confused by Multi Crew.

### ISSUE THREAD

**Issue by ghost** [EDSM-NET/FrontEnd#99]
Hi,

the traffic report on System Summary gets confused by Multi Crew. A CMDR joined my ship in MC and the traffic report shows now that 2 ships passed through the sector. Even so the CMDR who joined me was never in that system. Also the 3D map on the Expedition site shows straight lines after a MC session.

Fly/land safe.

CMDR Steyla

**Comment by AnthorNet** [comment]
That entirely depends on the software you are using, to send or not the multicrew part.
EDSM is not aware of it at all, except if you are using our journal importer which will not (theoretically) sed the multi crew flight logs except if you are the captain.
